### ISSUE TITLE
Duplicate group table created

### ISSUE THREAD

**Issue by ebuildy** [sonata-project/SonataUserBundle#1010]
### Environment

MacOS, php installed via brew.

Demo project: https://github.com/ebuildy/sandbox-sonata-user

#### Sonata packages

```
sonata-project/admin-bundle          3.31.1  The missing Symfony Admin Generator
sonata-project/block-bundle          3.12.0  Symfony SonataBlockBundle
sonata-project/cache                 2.0.1   Cache library
sonata-project/core-bundle           3.9.0   Symfony SonataCoreBundle
sonata-project/datagrid-bundle       2.3.1   Symfony SonataDatagridBundle
sonata-project/doctrine-extensions   1.0.2   Doctrine2 behavioral extensions
sonata-project/easy-extends-bundle   2.4.0   Symfony SonataEasyExtendsBundle
sonata-project/exporter              1.8.0   Lightweight Exporter library
sonata-project/user-bundle           4.1.1   Symfony SonataUserBundle
```

#### Symfony packages

```
friendsofsymfony/user-bundle         v2.0.2  Symfony FOSUserBundle
symfony/monolog-bundle               v3.1.2  Symfony MonologBundle
symfony/phpunit-bridge               v3.4.4  Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.6.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu            v1.6.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                v1.6.0  Symfony utilities for portability of PHP codes
symfony/security-acl                 v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle           v2.6.7  Symfony SwiftmailerBundle
symfony/symfony                      v3.4.4  The Symfony PHP framework
```

#### PHP version

```
PHP 7.2.2 (cli) (built: Feb  1 2018 11:50:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologie
```

## Subject

Doing ``doctrine:schema:update --dump-sql`` I see 2 tables ``fos_user_group`` and ``fos_user_user_group`` are created.

## Steps to reproduce

- from a fresh Symfony 3.4 install ``symfony-installer new test-sonata 3.4``
- following tutorial here https://sonata-project.org/bundles/user/master/doc/reference/installation.html
- extending with ``sonata:easy-extends:generate SonataUserBundle --dest=src``
- running ``doctrine:schema:update --dump-sql``

## Expected results

A single ``fos_user_group`` table should be created.

## Actual results

2 tables are created, so the group feature is not working properly.

## Possible bugs

I suspect the DoctrineCollector from the extension: https://github.com/sonata-project/SonataUserBundle/blob/4.x/src/DependencyInjection/SonataUserExtension.php#L230 that will create the wrong table, because Doctrine schema tool https://github.com/doctrine/doctrine2/blob/2.6/lib/Doctrine/ORM/Tools/SchemaTool.php#L546.

Also, if I set the same table name as FOS does, I got the error: "table already exists".

**Comment by jordisala1991** [comment]
`fos_user_group` table is for the groups, `fos_user_user_group` is to store the relations between users and groups.
It is a many to many.

Closing, if you think this should remain opened, just ping me with your exact issue.
