### ISSUE TITLE
Atk::Version gem

### ISSUE THREAD

**Issue by kigotho** [sonata-project/SonataUserBundle#1049]
/.rvm/gems/ruby-2.5.0/gems/atk-3.2.9/lib/atk.rb:47:in `<module:Version>': uninitialized constant Atk::Version::MAJOR_VERSION (NameError)

**Comment by kigotho** [comment]
using GTK3

**Comment by OskarStark** [comment]
Are you sure this is the correct repo? 😕 ❓

**Comment by kigotho** [comment]
Ohh NO! sorry guys
