### ISSUE TITLE
Route fos_user_profile_show not found after password reset

### ISSUE THREAD

**Issue by wizardz** [sonata-project/SonataUserBundle#105]
Based on documentation http://sonata-project.org/bundles/user/2-0/doc/reference/profile_edition.html fos_user_profile_show should be removed from routing, but it is used in 
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/ResettingController.php#L146 to redirect user to profile after password reset. As result route not found.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
