### ISSUE TITLE
i am facing The service "sonata.user.admin.user" has a dependency on a non-existent service "sonata.admin.manager.orm".

### ISSUE THREAD

**Issue by HaseebIsmail90** [sonata-project/SonataUserBundle#1050]
i am using sonata user bundle devmaster 
The service "sonata.user.admin.user" has a dependency on a non-existent service "sonata.admin.manager.orm".
can't find problem

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.39.0             3.39.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1             3.12.1             Symfony SonataBlockBundle
sonata-project/cache                     2.0.1              2.0.1              Cache library
sonata-project/core-bundle               3.11.2             3.11.2             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1              2.3.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.0              1.1.0              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.2              3.6.2              Symfony Sonata / Integrate Doctrine ORM into the S...
sonata-project/easy-extends-bundle       2.5.0              2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1              1.9.1              Lightweight Exporter library
sonata-project/google-authenticator      1.1.0              2.2.0              Library to integrate Google Authenticator into a P...```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
#########################
symfony/monolog-bundle     v3.3.0  v3.3.0  Symfony MonologBundle
symfony/phpunit-bridge     v3.4.16 v4.1.5  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.9.0  v1.9.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.9.0  v1.9.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.9.0  v1.9.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.9.0  v1.9.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.9.0  v1.9.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.9.0  v1.9.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.9.0  v1.9.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.3  Symfony SwiftmailerBundle
symfony/symfony            v3.4.16 v3.4.16 The Symfony PHP framework
```

#### PHP version

```
$ php -v
##############
PHP 7.2.10 (cli) (built: Sep 13 2018 01:01:10) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

<!--
    Give here as many details as possible.
    Next sections are for ERRORS only.
-->

## Steps to reproduce

## Expected results

## Actual results

<!--
    If it's an error message or piece of code, use code block tags,
    and make sure you provide the whole stack trace(s),
    not just the first error message you can see.
    More details here: https://github.com/sonata-project/SonataUserBundle/blob/4.x/CONTRIBUTING.md#issues
-->

**Comment by kunicmarko20** [comment]
We have a bug report template for a reason, please fill it.

**Comment by maavia10** [comment]
Environment
Sonata packages

$ composer show --latest 'sonata-project/*'
3

Symfony packages

$ composer show --latest 'symfony/*'
3.4.1

PHP version

$ php -v
7.2

  The service "sonata.user.admin.user" has a dependency on a non-existent service "sonata.admin.manager.orm".

i am also facing this issue 
i have just install fresh

**Comment by fedy95** [comment]
This string is helped me for symfony 4:
- composer require sonata-project/doctrine-orm-admin-bundle

**Comment by v0ff4k** [comment]
but what need to do if i using symfony 3.4  ?  with  "sonata-project/doctrine-orm-admin-bundle": "3.6.1" in composer  )

**Comment by v0ff4k** [comment]
i founded mine solution, i have not setted `new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),`  in app/AppKernel.php

**Comment by Liuck** [comment]
composer require sonata-project/doctrine-orm-admin-bundle 
解决 symfony4 依赖问题

**Comment by phansys** [comment]
@HaseebIsmail90, did any of the above suggestions helped to solve your problem?

**Comment by piedrucci** [comment]
> i founded mine solution, i have not setted new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(), in app/AppKernel.php

This works for me too!.. Thanks so much...

**Comment by core23** [comment]
Can you please update the docs @piedrucci @v0ff4k

**Comment by persfrancobe** [comment]
did you find any solution for this issue?

**Comment by jordisala1991** [comment]
The docs are updated now, this is no longer relevant
