### ISSUE TITLE
Question: use of request->getSession while Session injected?

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataUserBundle#1056]
## Feature Request

Symfony did Deprecate use of getSession without using hasSession first
https://symfony.com/blog/new-in-symfony-4-1-session-improvements#deprecate-some-uses-of-request-getsession

what should we do about it?

there are 4 places where getSession is used:
```
 grep "getSession(" -R
src/Action/LoginAction.php:        $session = $request->getSession();
src/EventListener/TwoFactorLoginSuccessHandler.php:            $request->getSession()->set($this->googleAuthenticator->getSessionKey($token), null);
src/GoogleAuthenticator/InteractiveLoginListener.php:        $event->getRequest()->getSession()->set($this->helper->getSessionKey($token), null);
src/GoogleAuthenticator/RequestListener.php:        $session = $event->getRequest()->getSession();
```
LoginAction already does inject Session service, why can't we use that?
or is there a case where that is null?
in the rare case of getSession returning null there it would crash without hasSession

Google RequestListener: has no Session service, but it only goes there is the TokenStorage has token?
can the Session service be used there too?
the same might be true for the other two cases

**Comment by greg0ire** [comment]
:thinking: I wonder what the session service looks like when there is no session. Also, isn't that service going to be removed?

**Comment by Hanmac** [comment]
@Greg0ire I don't know right now, I don't have a system to test at the moment.

I think it might not matter because most of the functions above should only be useable when having a user, and for this you need a session right?

**Comment by greg0ire** [comment]
Makes sense. Anyway, if this should break, we should get deprecations from Symfony.
