### ISSUE TITLE
Remove account indication on password reset

### ISSUE THREAD

**Issue by n3o77** [sonata-project/SonataUserBundle#1086]
## Feature Request

As in the FOSUserBundle ([PR](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2250)) it would be good to suppress explicit feedback in the password reset process to not leak account information.

I'm happy to provide a PR in the next few days / weeks but would appreciate some feedback on this.

**Comment by OskarStark** [comment]
This would be a great improvement, we appreciate a PR 👌🏻
