### ISSUE TITLE
Support HTML in password reset email

### ISSUE THREAD

**Issue by invfo** [sonata-project/SonataUserBundle#1094]
## Feature Request

It would be nice to support HTML markup in password reset  email.
Today, all HTML is escaped when creating the email [(code)](https://github.com/sonata-project/SonataUserBundle/blob/1d5485b1aed36f6a051ec25e8aa118c2c1de1a38/src/Mailer/Mailer.php#L72). The solution would be to set `content-type` to `text/html` [here](https://github.com/sonata-project/SonataUserBundle/blob/1d5485b1aed36f6a051ec25e8aa118c2c1de1a38/src/Mailer/Mailer.php#L76) by passing a second `"text/html"` argument to `setBody`.

I could provide a PR with a fix.

**Comment by VincentLanglet** [comment]
Shouldn't this issue be closed since we're using the `html` method of SymfonyMailer now @jordisala1991 ?

https://github.com/sonata-project/SonataUserBundle/blob/3ffcd23b676292ab474f93b30d9a9ae94a2ee193/src/Mailer/Mailer.php#L79
