### ISSUE TITLE
Remove FOSUserBundle inheritance

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataUserBundle#1112]
## Feature Request

This bundle is dead: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2874#issuecomment-462644756

There are some threads that were asking for new versions:
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2927 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2917 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2874

So we should remove the coupling to this bundle and fork/implement some of the basic functions here.

**Comment by grimabe** [comment]
Regarding the lack of maintenance of FosUserBundle and Symfony 5 release approaching this issue is getting more urgent. I don't know if there is a roadmap at Sonata somewhere but I am curious to see if there is any news about this issue ?
Thanks

**Comment by core23** [comment]
This is not a topic we're working on at the moment. Our top prio is to release new major versions of our bundles. 

Maybe you can help on this topic @grimabe ?

**Comment by core23** [comment]
FYI there is a new bundle which is a hard fork of the FOSUserBundle with some major cleanup: 
https://github.com/nucleos/NucleosUserBundle

I will create some additional bundles which will add a frontend profile and registration

**Comment by VincentLanglet** [comment]
Do we need these new bundle ? 

I understood in the FOSUser issue that they recommend to use the maker-bundle and this documentation https://symfony.com/doc/current/security.html

**Comment by core23** [comment]
> Do we need these new bundle ?
> 
> I understood in the FOSUser issue that they recommend to use the maker-bundle and this documentation https://symfony.com/doc/current/security.html

Not sure if we need user bundles anymore, but I don't like the "there is only one way for a user provider" approach that symfony does. It will work for most cases, but there is no alternative way anymore.

**Comment by haivala** [comment]
I have been digging this for a while now and seems that there is many ways to do this but I just need to ask this: What is the recommended way to upgrade a project with SonataUserBundle not to use FOSUserBundle so that it is future proof? I'm using Symfony 4.4.

**Comment by VincentLanglet** [comment]
> upgrade a project with SonataUserBundle not to use FOSUserBundle so that it is future proof

I'm not sure you can as long as SonataUserBundle use FOSUserBundle.
PR should be done first on this project to remove the dependency.

**Comment by haivala** [comment]
So what you are saying is that the maker-bundle way does not work with SonataUserBundle?

**Comment by VincentLanglet** [comment]
> So what you are saying is that the maker-bundle way does not work with SonataUserBundle?

I don't know. I don't user makerBundle and I don't use this bundle.

What I'm saying is as long this bundle is using FOSUserBundle, you can't use it without FOSUserBundle.
And when someone will remove the FOSUserBundle usage, you certainly have changes to do in your code.

**Comment by haivala** [comment]
Just out of curiosity and little bit off topic but what do you use for user management then?

**Comment by VincentLanglet** [comment]
> Just out of curiosity and little bit off topic but what do you use for user management then?

I'm just using User/LoginForm as described in the Symfony doc https://symfony.com/doc/current/security.html
And I created a UserAdmin with SonataAdmin.

**Comment by haivala** [comment]
So just to be clear that is the same as using the makerBundle

**Comment by haivala** [comment]
As this is now closed: https://github.com/sonata-project/SonataUserBundle/pull/1121#event-3738315863
I suggest that the discussion should be in this issue
