### ISSUE TITLE
Remove oppressive words from code

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataUserBundle#1191]
## Feature Request

We should avoid terms like *blacklist*, *whitliste, *master*, *slave*, ... and use more tech-related words like *blocklist*, *prmary*, *secondary*,...

In this repo, we use the term *whitelist* which could be replaced with *allowlist*:
https://github.com/sonata-project/SonataUserBundle/blob/4.x/src/GoogleAuthenticator/Helper.php#L42

**Comment by davidromani** [comment]
Hello @core23 

I'm interested in to solve it if you are agree.

**Comment by greg0ire** [comment]
@davidromani knock yourself out!

The offending property is private, so in this case a simple refactor will do the trick:

https://github.com/sonata-project/SonataUserBundle/blob/782cdcd7b9e73270784ff00e34df85fa18c463d3/src/GoogleAuthenticator/Helper.php#L42

**Comment by davidromani** [comment]
Maybe `$trustedIpList` is more convenient, what do you think @greg0ire?

**Comment by greg0ire** [comment]
I agree, it's great!
