### ISSUE TITLE
Use Symfony\Component\Mailer\Mailer (mailgun, sendgrid etc.) as a mailer

### ISSUE THREAD

**Issue by judimator** [sonata-project/SonataUserBundle#1193]
## Feature Request

I use following packages: ` "symfony/mailer": "4.4.*",  "symfony/mailgun-mailer": "4.4.*"`
So `mailer` service in my container is instance of `Symfony\Component\Mailer\Mailer`. But `\Sonata\UserBundle\Mailer\Mailer` expects instance of Swift_Mailer. I suggest use at least both.

I'm looking forward any thoughts!

**Comment by VincentLanglet** [comment]
Do you want to work on this @judimator ?

**Comment by judimator** [comment]
Well, I hurried to future request. I set sonata_user.mailer to my own service and it helped. Thanks!

**Comment by greg0ire** [comment]
I think this should stay open though… having a dependency on `Swift_Mailer` is not good for Sonata…

**Comment by greg0ire** [comment]
Possible solution:

1. remove the type declaration;
2. trigger a deprecation if a swift mailer is passed;
3. throw an error if neither a swift mailer nor a Symfony\Component\Mailer\Mailer is passed;
4. call the right methods depending on the type;
5. once that is merged, drop `Swift_Mailer`
