### ISSUE TITLE
Validation does not work

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataUserBundle#1234]
Validation is not working for Default groups.

after change this line: https://github.com/sonata-project/SonataUserBundle/blob/b3b54effcd225194b48ff752e90e4c4567b31f64/src/Admin/Model/UserAdmin.php#L46

default Assert back to work.

change: 

```php
$options['validation_groups'] = (!$this->getSubject() || null === $this->getSubject()->getId()) ? ['Default', 'Registration'] : ['Default', 'Profile'];
```

**Comment by VincentLanglet** [comment]
Wanna make a PR @eerison ?

**Comment by eerison** [comment]
Hi @VincentLanglet yeah, I'll open a MR :)
