### ISSUE TITLE
User registration SonataUserBundle 4

### ISSUE THREAD

**Issue by Tadek888** [sonata-project/SonataUserBundle#1308]
How can I enable user registration SonataUserBundle 4 ?
In SonataUserBundle 3.X i found routes xml file to create user registration but in 4.X there is no registration file.

SonataUserBundle/src/Resources/config/routing/sonata_registration_1.xml

**Comment by VincentLanglet** [comment]
The SonataUserBundle does not provide any registration route anymore.

You should use the FosUser ones https://github.com/FriendsOfSymfony/FOSUserBundle/blob/cf7fe27b2f4e1f298ee6eadf537267f8c9f9b85c/Resources/config/routing/registration.xml
