### ISSUE TITLE
admin_app_sonatausergroup_create does not exist

### ISSUE THREAD

**Issue by divelopa** [sonata-project/SonataUserBundle#1338]
Apologies if this issue is not a bug, however, I tried going through the application and the web for same issues bot none of the solutions work. I've also posted on [Stackoverflow ](https://stackoverflow.com/questions/66564218/unable-to-generate-a-url-for-the-named-route-admin-app-sonatauseruser-create-a)but haven't got a response.

I renamed my User entity from SonataUserUser to User and since then, the application has not run since.

I get the error `An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_app_sonatausergroup_create" as such route does not exist.").`

I tried renaming it back but still get the same error. Is the entity's name 'cast in stone' and shouldn't be renamed?

**Comment by wbloszyk** [comment]
Route is generated by some pattern. After rename your class you MUST:
- update `Admin` service configuraion for this class
- clear cache (remove `var/cache` or use `bin/console cache:clear` in console)

**Comment by divelopa** [comment]
I assumed since I'm dev, cache would be cleared
