### ISSUE TITLE
Make reset password optional

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataUserBundle#1491]
## Feature Request

It would be nice to enable / disable reset password and avoid dependencies with mailer.

Extracted from: #1465

**Comment by Hanmac** [comment]
I'm currently brainstorming about this one, where i try to think of the possible constellations and how they should react:

* first it should check if there are resetting values, if not, then a big chunk doesn't need to be configured.
  * there doesn't need to be reset routes, and the link in template doesn't need to be there either
  * without resetting there doesn't need to be sonata user mailer, and also no symfony mailer
* then should it be possible to disable the resetting by disabling the `sonata_user.mailer` config?
* when having a custom mailer, then it doesn't need to complain about symfony mailer

any other should complain about missing services, right?

and if the resetting should work without admin bundle
