### ISSUE TITLE
Why forgot password option not inclueded in login functionality

### ISSUE THREAD

**Issue by Stefun** [sonata-project/SonataUserBundle#152]
I'm integrating SonataUserBundle with SonataAdminBundle which works fine. Login functionality also works fine. But i didn't find forgot password option in login. Why it it not included in Login. Any specific reasons?

**Comment by OskarStark** [comment]
no, i think it is implemented now, isn't it @Stefun ?

**Comment by stephen-tj** [comment]
Yes @OskarStark

**Comment by OskarStark** [comment]
it is, but not in the ```2.3``` stable!

@Soullivaneuh @sagikazarmark will it be available in ```2.4``` or ```3.0``` ?

**Comment by sagikazarmark** [comment]
I think it will be available in SonataUser 2.3 and SonataAdmin 2.4

But ask @Soullivaneuh about it, because I am already confused about versions.

**Comment by OskarStark** [comment]
thank you for your feedback @sagikazarmark 

I'm confused, too :smile:

**Comment by jordisala1991** [comment]
This is already implemented on 3.x
