### ISSUE TITLE
UserProvider: add way to disable (ByEmail) part

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataUserBundle#1525]
For one Project i need a way to have two or more users have the same email but different user names. i disabled the database unique field.

But i need to mess with the Sonata User Provider so make it usable to get the User by Email when provided for the Security Segment.
Sadly most of the classes are final, or the methods private, and i don't think i can use a Service Decorator there.

**Comment by VincentLanglet** [comment]
To me, this can be done with service decorator, by implementing your own UserProvider and ask Symfony to use it instead of the one provided by Sonata

cf: https://symfony.com/doc/current/service_container/service_decoration.html
```
# config/services.yaml
services:
    App\Mailer: ~

    # this replaces the old App\Mailer definition with the new one, the
    # old definition is lost
    App\Mailer:
        class: App\NewMailer
```

**Comment by Hanmac** [comment]
like i said, if i try to decorate the UserProvider, i can't get the sonata User Data because the methods i would need to overwrite are private.

but i think i found the solution, if i decorate the UserManager and make `findUserbyUsernameOrEmail` just call `findUserByUsername` regardless it should work.
