### ISSUE TITLE
The doctrine/collections requirement prevents installing on Symfony 6.2

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataUserBundle#1598]
The dependecy is locked at 1.x for `doctrine/collections`. This prevents installing this bundle with a fresh Symfony 6.2 install, unless you downgrade that library.

**Comment by VincentLanglet** [comment]
Feel free to add support for doctrine/collections 2

**Comment by gremo** [comment]
Sure I would, can you point me to the right direction? I don't think it's a great effort https://github.com/doctrine/collections/blob/2.1.x/UPGRADE.md

**Comment by VincentLanglet** [comment]
Changing this https://github.com/sonata-project/SonataUserBundle/blob/5.x/composer.json#L24
to `|| ^2.0` might be enough.

You can check if locally the v2 is installed.
If not, you can use `composer why-not doctrine/collections 2` to know why.
Maybe we'll have to add support for collections v2 to some others sonata bundle first.

**Comment by gremo** [comment]
Thank you!

Right now the only "problem" seems to be user-bundle itself (the root requirement is coming from the dowgrade I made in order to install user-bundle):

```txt
# composer why-not doctrine/collections 2
symfony/skeleton           dev-master requires doctrine/collections (^1.8) 
sonata-project/user-bundle 5.5.0      requires doctrine/collections (^1.6) 
```

Project is configured right now with SonataAdminBundle, SonataMediaBundle and SonataUserBundle.

**Comment by VincentLanglet** [comment]
Then the PR will be easy
