### ISSUE TITLE
`BaseUser.mongodb.xml` `boolean field `enabled` triggers a deprecation warning

### ISSUE THREAD

**Issue by landure** [sonata-project/SonataUserBundle#1613]
In SonataUserBundle 5.x, when using Doctrine MongoDB ODM, `BaseUser.mongodb.xml` field `enabled` use of `boolean` type triggers a deprecation warning:

```log
 Since doctrine/mongodb-odm 2.1: The "boolean" mapping type is deprecated. Use "bool" instead. 
```

**Comment by VincentLanglet** [comment]
Hi, @landure can you provide a PR ?
