### ISSUE TITLE
Invalid type for path "security.role_hierarchy.providers.sonata_user_bundle" - Error on fresh install. 

### ISSUE THREAD

**Issue by tgaertner** [sonata-project/SonataUserBundle#1622]
#### Sonata packages

<details><summary>show</summary>
<p>

sonata-project/block-bundle              4.20.0 4.20.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       2.2.0  2.2.0  Doctrine2 behavioral extensions
sonata-project/exporter                  3.1.1  3.1.1  Lightweight Exporter library
sonata-project/form-extensions           1.18.1 1.18.1 Symfony form extensions
sonata-project/twig-extensions           2.0.0  2.0.0  Sonata twig extensions

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

symfony/asset                      v5.4.21 v6.2.7  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v5.4.21 v6.2.7  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                    v5.4.22 v6.2.8  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.4.21 v6.2.7  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.4.21 v6.2.7  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/doctrine-messenger         v5.4.21 v6.2.7  Symfony Doctrine Messenger Bridge
symfony/dotenv                     v5.4.22 v6.2.8  Registers environment variables from a .env file
symfony/expression-language        v5.4.21 v6.2.7  Provides an engine that can compile and evaluate expressions
symfony/flex                       v2.2.5  v2.2.5  Composer plugin for Symfony
symfony/form                       v5.4.22 v6.2.8  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.22 v6.2.8  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.4.22 v6.2.8  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/intl                       v5.4.22 v6.2.8  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v5.4.22 v6.2.8  Helps sending emails
symfony/maker-bundle               v1.48.0 v1.48.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v5.4.21 v6.2.7  Allows manipulating MIME messages
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/notifier                   v5.4.22 v6.2.8  Sends notifications via one or more channels (email, SMS, ...)
symfony/phpunit-bridge             v6.2.7  v6.2.7  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/process                    v5.4.22 v6.2.8  Executes commands in sub-processes
symfony/property-access            v5.4.22 v6.2.8  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.4.22 v6.2.8  Extracts information about PHP class' properties using metadata of popular sources
symfony/runtime                    v5.4.22 v6.2.8  Enables decoupling PHP applications from global state
symfony/security-bundle            v5.4.22 v6.2.8  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/serializer                 v5.4.22 v6.2.8  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/stopwatch                  v5.4.21 v6.2.7  Provides a way to profile code
symfony/string                     v5.4.22 v6.2.8  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.4.22 v6.2.8  Provides tools to internationalize your application
symfony/twig-bundle                v5.4.21 v6.2.7  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.4.22 v6.2.8  Provides tools to validate values
symfony/web-link                   v5.4.21 v6.2.7  Manages links between resources
symfony/web-profiler-bundle        v5.4.21 v6.2.7  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v5.4.21 v6.2.7  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/amqp-messenger             v5.4.22 v5.4.22 Symfony AMQP extension Messenger Bridge
symfony/cache                      v5.4.22 v6.2.8  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v2.5.2  v3.2.1  Generic abstractions related to caching
symfony/config                     v5.4.21 v6.2.7  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/dependency-injection       v5.4.22 v6.2.8  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.2.1  v3.2.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.22 v6.2.8  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v5.4.22 v6.2.8  Eases DOM navigation for HTML and XML documents
symfony/error-handler              v5.4.21 v6.2.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.22 v6.2.8  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.2.1  v3.2.1  Generic abstractions related to dispatching event
symfony/filesystem                 v5.4.21 v6.2.7  Provides basic utilities for the filesystem
symfony/finder                     v5.4.21 v6.2.7  Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts      v2.5.2  v3.2.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.22 v6.2.8  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.22 v6.2.8  Provides a structured process for converting a Request into a Response
symfony/messenger                  v5.4.22 v6.2.8  Helps applications send and receive messages to/from other applications or via message queues
symfony/monolog-bridge             v5.4.22 v6.2.8  Provides integration for Monolog with various Symfony components
symfony/options-resolver           v5.4.21 v6.2.7  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.21 v6.2.7  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.27.0 v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.27.0 v1.27.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.27.0 v1.27.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.27.0 v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.27.0 v1.27.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.27.0 v1.27.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.27.0 v1.27.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.27.0 v1.27.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/redis-messenger            v5.4.22 v6.2.8  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.4.22 v6.2.8  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-core              v5.4.22 v6.2.8  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.21 v6.2.7  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.22 v5.4.22 Symfony Security Component - Guard
symfony/security-http              v5.4.22 v6.2.8  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.5.2  v3.2.1  Generic abstractions related to writing services
symfony/translation-contracts      v2.5.2  v3.2.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.22 v6.2.8  Provides integration for Twig with various Symfony components
symfony/var-dumper                 v5.4.22 v6.2.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.2.8  v6.2.8  Allows exporting any serializable PHP data structure to plain PHP code

</p>
</details>

#### PHP version

PHP 8.1.16 

## Subject

Error on fresh install following the instuctions from the docs https://docs.sonata-project.org/projects/SonataUserBundle/en/5.x/reference/installation/ using Symfony 5.

## Actual results

Error:
Invalid type for path "security.role_hierarchy.providers.sonata_user_bundle". Expected "scalar", but got "array".

Releated Config: 

security:
        providers:
            sonata_user_bundle:
                id: sonata.user.security.user_provider

**Comment by VincentLanglet** [comment]
Hi, thanks for the report

Do you know if it's a 
- doc issue
- default value issue
- flex recipe issue
?

Can you provide a PR.

**Comment by jordisala1991** [comment]
I think your configuration is not correct, please check those if you need another example (the doc one is correct too):

https://github.com/sonata-project/SonataUserBundle/blob/5.x/tests/App/config/config.yaml
https://github.com/sonata-project/SonataUserBundle/blob/5.x/tests/App/config/config_sf5.yaml
