### ISSUE TITLE
Role checkboxes are disabled when creating/editing a user

### ISSUE THREAD

**Issue by gravitiq-cm** [sonata-project/SonataUserBundle#1630]
When I edit/create a new user, the custom roles defined in `security.yaml` have disabled checkboxes. What would cause this?

ROLE_OPERATIONS is disabled in the list:
![image](https://user-images.githubusercontent.com/107187716/232793894-1f8dd04b-13ff-4f61-9601-a623f5d95338.png)

It's configuration in `security.yaml` is very basic... do I need to add something else to make it selectable?
![image](https://user-images.githubusercontent.com/107187716/232794083-9e7112ca-c878-4dde-8647-4a5198064788.png)

In `roles_matrix_list.html.twig` the code looks like this:
```
{% for role, attributes in roles|sort %}
{% if attributes.form is defined %}
    <li>{{ form_widget(attributes.form, {label: attributes.role_translated, value: attributes.role}) }}</li>
    {% if not attributes.is_granted %}
        <script>
            $('input[value="{{ role }}"]').iCheck('disable');
            $('form').on('submit', function() {
                $('input[value="{{ role }}"]').iCheck('enable');
            });
        </script>
    {% endif %}
{% endif %}
{% endfor %}
```

What is that JS trying to do? I'm logged in as SUPER_ADMIN, so don't understand why any of the roles would flag as "not attributes.is_granted" I can hack the HTML to enable the checkbox as a workaround, but would prefer to fix the root cause!

**Comment by Steedy** [comment]
I also had the same issue, for those that find this topic a suggested workaround is to amend the JS used to disable the checkbox.

Overwrite the twig file `roles_matrix_list.html.twig` in your project by recreating the file in `path/to/project/templates/bundles/SonataUserBundle/Form/roles_matrix_list.html.twig` and make the changes to the JS or comment out

**Comment by gravitiq-cm** [comment]
Sorry - I should have added a note with the workaround here instead of just messaging on Slack :-)

**Comment by Nexotap** [comment]
Just encountered the same problem.
Maybe we can reopen this?
