### ISSUE TITLE
Deprecation: UserListener needs to be done as listener instead of subscriber

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataUserBundle#1650]
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
sonata-project/user-bundle 5.9.0
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
symfony/doctrine-bridge v6.3.0
```

</p>
</details>

#### PHP version

```
$ php -v
# Put the result here.
PHP 8.2.6
```

## Steps to reproduce

Open a Page in Backend and use Profiler to see Deprecations

## Expected results

No Deprecations

## Actual results

> 'symfony/doctrine-bridge', '6.3', 'Using Doctrine subscribers as services is deprecated, declare listeners instead'

Because of https://github.com/symfony/symfony/pull/49918 and https://github.com/doctrine/DoctrineBundle/pull/1664,
`doctrine.event_subscriber` is deprecated and should use listener instead

Should that be done as https://symfony.com/doc/current/doctrine/events.html#doctrine-entity-listeners directly instead of listening to all entities? technically it should not look for `Sonata\UserBundle\Model\UserInterface` but for `sonata.user.user.class` ?

for a possible MR, should i still use the php config, or should i use [#[AsEntityListener]](https://github.com/doctrine/DoctrineBundle/blob/2.8.x/Attribute/AsEntityListener.php) ?

**Comment by jordisala1991** [comment]
I think we should fix this the same as we did for doctrine extensions: https://github.com/sonata-project/sonata-doctrine-extensions/pull/487

Do you want to do the PR?

**Comment by Hanmac** [comment]
@jordisala1991 yeah i can, i think

i was just looking if i could use an `entity-listener` instead of a full one (so it only needs to listen to one class anyway? not just the UserInterface?)
but it seems that such option doesn't exist for `doctrine_mongodb.odm.event_listener` and the ODM stuff, so it seems i still need to use the full listener for both
