### ISSUE TITLE
Allow disabling sonata.user.group service

### ISSUE THREAD

**Issue by waiting-for-dev** [sonata-project/SonataUserBundle#168]
I've been trying to remove `sonata.user.group` service using following CompilerPass:

    <?php
    
    namespace NS\Service\CompilerPass;
    
    use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
    use Symfony\Component\DependencyInjection\ContainerBuilder;
    
    class CompilerPass implements CompilerPassInterface
    {
        public function process(ContainerBuilder $container)
        {
           $container->removeDefinition('sonata.user.admin.group');
        }
    }

But the service is not optional and it is required somewhere else (I can't say exactly where). I think in `FOSUserBundle` disallowing groups is as easy as do not tell anything about its class in `config.yml`, but as far as I know it is mandatory in SonataUserBundle.

**Comment by core23** [comment]
Continued in #517
