### ISSUE TITLE
How to override admin_orm.xml ?

### ISSUE THREAD

**Issue by ghost** [sonata-project/SonataUserBundle#214]
Hello,

I was able to override admin.orm.xml in app/Resources/SonataUserBundle/config/admin_orm.xml to add services calls or override templating but it's not working anymore.

Do you have any advice ?

Thanks

**Comment by francescomalatesta** [comment]
Same issue here, anyone managed to solve it?

**Comment by jordisala1991** [comment]
Is this still an issue?
