### ISSUE TITLE
Cannot switch user

### ISSUE THREAD

**Issue by Deamon** [sonata-project/SonataUserBundle#243]
Hello everyone,
I'm working with sf 2.3 and since the beginning of my project I use FosUserBundle.

Recently, I discovered SonataAdmin and decided to use it in combination with FOSUB.

to manage Users in SonataAdmin, The dependancy SonataUserBundle has to be installed so I installed it.

But now that everything is configured to work with Sonata Admin and user Bundle + FOSUB, I cannot switch user any more.

I looke in an other issue with the same problem but my usernameCanonical is correct.

The issue is : 
`Switch User failed: "Username "myusername" does not exist."`

Because everything works well before installing SonataUserBundle I assume it is due to this bundle.

Does anyone as a tip to make this work again?

Thank you!

**Comment by sadortun** [comment]
@Deamon did you make it work ?
