### ISSUE TITLE
Bundle overriding custom login.html.twig

### ISSUE THREAD

**Issue by jameshalsall** [sonata-project/SonataUserBundle#272]
After updating to 9070416b87c54fecf1375e2630820b4c9c7a54e3 my custom login.html.twig is being overridden with the `SonataUserBundle` one.

My template resides at `Vendor/UserBundle/Resources/views/Security/login.html.twig`, the same path as the one that was added in commit 56024376c2d1850aa2aa3abe4fb128f8bf16dd38.

What is the reason for adding this template?

**Comment by zjsxwc** [comment]
I have the same problem,

to solve the problem i rewrited the sonata admin user login url's controller in file `app/config/routing.yml`

```
sonata_user_admin_security_login:
    path:   /admin/login
    defaults: { _controller: ApplicationSonataUserBundle:AdminSecurity:login }
```

**Comment by jonhleno** [comment]
> I have the same problem,
> 
> to solve the problem i rewrited the sonata admin user login url's controller in file `app/config/routing.yml`
> 
> ```
> sonata_user_admin_security_login:
>     path:   /admin/login
>     defaults: { _controller: ApplicationSonataUserBundle:AdminSecurity:login }
> ```

It was truly helpful... thanks!
