### ISSUE TITLE
Please, tell me how to composer with FOSUserBundle "~2.0@dev"

### ISSUE THREAD

**Issue by denteca** [sonata-project/SonataUserBundle#348]
In according to http://sonata-project.org/bundles/user/master/doc/reference/installation.html

i'm installing "sonata-project/user-bundle" with composer in "dev-master". Is it correct?

I have FOSUserBundle in "~2.0@dev" in my composer.json and with "composer update" i get an error: 

Installation request for sonata-project/user-bundle dev-master -> satisfiable by sonata-project/user-bundle[dev-master].
sonata-project/user-bundle dev-master requires sonata-project/doctrine-extensions ~1.0 -> no matching package found.

**Comment by damien-thiesson** [comment]
+1 on this one. Still not compatible with FosUserBundle 2 15 months later.

**Comment by max-kovpak** [comment]
+1

**Comment by redactuk** [comment]
+1

**Comment by michaelKaefer** [comment]
The solution is here: https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by max-kovpak** [comment]
No, the solution it is make it compatible with fosuserbundle.

**Comment by Soullivaneuh** [comment]
See: https://github.com/sonata-project/SonataUserBundle/pull/745
And: https://github.com/sonata-project/SonataUserBundle/issues/322

Please note that FOSUser v2 *is not stable yet** so we try to make it compatible **with best effort**.

This is not possible on stable branch of sonata-user right now. If you want stable, use stable of FOSUser too (v1).
