### ISSUE TITLE
Redirecting to Referrer when registering

### ISSUE THREAD

**Issue by arosslau** [sonata-project/SonataUserBundle#397]
Hey,

I just found out that every user is getting redirected after filling the reg-form to the referrer. That prevents e.g. the "check-email" page when email-confirmation is enabled.

Bug or Feature?

I can't guess any reason for having this as a feature.

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
