### ISSUE TITLE
Problem when adding a user trough the API

### ISSUE THREAD

**Issue by grosenbaum** [sonata-project/SonataUserBundle#410]
Steps to reproduce:
- Using a fresh install of the sandbox
- Connected as admin / admin in /api/doc
- Trying to POST a user without any params rises a 500 Internal Server Error

My related nginx logs:

> 2014/05/16 16:02:34 [error] 2431#0: *930 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to FOS\UserBundle\Model\User::setExpiresAt() must be an instance of DateTime, null given, called in /var/www/sandbox/sonata-en/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 347 and defined in /var/www/sandbox/sonata-en/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Model/User.php on line 454" while reading response header from upstream, client: 127.0.0.1, server: sonata-en-sandbox.vm, request: "POST /app.php/api/user/users.json HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "sonata-en-sandbox.vm", referrer: "http://sonata-en-sandbox.vm/app.php/api/doc/"

**Comment by webdevilopers** [comment]
Possibly related:
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1958
- https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1956

Looks like the fields are deprecated for FOSUser **2** anyway.

**Comment by OskarStark** [comment]
Closed via #869
