### ISSUE TITLE
On login page, register form gets embedded in base layout (resulting in two nested base layout)

### ISSUE THREAD

**Issue by zedrdave** [sonata-project/SonataUserBundle#412]
While trying to figure why my login page would have two nested base layouts, I narrowed it down to `SonataUserBundle / Resources / views / Security / base_login.html.twig`, which calls:

```
{% render controller("SonataUserBundle:RegistrationFOSUser1:register") %}
```

But then the controller renders the form by calling:

```
        return $this->container->get('templating')->renderResponse('FOSUserBundle:Registration:register.html.'.$this->getEngine(), array(
            'form' => $form->createView(),
        ));
```

which uses `{% extends "FOSUserBundle::layout.html.twig" %}`...

... resulting in nested base layouts...

Am I missing something or is there a bug somewhere?

**Comment by yanict** [comment]
that will break if you don't fill the register form properly.
try using 2 different passwords, only the register.html.twig willl be loaded and that will make the layout disappear.
i'm still looking for a solution, if anyone has a good one ?

thanks

**Comment by kaayru** [comment]
I was struggling with the same issue. To fix it, I did override the problematic template with the following one:

```
app/Resources/FOSUserBundle/views/Registration/register.html.twig
```

With the same content as in the original one, without extending any layout:

```twig
{% block fos_user_content %}
{% include "FOSUserBundle:Registration:register_content.html.twig" %}
{% endblock fos_user_content %}
```

Did the trick for me!

**Comment by jontorrado** [comment]
That's not the solution because if you do not modify the /register controller or layout, that page will result in a no-layout registration form. Another solution is to modify the controller being executed for your own:
```
{% block sonata_user_registration %}
    {% render controller("SonataUserBundle:RegistrationFOSUser1:register") %}
{% endblock %}
```
Then just render the same template as `register.html.twig` but without the extends.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
