### ISSUE TITLE
Can't add user to group

### ISSUE THREAD

**Issue by lucasgranberg** [sonata-project/SonataUserBundle#418]
I can't add an user to a group if the user doesn't have the role ROLE_SUPER_ADMIN. This doesn't seem right to me. Why is this restricted. If I (as a superadmin) wan't to add somebody to a group it shouldn't have anything to do with that users role. Instead the system should check my role and add fields based on that.

Is there some reason for this that I am missing?

```php

    protected function configureFormFields(FormMapper $formMapper)
    {
        // define group zoning
        $formMapper
    ...
        if ($this->getSubject() && !$this->getSubject()->hasRole('ROLE_SUPER_ADMIN')) {
            $formMapper
                ->with('Management')
                    ->add('groups', 'sonata_type_model', array(
                        'required' => false,
                        'expanded' => true,
                        'multiple' => true
                    ))
    ...
                ->end()
            ;
        }
    ...
    }
```

https://github.com/sonata-project/SonataUserBundle/blob/master/Admin/Model/UserAdmin.php#L181

**Comment by AienTech** [comment]
I'm using `dev-master` an still having this issue on `UserAdmin:191`

**Comment by lucasgranberg** [comment]
I think the code is there just to prevent plebs from editing super admin accounts. You can override the whole admin file and extend upon the old one.
http://stackoverflow.com/questions/11413240/overriding-the-user-admin-form

**Comment by greg0ire** [comment]
I wonder if this was not removed in a very recent PR

**Comment by greg0ire** [comment]
See #717

**Comment by lucasgranberg** [comment]
Ok, Ill close this issue as https://github.com/sonata-project/SonataUserBundle/pull/717 will fix it (if it gets pulled).
