### ISSUE TITLE
problem with create duplicate username

### ISSUE THREAD

**Issue by hoannv** [sonata-project/SonataUserBundle#426]
I'm using symfony2.5.\* and fosuser 1.3.*. I get a problem with create new user in sonataadmin. It's not validating user with duplicate username.

I see a new commit in fosuser1.3.\* Update ValidationPass to work with Symfony 2.5+ https://github.com/FriendsOfSymfony/FOSUserBundle/commit/78cdbda2f56629048e65d03de0be930f5715d14d

I'm not sure it's the reason why validation is not work.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
