### ISSUE TITLE
Invalid composer.json link to "sonata-project/datagrid-bundle": "~2.2@dev",

### ISSUE THREAD

**Issue by lu4e3ar** [sonata-project/SonataUserBundle#430]
During composer install :
"sonata-project/user-bundle dev-master requires sonata-project/datagrid-bundle ~2.2@dev -> no matching package found"

There are no branch/tag 2.2 in sonata-project/datagrid-bundle https://github.com/sonata-project/SonataDatagridBundle/branches

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
