### ISSUE TITLE
 Registration redirection bug

### ISSUE THREAD

**Issue by aarubui** [sonata-project/SonataUserBundle#444]
BUG:
Since a250abdb45f4e7a9d5d122826df03c6b1a76599f, the user is redirected to the referer upon successful registration (confirmation disabled). When there is no referer, a "Cannot redirect to an empty URL." error is returned.

**Comment by azzouz** [comment]
Hi everybody,
To overcome this bug, downgrade your SonataUserBundle to "2.2.4" version or override the RegistrationFOSUser1 Controller in your latest version "2.3.x-dev" with this code [RegistrationFOSUser1Controller](https://github.com/sonata-project/SonataUserBundle/blob/2.2/Controller/RegistrationFOSUser1Controller.php)

**Comment by OskarStark** [comment]
Closed via #869
