### ISSUE TITLE
SonataUserBundle FOSUserBundle UniqueEntity email & username

### ISSUE THREAD

**Issue by Lavinia-Dan** [sonata-project/SonataUserBundle#448]
I have my own User Class, wich inherits Sonata's BaseUser <code>(Sonata\UserBundle\Entity\BaseUser).</code>

My problem: If I try to create a user from sonata admin using an existing email, I get the following exception:
<code>
"Failed to create object: Application\Sonata\UserBundle\Entity\User" SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint DETAIL: Key (email_canonical)=(test@test.com) already exists.
</code>

I tried to use as suggested in some documentations & tickets UniqueEntity using the proper use statements, but to no avail.

I use the UniqueEntity annotation on other entities with sonata admin without a problem, and I'm getting a nice message inside the form which notifies the user that there is already an entity with that name/title instead of the exception. But for the User entity it simply does not work the same way.

This is how I registered sonata user bundle in AppKernel:
<code>
new Application\Sonata\UserBundle\ApplicationSonataUserBundle('FOSUserBundle') 
extending FOSUserBundle
</code>

use statements in custom User entity: (generated by EasyExtends bundle, just that I've added some custom columns & one to many relations with other entities like ex: Project):

<code>
namespace Application\Sonata\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
</code>

and this is the annotation for the user class

<code>

    * @ORM\Table(name="fos_users")

    * @ORM\Entity

    * @UniqueEntity("username")

    * @UniqueEntity("username_canonical")

    * @UniqueEntity("email")

    * @UniqueEntity("email_canonical")

</code>

this is my config for sonata_user:
<code>
    sonata_user:

        security_acl: true

        manager_type: orm

        class:

            user:  Application\Sonata\UserBundle\Entity\User

            group: Application\Sonata\UserBundle\Entity\Group
</code>

this is the config for fos_user:

<code>
fos_user:

    db_driver:     orm

    firewall_name: admin, user

    user_class:    Application\Sonata\UserBundle\Entity\User

    group:

        group_class:   Application\Sonata\UserBundle\Entity\Group

        group_manager: sonata.user.orm.group_manager

    service:

        user_manager: sonata.user.orm.user_manager
</code>

I'm using a custom admin class

<code>
parameters:

    #use custom user admin class

    sonata.user.admin.user.class:

        Application\Sonata\UserBundle\Admin\Model\UserAdmin
</code>

(I've also tried with the default admin class)

this is my sonata admin configuration:
<code>
sonata_admin:

    security: 

        handler: sonata.admin.security.handler.acl 

    title: My App 

    templates: 

        layout: CoreBundle:Admin:standard_layout.html.twig
</code>

I have also tried to override validation.yml/validation.xml file with my own validation rules ... and I still get the exception ... 

I am out of ideas. I would be very grateful if you could help me.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
