### ISSUE TITLE
Various nesting problems when overriding FOSUserBundle resp. SonataUserBundle resp. ApplicationSonataUserBundle layout template

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataUserBundle#449]
I'm trying to embed the templates of ‪FOSUserBundle‬ + ‪SonataUserBundle‬ in my base layout.

My custom template is stored at `app/Resources/SonataUserBundle/views/layout.html.twig` and simply looks like this the official docs example with my base layout extended:
```twig
{% extends '::base.html.twig' %}

{% block content %}
{% block fos_user_content %}{% endblock %}
{% endblock %}
```

When I call the `login` route the `register` template is included too. I think this currently was an improvement by `SonataUserBundle` but also a BC break:
https://github.com/sonata-project/SonataUserBundle/blob/master/CHANGELOG.txt#L4-7

But for some reason my base layout is now included twice(!).

Related issue: https://github.com/sonata-project/SonataUserBundle/issues/412

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
