### ISSUE TITLE
SonataUserBundle work with FOSUserBundle 2.x

### ISSUE THREAD

**Issue by graille** [sonata-project/SonataUserBundle#451]
Hi !

I have implemented FOSUserBundle 2.x and I have SonataAdminBundle.
I would like to implement SonataUserBundle, but I don't know if SUB works with FOSUB 2 :s

Con you help me ? :)

**Comment by roelveldhuizen** [comment]
Are there any working implementations of FOSUserBundle 2.x ? with SonataUserBundle?

**Comment by redactuk** [comment]
Any news on this? As a new Symfony/Sonata user I find this lack of compatibility baffling. I've been struggling with this for over a week now and can't belive that after a year still nothing has been done to address this.

**Comment by fkrauthan** [comment]
Is this project dead? Symfony 3 only works with FOSUserBundle 2.x but this plugin only supports FOSUserBundle 1.3? This is gonna be deal breaker for Sonata Admin as soon as they release the next version with Symfony 3.0 support.

**Comment by rande** [comment]
There is a work in progress here: https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2

Feel free to add PR to help completing the work.

Also this issue is duplicated others related issues.
