### ISSUE TITLE
Attempted to call method "setCurrentUri" on class "Knp\Menu\MenuItem" in sonata-project/user-bundle/Block/ProfileMenuBlockService.php line 91

### ISSUE THREAD

**Issue by Beagon** [sonata-project/SonataUserBundle#456]
I've just configured and installed Sonata's User bundle but when I want to go to the profile page I get this error:

`Attempted to call method "setCurrentUri" on class "Knp\Menu\MenuItem" in /home/robin/public_html/symfony2/vendor/sonata-project/user-bundle/Block/ProfileMenuBlockService.php line 91. Did you mean to call: "setCurrent"?`

This is what is in my composer.json (if that happens to help)

---

```
"require": {
    "php" : ">=5.3.3",
    "symfony/symfony" : "2.5.1",
    "doctrine/orm" : "2.4.*",
    "doctrine/doctrine-bundle" : "1.2.*",
    "doctrine/doctrine-fixtures-bundle" : "2.2.*",
    "twig/extensions" : "~1.1",
    "symfony/assetic-bundle" : "~2.3",
    "symfony/swiftmailer-bundle" : "~2.3",
    "symfony/monolog-bundle" : "~2.6",
    "sensio/distribution-bundle": "3.0.*",
    "sensio/framework-extra-bundle": "~3.0",
    "incenteev/composer-parameter-handler": "~2.1",
    "sonata-project/admin-bundle" : "dev-master",
    "sonata-project/doctrine-orm-admin-bundle" : "dev-master",
    "sonata-project/easy-extends-bundle" : "dev-master",
    "sonata-project/user-bundle" : "dev-master",
    "sonata-project/datagrid-bundle" : "dev-master",
    "sonata-project/jquery-bundle" : "dev-master",
    "knplabs/knp-menu": "2.0.*",
    "knplabs/knp-menu-bundle": "2.0.*"
},
```

---

Thanks in advance for the help and these bundles are great!

**Comment by roman-1983** [comment]
This issue is related to https://github.com/sonata-project/sandbox/issues/484

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
