### ISSUE TITLE
User within PHPCR / Symfony CMF integration

### ISSUE THREAD

**Issue by petforsberg** [sonata-project/SonataUserBundle#457]
Would it be a problem to add some Symfony CMF (PHPCR-ODM based app) integration into Sonata Admin with use of SonataUserBundle? For the moment, I saw (and have) working Sonata Admin with Symfony CMF, but it's not really useful in a serious website without some user integration.

**Comment by core23** [comment]
There is a separate bundle for this https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle
