### ISSUE TITLE
Unable to remove user roles, if role has hierarchy

### ISSUE THREAD

**Issue by LukasLt** [sonata-project/SonataUserBundle#461]
We were unable to remve assigned user roles, like `ROLE_BUYER: ROLE_USER`, using Sonata Admin bundle.

We nailed down to `Sonata\UserBundle\Form\Transformer\RestoreRolesTransformer::reverseTransform() (65)`

       list($availableRoles, ) = $this->rolesBuilder->getRoles();
       $hiddenRoles = array_diff($this->originalRoles, $availableRoles);

The problem is that `$this->originalRoles` user 'keys', while `$availableRoles` - 'values'. 

     var_dump($this->originalRoles);
     #     array(2) {
     #       [0]=>
     #         string(10) "ROLE_BUYER"
     #         <...>
     #     }

     var_dump($availableRoles);
     #     array(12) {
     #       [ROLE_BUYER]=>
     #         string(10) "ROLE_BUYER: ROLE_USER"
     #         <...>
     #    }

Fix was add array_keys as such

     $hiddenRoles = array_diff($this->originalRoles, array_keys($availableRoles));

otherwise, `ROLE_BUYER` was allways readded as hidden role again :/

**Comment by pamuche** [comment]
+1 for merging the solution from @LukasLt (https://github.com/sonata-project/SonataUserBundle/issues/461#issue-40799219) into master.

**Comment by pamuche** [comment]
Ok, found thats allready fixed & merged in master:
https://github.com/sonata-project/SonataUserBundle/pull/522/

**Comment by Soullivaneuh** [comment]
Thanks for the tip @pamuche
