### ISSUE TITLE
Missing PageableManagerInterface::getPager implementation

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataUserBundle#463]
This happens only when using the production environment : 

> Class Sonata\UserBundle\Document\UserManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Sonata\CoreBundle\Model\PageableManagerInterface::getPager) in /home/users/gparis/workspace/cine/db/vendor/sonata-project/user-bundle/Document/UserManager.php on line 33

**Comment by core23** [comment]
Can you provide a PR for this @greg0ire ?

**Comment by greg0ire** [comment]
It looks like it has been "Implemented" in the meantime : 

```
    /**
     * @param array $criteria
     * @param int   $page
     * @param int   $limit
     * @param array $sort
     *
     * @return PagerInterface
     */
    public function getPager(array $criteria, $page, $limit = 10, array $sort = array())
    {
        new \RuntimeException('method not implemented');
    }
```
