### ISSUE TITLE
composer install hangs

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataUserBundle#464]
I'm trying to run `composer install`, in order to fix bugs in the bundle, and Composer is having a hard time figuring out what to install (I think I'm hitting [this bug](https://github.com/composer/composer/issues/1959)). Tested and reproduced on 3 different machines, I even waited for 20 minutes, without any result.

Here is how you can test

    cd /tmp && git clone https://github.com/sonata-project/SonataUserBundle.git && cd SonataUserBundle && ci -vvv

**Comment by core23** [comment]
Think we should close this ;)
