### ISSUE TITLE
Adding customised validation rules to SonataUserBundle

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataUserBundle#466]
How do we add new custom validation rules when using SonataUserBundle?

I want to add rules to the UserAdmin form used in by SonataAdmin, but I just can't seem to get them picked up...

I've posted the issue in full on Stack:
http://stackoverflow.com/questions/25609526/adding-customised-validation-rules-to-sonatauserbundle

If I've missed something then this is a documentation issue (which I'll try to help with, as ever, once the solution is explained). On the other hand, if this is just not possible then it's definitely a feature issue!

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
