### ISSUE TITLE
Can't create user with default UserAdmin without checking  Locked, Expired, Enabled and Credentials Expired

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataUserBundle#472]
The MySQL database columns for `locked`, `expired`, `enabled` and `credentials_expired` are described as `tinyint(1) NOT NULL`.

When submitting the UserAdmin form the User is not created until I checked all of the boxes which will set `1` as values.
There doesn't seem to be a way to make it automatically set `0`.

Is this a problem - maybe in addition with the `SonataAdminBundle` or `FOSUserBundle`?

Possibly related to issue https://github.com/sonata-project/SonataUserBundle/issues/410.

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
