### ISSUE TITLE
Versioning issue.

### ISSUE THREAD

**Issue by hardikvi** [sonata-project/SonataUserBundle#476]
There is installation conflict with "sonata-project/user-bundle".

The latest version of  "sonata-project/user-bundle" is requring "friendsofsymfony/user-bundle: ~1.3" now it restricts me to use "Events" of FOSUserBundle. 

So is there anyway i can use latest FOSUserBundle features with "sonata-project/user-bundle" ?

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataUserBundle/issues/322
