### ISSUE TITLE
undefined method Knp\Menu\MenuItem::setCurrentUri() when trying to get to profile route

### ISSUE THREAD

**Issue by claireve** [sonata-project/SonataUserBundle#483]
I have installed Sonata Admin and Sonata User. I have this error when I try to get to the route /profile (sonata_user_profile_show). 

FatalErrorException: Error: Call to undefined method Knp\Menu\MenuItem::setCurrentUri() in /Users/me/Sites/mysite/vendor/sonata-project/user-bundle/Block/ProfileMenuBlockService.php line 91

Here is my composer.json

{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3._",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2._",
        "twig/extensions": "1.0._",
        "symfony/assetic-bundle": "2.3._",
        "symfony/swiftmailer-bundle": "2.3._",
        "symfony/monolog-bundle": "2.3._",
        "sensio/distribution-bundle": "2.3._",
        "sensio/framework-extra-bundle": "2.3._",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "stof/doctrine-extensions-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "1.3.3",
        "sonata-project/core-bundle": "~2.2@dev",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/jquery-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/user-bundle": "~2.2",
        "jms/security-extra-bundle": "dev-master"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\ParameterHandler\ScriptHandler::buildParameters",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\ParameterHandler\ScriptHandler::buildParameters",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets",
            "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "stable",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.3-dev"
        }
    }
}

Thanks for the help.

**Comment by Schyzophrenic** [comment]
I encounter the same error

**Comment by gabrielalmeida** [comment]
:+1:

**Comment by soipo** [comment]
Same error, it seems that the dev branch requires:

"knplabs/knp-menu-bundle": ">=2.0,<3.0.0",
"knplabs/knp-menu": ">=2.0,<3.0"

instead of using the 1.1.*,

**Comment by stephanvierkant** [comment]
#456

**Comment by jordisala1991** [comment]
Duplicated of #456 . Closing
