### ISSUE TITLE
Fatal error: Class 'ResourceBundle' not found 

### ISSUE THREAD

**Issue by yosandry1** [sonata-project/SonataUserBundle#494]
When a new user attempts incert the web and not the console gives me the error, but the groups did not
Fatal error: Class 'ResourceBundle' not found in E:\xampp\htdocs\Symfony_standar\vendor\symfony\symfony\src\Symfony\Component\Intl\ResourceBundle\Reader\BinaryBundleReader.php on line 32
excuse me for my English

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
