### ISSUE TITLE
Can't remove roles from user

### ISSUE THREAD

**Issue by asmisha** [sonata-project/SonataUserBundle#497]
Sonata User Bundle v2.2

I'm not able to remove roles from user on user admin page, until I change 
`$hiddenRoles = array_diff($this->originalRoles, $availableRoles);`
to
`$hiddenRoles = array_diff($this->originalRoles, array_keys($availableRoles));`

in Form/Transformer/RestoreRolesTransformer.php:67

The point is EditableRolesBuilder returns roles as array name => formattedName, but originalRoles has names, not formatted names. So array_diff here always returns originalRoles.

**Comment by pamuche** [comment]
fixed & merged in master: #522
