### ISSUE TITLE
Hidden roles are not kept after edit

### ISSUE THREAD

**Issue by edorfaus** [sonata-project/SonataUserBundle#499]
If a user can edit some of the roles of a group, but not all of them, then the ones the user does not have access to are hidden (not shown in the role list). If one of those hidden roles were originally selected for that group, after this user clicks update, that role will be removed from the group. Since it was never shown to the user, it should instead be kept selected.

This problem was introduced by PR #452 - which causes SecurityRolesType to set the transformer's list of original roles to the list of roles that were selected by the user instead of setting it to the list of roles that the group had originally.

Therefore, I think that change should be reverted, and the problem it worked around (issue #423) should be fixed in a different way - I would suggest using the array_keys solution mentioned in issues #497, #461 and #469, and implemented in pull requests #471 and #470 by @vstrizhenok (which also include a test).

**Comment by mkurzeja** [comment]
@Bladrak Any change to fix this issue? Please let me know if preparing a single PR that reverts changes from #452 and includes #470 would help. I could submit it with some additional tests.

**Comment by Bladrak** [comment]
@mkurzeja no change on my side, but feel free to submit the PR. @rande may check this out
