### ISSUE TITLE
Remove section social from user block giving error

### ISSUE THREAD

**Issue by meron1122** [sonata-project/SonataUserBundle#503]
Model:
```php
<?php
 
namespace Application\Sonata\UserBundle\Admin;
 
use Sonata\UserBundle\Admin\Model\UserAdmin as SonataUserAdmin;
use Sonata\AdminBundle\Form\FormMapper;
 
class UserAdmin extends SonataUserAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        parent::configureFormFields($formMapper);
        $formMapper
            ->remove('facebookUid')
            ->remove('facebookName')
            ->remove('twitterUid')
            ->remove('gplusUid')
            ->remove('gplusName')
            ->remove('twitterName');
 
    }
}

```
Error:
>Key "User.Social" for array with keys "User.Profile, User.General, Security.Status, Security.Groups, Security.Keys, Security.Roles" does not exist in SonataAdminBundle:CRUD:base_edit_form_macro.html.twig at line 4 

So, how to remove/hide social section in user block?
This is realy not nessesary in most application, including mine.

**Comment by kaiwa** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
:+1: 

Social data should be optional too IMO.

**Comment by OskarStark** [comment]
but is this error message really related to this what you are doing @meron1122 ??

**Comment by saifrehman15** [comment]
Sorry for late replay. This is worked for me . Following is my  admin file. 

<?php
namespace Application\Sonata\UserBundle\Admin;
use Sonata\UserBundle\Admin\Model\UserAdmin as SonataUserAdmin;
use Sonata\AdminBundle\Form\FormMapper;

class UserAdmin extends SonataUserAdmin
{
    // @see https://groups.google.com/forum/#!topic/sonata-users/lLZyA4VBKOY
    protected $formOptions = array(
        'validation_groups' => 'default'
    );
    protected function configureFormFields(FormMapper $formMapper)
    {
        parent::configureFormFields($formMapper);
//        $formMapper->remove('facebookName');

        $formMapper->removeGroup('Social', 'User');
        $formMapper->removeGroup('Status', 'Security');
        $formMapper->removeGroup('Keys', 'Security');
        $formMapper->removeGroup('Groups', 'Security');
        $formMapper->removeGroup('Roles', 'Security');
        $formMapper->removeGroup('Security', 'Security');

    }
}

and my configuration is as follow 

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Application\Sonata\UserBundle\Admin\UserAdmin
            #controller:     ApplicationSonataUserBundle:CURD
            translation:    SonataUserBundle

    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] 
------------------------------------
Hope this could help . For more information you could refer following link.
http://symfony.com/doc/current/bundles/SonataAdminBundle/cookbook/recipe_delete_field_group.html

**Comment by OskarStark** [comment]
@saifrehman15 i formatted your answer. now it is more readable

**Comment by saifrehman15** [comment]
I want to hide/remove the security tab from user edit page. Can I do that 
![security](https://cloud.githubusercontent.com/assets/8169432/24502132/e627c7bc-1565-11e7-9b0f-2f25fedfcd75.png)

**Comment by saifrehman15** [comment]
I have found the solution. Here it is . 
https://sonata-project.org/bundles/admin/3-x/doc/reference/action_show.html#setting-up-a-custom-show-template-very-useful
