### ISSUE TITLE
Installation instructions are missing a non-FOSUserBundle way of setup

### ISSUE THREAD

**Issue by kix** [sonata-project/SonataUserBundle#516]
The [installation instruction](https://github.com/sonata-project/SonataUserBundle/blob/2.2/Resources/doc/reference/installation.rst) states you can install SonataUserBundle without using (extending) FOSUserBundle, although this is only stated in the first paragraphs. The rest of the instruction just describes how to configure SonataUserBundle with FOSUserBundle enabled. 
I suggest that the doc should have a separate section for using SonataUserBundle is standalone mode (if that's possible, of course).

**Comment by core23** [comment]
We don't support a non-FOSUserBundle way.
