### ISSUE TITLE
No way to disable groups support

### ISSUE THREAD

**Issue by kix** [sonata-project/SonataUserBundle#517]
My application doesn't need group management, thus I don't even have an entity for groups, and I don't need to configure parameters under `fos_user.group`. However that does not work well with SonataUserBundle, it says:

```
The service "sonata.user.orm.group_manager" has a dependency on a non-existent parameter "fos_user.model.group.class"
```

I think there should be a way to both disable group management and avoid hacking the configuration. 
See also #168, @waiting-for-dev there tries to remove the service in a `CompilerPass`, and that's essentially just a hack. Though seems like he was forced into this as there's no obvious and documented way to fix this.

Please, can you suggest any ways I could fix this problem? I'm doing a bit digging in the sources now, but maybe you could give a hint?

**Comment by OskarStark** [comment]
i think this is related to the underlaying FOSUserBundle, not the SonataUserBundle @kix 

ping
@rande @Soullivaneuh , if you agree with me, please close this ticket!

Thank you

**Comment by Soullivaneuh** [comment]
@OskarStark Not really. The issue described means that sonata need group manager even if @kix don't want to do it.

I'll let this open by waiting for confirmation. Feel also free to make a PR about that. ;-)

**Comment by kix** [comment]
@OskarStark @Soullivaneuh Yes, exactly: I don't need group management at all while SonataUserBundle forces it.

**Comment by michaelkonecny** [comment]
@OskarStark @Soullivaneuh I confirm that, too.

**Comment by lukepass** [comment]
Hello, this is still a problem and there is no way to disable group support in Sonata User. Is there a fix? Thanks

**Comment by jordisala1991** [comment]
Continued in #999
