### ISSUE TITLE
Unable to replace alias "sonata.user.mongodb.user_manager" with "fos_user.user_manager".

### ISSUE THREAD

**Issue by VolodymyrChornohal** [sonata-project/SonataUserBundle#518]
Hi, 
I'm trying to install sonatauserbundle on Symfony CMF. So I did everything according to the guidelines.
Can anybody hint on why i'm getting this while trying to run this command "php app/console sonata:easy-extends:generate SonataUserBundle -d src"? 
Here is my fos_user configuration:

```
fos_user:
    db_driver:      mongodb
    firewall_name:  main
    user_class:     Sonata\UserBundle\Document\BaseUser

    group:
        group_class:   Sonata\UserBundle\Document\BaseGroup
        group_manager: sonata.user.mongodb.group_manager

    service:
        user_manager: sonata.user.mongodb.user_manager
```

**Comment by odeg36** [comment]
It could be possible that you resolve the problem? i'm in the exact position.

Greeting from Colombia

**Comment by OskarStark** [comment]
@VolodymyrChornohal what do you get? error please

thx

**Comment by VolodymyrChornohal** [comment]
Oh, sorry, I actually did solve this problem, simply by making corrections to configuration file: 
like this
    fos_user:
        db_driver:      mongodb
        firewall_name:  main
        user_class:     Application\Sonata\UserBundle\Document\User

        group:
            group_class:   Application\Sonata\UserBundle\Document\Group
            group_manager: sonata.user.mongodb.group_manager

        service:
            user_manager: sonata.user.mongodb.user_manager

and, this:

    # Doctrine MongoDB configuration
    doctrine_mongodb:
        connections:
            default:
                server: mongodb://localhost:27017
                options: {}
        default_database: test_database
        document_managers:
            default:
                mappings:
                        ApplicationSonataUserBundle: ~
                        SonataUserBundle: ~
                        FOSUserBundle: ~                                    # If SonataUserBundle extends it
                auto_mapping: true

**Comment by roman-1983** [comment]
I have changed to ``"sonata-project/user-bundle" : "~2.2@dev"`` to solve the problem.
