### ISSUE TITLE
require sonata datagrid

### ISSUE THREAD

**Issue by zazzou** [sonata-project/SonataUserBundle#521]
it requires sonata-datagrid so the installation via composer fails.
so i try to found this bundle on your site but the doc is missing (the page have no content but the header and the footer.) This have been already notified in the bundle's git (https://github.com/sonata-project/SonataDatagridBundle/issues/9)

**Comment by Soullivaneuh** [comment]
Can you provide your composer.json file and which error do you have?

**Comment by webdevilopers** [comment]
I guess it refers to:
- https://github.com/sonata-project/SonataUserBundle/issues/430
- https://github.com/sonata-project/SonataUserBundle/issues/492

If I got it right it only occurs when using `dev-master`. Since the installation docs recommend to use it this seems to be a huddle for beginners.

**Comment by ureimers** [comment]
Thanks you. Adding ``"minimum-stability": "dev"`` (and ``"prefer-stable": true`` too) to my project's ``composer.json`` resolved the composer requirement problems.

**Comment by jordisala1991** [comment]
This is fixed already
