### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by gnutix** [sonata-project/SonataUserBundle#526]
It's been more than a year since the latest stable tag. Is it normal ?

**Comment by OskarStark** [comment]
:+1:  for stable release!

**Comment by Schyzophrenic** [comment]
:+1: as well!

**Comment by ste93cry** [comment]
:+1:

**Comment by rande** [comment]
Do you want a new 2.2 release ? or a 2.3 release ? We can't release a new version with the master branch as the sonata admin bundle 2.4 is not yet stable.

**Comment by ste93cry** [comment]
I think a 2.3 release would be a good start, as this is the latest stable version of admin bundle and there is no 2.3 tag for this bundle. Trying to install SonataUserBundle from composer without specifing `2.3.*@dev` fails because there is no compatible version with SonataAdminBundle 2.3

**Comment by OskarStark** [comment]
:+1: for 2.3 first

**Comment by ste93cry** [comment]
We need a 2.3 release as soon as possible because the SonataUserBundle with recent changes introduced in d8cd1abd106c741837202d1fec2280149bfdaa3f broke the login form

**Comment by OskarStark** [comment]
@ste93cry you are right!

**Comment by Soullivaneuh** [comment]
@rande Is sonata user master enough stable to make a release?

If not, which issue must be resolved before?

**Comment by ste93cry** [comment]
As far as I can see SonataUserBundle at master version is being built on top of Sonata 2.4 and we need a 2.3 release. Prior to the commit d8cd1ab it is stable enough for a tag

**Comment by redactuk** [comment]
Any news on this?
