### ISSUE TITLE
Implement Avatar functionality

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataUserBundle#529]
Currently a `defaultAvatar` is featured
- http://sonata-project.org/bundles/user/master/doc/reference/advanced_configuration.html#advanced-configuration
  inside the user block
  https://github.com/sonata-project/SonataUserBundle/blob/master/Resources/views/Admin/Core/user_block.html.twig#L8

Some people wonder what this feature is about:
http://stackoverflow.com/questions/26515929/sonataadmin-users-profile-and-avatar

Are there any plans for instance extending the User with a Sonata Media Image to implement an Avatar functionality?

**Comment by Tocacar** [comment]
I am also interested to know...

**Comment by Soolan** [comment]
Me three

**Comment by xmon** [comment]
Me four

**Comment by ldelia** [comment]
Me five

**Comment by rande** [comment]
he he

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
I recommend [ornicar/gravatar-bundle](https://github.com/ornicar/GravatarBundle) usage for that.

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.

There have been some proposals for this issue. From my POV it can be closed.
Please tell me if I have to close it personally.
