### ISSUE TITLE
Admin LTE 2.0 login box integration is not working

### ISSUE THREAD

**Issue by ferranorriols** [sonata-project/SonataUserBundle#533]
Hi there,

This morning I've updated the sonataUserBundle and I've seen that something has changed with the styles in the login page. It's due to the changes of your last PR #527, but I don't see how to fix this problem. Could you please explain me what I have to change in order to have a default style?

This is a screenshot what I have:
![screenshot-sonataadmin](https://cloud.githubusercontent.com/assets/947112/6580484/2c4a5b52-c751-11e4-8002-19b24e1fd351.png)

Thanks

**Comment by rande** [comment]
Please review this: https://gist.github.com/rande/9c0cfbd751d3e64b893f
