### ISSUE TITLE
Clean Symfony with Sonata and FosUserBundle: Template not found

### ISSUE THREAD

**Issue by JPAntonisse** [sonata-project/SonataUserBundle#534]
If I choose to use the sonata routes in my routing.yml I get the following error while going to edit authentication via Profile:

Unable to find template "MopaBootstrapBundle:Form:fields.html.twig" in SonataUserBundle:ChangePassword:changePassword_content.html.twig at line 2.

If I choose to use the FOSUserBundle routes and I go to profile, the sonata user block menu gives the following error:

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "sonata_user_profile_edit" as such route does not exist.") in SonataUserBundle:Profile:action.html.twig at line 27.

I tried it with a clean Symfony install, i configured everything according to ALL the installation instructions. Still missing templates etc. It is really frustrating because I am doing hard work trying to learn Symfony2 with a good Sonata bundle. Yet I am failing because there are errors in the generated code.(?)

Composer requirements:

```json
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",

        "sonata-project/core-bundle": "~2.2@dev",
        "sonata-project/doctrine-orm-admin-bundle": "~2.3",
        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/user-bundle": "~2.2",
        "sonata-project/easy-extends-bundle": "~2.1",

        "knplabs/knp-menu-bundle": "v1.1.2",
        "knplabs/knp-menu": "v1.1.1"
    },
```

**Comment by core23** [comment]
This issue should be fixed in the latest stable version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
