### ISSUE TITLE
Sonata User Update

### ISSUE THREAD

**Issue by Th3Mouk** [sonata-project/SonataUserBundle#535]
Hello everyone ! 

After a composer update the https://github.com/sonata-project/SonataUserBundle/blob/master/Block/AccountBlockService.php no longer implements the same ErrorElement Class than the others blocks in this set of configuration.

Because this commit improve the location of the class
https://github.com/sonata-project/SonataCoreBundle/commit/56a10e60f669b1d55bab504a76d92b5d20b0f8c1

It's difficult to update all other blocks, because to correct my problem i need to wait that all of this have a new stable version this the new ErrorElement location.

```
sonata-project/admin-bundle              2.3.1              Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle
sonata-project/cache                     1.0.4              Cache library
sonata-project/cache-bundle              2.2.0              This bundle provides caching services
sonata-project/core-bundle               2.3.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master dba166c Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.1              Symfony Sonata / Integrate Doctrine ORM into the Son...
sonata-project/easy-extends-bundle       2.1.9              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.3.4              Lightweight Exporter library
sonata-project/formatter-bundle          2.3.3              Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP...
sonata-project/intl-bundle               2.2.1              Symfony SonataIntlBundle
sonata-project/media-bundle              2.3.1              Symfony SonataMediaBundle
sonata-project/notification-bundle       2.3.0              Symfony SonataNotificationBundle
sonata-project/page-bundle               2.3.8              Symfony SonataPageBundle
sonata-project/seo-bundle                1.1.9              Symfony SonataSeoBundle
sonata-project/user-bundle               dev-master ccb2718 Symfony SonataUserBundle
```

I really need user-bundle in 2.3 but since 1 year there is no stable release, and I just pay the price of a new improvement.

What is the better solution ? Roll Back https://github.com/sonata-project/SonataUserBundle/commit/ccb2718ca5352fc8ed73efd24bf466151148b3c6 ? Or tag a 2.3.0 without this commit ? Or i need to fork it and wait a stable release ?

Thanks for your help @rande 

Cheers

**Comment by rande** [comment]
Please review: https://gist.github.com/rande/9c0cfbd751d3e64b893f

**Comment by Th3Mouk** [comment]
Why there is no 2.3.0 for Sonata User Bundle ?

**Comment by rande** [comment]
@Th3Mouk this is a work in progress. The 2.3.0 will be the next stable release.

**Comment by Th3Mouk** [comment]
U rock @rande a lot of work !
