### ISSUE TITLE
utility of the 'TwoStepVerificationCode' field

### ISSUE THREAD

**Issue by tristanbes** [sonata-project/SonataUserBundle#54]
``` php
 [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'two_step_code' cannot be null 
```

Actually this is what i get because this field is mapped by the `BaseUser` from `SonataUserBundle`, i don't know the utility of this field ?

Should I add in my fixtures :

`$user->setTwoStepVerificationCode(sha1(time()));` or some random token ?

Thanks.

**Comment by shawe** [comment]
@rande working for me after execute the command you use for first activation that don't appear on documentation, but now isn't redirecting to the correct place once you are logged in.

**Comment by Soullivaneuh** [comment]
> that don't appear on documentation

PR are always welcomed. :wink:

**Comment by shawe** [comment]
Maybe this isn't a problem when you know what you can do and how, but not when you are learning...
