### ISSUE TITLE
User entity setters do not return $this

### ISSUE THREAD

**Issue by mcwebb** [sonata-project/SonataUserBundle#541]
All the entity setters return void rather than $this.
While I understand that this is somewhat personal preference, I think they should return $this for the sake of consistency since the class extends FOSUserBundle's wherein all setters do return $this. Which means that when operating on a single $user instance some setters will return $this while others will not.

I can provide a PR if you're in agreement.

**Comment by OskarStark** [comment]
PR would be nice, i agree with you! :+1:

**Comment by Soullivaneuh** [comment]
Let's go for a PR to see your proposition. :+1:
