### ISSUE TITLE
Invalid state, originalRoles array is not set, when creating a new user

### ISSUE THREAD

**Issue by brieuc28** [sonata-project/SonataUserBundle#548]
Hi,

Version of UserBundle : tested with 2.2.4 and actually using ~2.2 in my composer.json 

When i try to create (update is fine) a new user, with or without role(s) selected i straight have this error :

    Invalid state, originalRoles array is not set

Roles choices are added that way (Not modified, straight from vendor) :

    ->add('realRoles', 'sonata_security_roles', array(
                    'label'    => 'form.label_roles',
                    'expanded' => true,
                    'multiple' => true,
                    'required' => false
                ))

And here the code that return the exception (straight from vendor, so probably not a good idea to fix the error here except if it is a real issue).

    /**
     * {@inheritdoc}
     */
    public function reverseTransform($selectedRoles)
    {
        if ($this->originalRoles === null) {
            throw new \RuntimeException('Invalid state, originalRoles array is not set');
        }

        list($availableRoles, ) = $this->rolesBuilder->getRoles();

        $hiddenRoles = array_diff($this->originalRoles, $availableRoles);

        return array_merge($selectedRoles, $hiddenRoles);
    }

I tried to debug in the vendor and indeed in the class RestoreRolesTransformer, setOriginalRoles() return null. SetOriginalRoles() is called in the class ResolvedFormType that way :

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $formBuilder, array $options)
    {
        /**
         * The form shows only roles that the current user can edit for the targeted user. Now we still need to persist
         * all other roles. It is not possible to alter those values inside an event listener as the selected
         * key will be validated. So we use a Transformer to alter the value and an listener to catch the original values
         *
         * The transformer will then append non editable roles to the user ...
         */
        $tranformer = new RestoreRolesTransformer($this->rolesBuilder);

        // GET METHOD
        $formBuilder->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event) use ($tranformer) {
            $tranformer->setOriginalRoles($event->getData());
        });

        // POST METHOD
        $formBuilder->addEventListener(FormEvents::PRE_BIND, function(FormEvent $event) use ($tranformer) {
            $tranformer->setOriginalRoles($event->getForm()->getData());
        });

        $formBuilder->addModelTransformer($tranformer);
    }

Here the $_POST :

    $_POST = array[2]
	$_POST['s55408c8cd45a7'] = array[12]
		$_POST['s55408c8cd45a7']['username'] = (string) test@test.com
		$_POST['s55408c8cd45a7']['email'] = (string) test@test.com
		$_POST['s55408c8cd45a7']['plainPassword'] = (string) 12345
		$_POST['s55408c8cd45a7']['dateOfBirth'] = array[3]
			$_POST['s55408c8cd45a7']['dateOfBirth']['day'] = (string) 8
			$_POST['s55408c8cd45a7']['dateOfBirth']['month'] = (string) 6
			$_POST['s55408c8cd45a7']['dateOfBirth']['year'] = (string) 1988
		$_POST['s55408c8cd45a7']['firstname'] = (string) Firstname
		$_POST['s55408c8cd45a7']['lastname'] = (string) Lastname
		$_POST['s55408c8cd45a7']['phone'] = (string) 111122223333
		$_POST['s55408c8cd45a7']['city'] = (string) City
		$_POST['s55408c8cd45a7']['address'] = (string) Address
		$_POST['s55408c8cd45a7']['realRoles'] = array[1]
			$_POST['s55408c8cd45a7']['realRoles'][0] = (string) ROLE_SONATA_ADMIN
		$_POST['s55408c8cd45a7']['enabled'] = (string) 1
		$_POST['s55408c8cd45a7']['_token'] = (string) Jqz_-A1eHhKunLHe1AB-hYiSW7Dy81aO7quN2Wm84sY
	$_POST['btn_create_and_edit'] = <string>

I didn't yet understand the logic. Could it be a real issue?

**Comment by sjagr** [comment]
Does your extended `User` entity have a `__construct` function? If so, it needs to extend the parent's construct.

**Comment by brieuc28** [comment]
That was indeed the problem. I had also 2 other entities extending the User Entity where i did forget to put parent::__construct();

Thank you!
