### ISSUE TITLE
dateOfBirth user profile

### ISSUE THREAD

**Issue by aliocza** [sonata-project/SonataUserBundle#550]
The datepicker for dateOfBirth is locked with parameters : 
(sonata-project\user-bundle\Admin\Entity\UserAdmin.php)

```
->add('dateOfBirth', 'sonata_type_date_picker', array(
      'years' => range(1900, $now->format('Y')),
      'dp_min_date' => '1-1-1900',
      'dp_max_date' => $now->format('c'),
      'required' => false
))
```

> **Preview:**  
> ![bug](https://cloud.githubusercontent.com/assets/8338334/7494235/c59cef68-f406-11e4-87e1-d1d7ba30fa08.jpg)

**Comment by OskarStark** [comment]
so what is wrong?
can you please say what IS and what SHOULD?

thanks

**Comment by aliocza** [comment]
we can't set the date if this is locked... then the range in the code it's correct but
i think it's a bug.
you can try with demo : http://demo.sonata-project.org/admin/app/user/1/edit

**Comment by OskarStark** [comment]
what do you mean with "locked"?

you mean you can go backward but not forward in the datepicker?

**Comment by aliocza** [comment]
i can't click on one date in the calendar but if you write manually into input it's ok.
ex: if you set directly in input : "April 01, 1992" ok, if you try with calendar you cannot set because the calendar is locked.

**Comment by jordisala1991** [comment]
Closing because it does not make a lot of sense. I just tested it and the calendar for picking dates is working correctly.

Feel free to provide more information if this issue is still relevant. If any of the @sonata-project/contributors understands this and care to explain, please reopen too.
