### ISSUE TITLE
Style problem with SonataUserBundle/FOSBundle

### ISSUE THREAD

**Issue by yuriricci** [sonata-project/SonataUserBundle#551]
Hi everyone,
I have a problem in the rendering (styles) of the login and the logout sections:
![1](https://cloud.githubusercontent.com/assets/7250389/7552437/34e7ff66-f6b4-11e4-9a34-7e78a32d7a28.png)
![2](https://cloud.githubusercontent.com/assets/7250389/7552438/3767814e-f6b4-11e4-8836-c62a5cb5fde4.png)
For what concerns functionality, they work ok. Also, no errors are shown if I inspect the client-server dialogue, which is quite strange. It happened when I update to last STABLE versions, using composer config:
"sonata-project/core-bundle": "~2.3",
 "sonata-project/admin-bundle": "~2.3",
 "sonata-project/doctrine-orm-admin-bundle": "~2.3",
 "sonata-project/user-bundle": "~2.2",

EDIT:
After some more digging, it seems that they are actually the login and logout widgets of Sonata User Bundle... am I wrong? If it is so, are maybe planned some look & feel enhancements in the next stable release?

**Comment by MM-Psiiirus** [comment]
hi @yuriricci , i've run into the same problem and fixed it by just extend the SonataUserBundle:Admin:Security:login.html.twig from the 
{% extends 'SonataAdminBundle::empty_layout.html.twig' %} Template
instead of the
{% extends 'SonataAdminBundle::standard_layout.html.twig' %} Template

**Comment by yuriricci** [comment]
Hi @MM-Psiiirus, thank you for your reply.
Can you argument a bit more precisely your solution? If I understood correctly, you used the SonataAdminBundle::empty_layout.html.twig view in place of the SonataAdminBundle::standard_layout.html.twig view, and within such view you extended SonataUserBundle:Admin:Security:login.html.twig?

**Comment by MM-Psiiirus** [comment]
Hiya,
after finishing the SonataUserBundle installation guide you should have already set upped the easy-extend version of the SonataUserBundle so its quite easy to overload this template by just put it into the needed folder as seen on my screenshot. I would prefer to complete copy the whole twig file and just edit the first line as i already posted before. :)

![bildschirmfoto 2015-06-18 um 08 14 08](https://cloud.githubusercontent.com/assets/593363/8225245/7c281c9c-1592-11e5-8d51-1bdf47918997.png)
