### ISSUE TITLE
Error after composer update

### ISSUE THREAD

**Issue by bnd170** [sonata-project/SonataUserBundle#556]
I made a project using Sonata Package with admin, media... user too implemeted with FOSUser.

I create a custom User Entity following your doc and before today's update it works fine.

Now my website throws me an 500 Internal Server Error and my php logger shows me this error:

Call to a member function getUser() on a non-object in vendors\sonata-project\user-bundle\Controller\SecurityFOSUser1Controller.php on line 29

The lane is:

```
    $user = $this->container->get('security.context')->getToken()->getUser();
```

I think it happen when I try to open some controller that uses an entity linked to the user entity.

```
/**
 * @ORM\ManyToOne(targetEntity="\Application\Sonata\UserBundle\Entity\User")
 * @ORM\JoinColumn(name="author_id", referencedColumnName="id")
 */
private $user;
```

It doesnt throw me an error but the relation doesnt work in DB.

**Comment by OskarStark** [comment]
can you rollback to the version of SonataUserBundle before and try again?

what does ```doctrine:mapping:info``` say?

**Comment by jordisala1991** [comment]
Closing, not enough info
