### ISSUE TITLE
Add api doc section parameter

### ISSUE THREAD

**Issue by ruscon** [sonata-project/SonataUserBundle#560]
https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md

The following properties are available:
section: allow to group resources

![Example](https://api.monosnap.com/rpc/file/download?id=8bnWjHLBVgtaBx5CD6whAUgDTItiUg)

**Comment by core23** [comment]
Not sure what to do here... Can you provide a PR?

**Comment by ruscon** [comment]
The following properties are available:
section: allow to group resources
resource: whether the method describes a main resource or not (default: false);

example:
https://github.com/nelmio/NelmioApiDocBundle/issues/402#issuecomment-48711707

**Comment by ruscon** [comment]
> Can you provide a PR?
Ok

**Comment by core23** [comment]
Sorry, for my stupid question. But I'm not using the REST API. Just doing some housekeeping on the issues.

**Comment by jordisala1991** [comment]
No PR was provided, and I didnt find other bundles using this section parameter.

If you want to provide a PR or keep the issue alive, please ping me, otherwise if no one cares about section, I dont see any interest of keepong this opened.

Closing for now.
