### ISSUE TITLE
Deprecated SecurityContextInterface 

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataUserBundle#568]
`SecurityContextInterface` is deprecated since Symfony 2.6.

`TokenStorageInterface` and/or `AuthorizationCheckerInterface` should be used instead.

Make sure to keep BC with Symfony <2.6

Concerned files:
- https://github.com/sonata-project/SonataUserBundle/blob/master/Block/AccountBlockService.php
- https://github.com/sonata-project/SonataUserBundle/blob/master/GoogleAuthenticator/RequestListener.php
- https://github.com/sonata-project/SonataUserBundle/blob/master/Security/EditableRolesBuilder.php
- https://github.com/sonata-project/SonataUserBundle/blob/master/Tests/Security/EditableRolesBuilderTest.php

**Comment by PurpleBooth** [comment]
Any news on this issue, it's been depreciated for about a year now.

Is this project still under active development?

**Comment by core23** [comment]
> Is this project still under active development?

Yes, we're working on the next major release.

We would appreciate new contributors. Feel free to improve the code @PurpleBooth 👍

**Comment by PurpleBooth** [comment]
Sure, I'm happy to submit a patch, probably be sometime tomorrow

**Comment by jordisala1991** [comment]
This is no longer a problem with 4.0
