### ISSUE TITLE
Travis: More than 20 minutes composer up --prefer-lowest

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataUserBundle#574]
This is incredible: https://travis-ci.org/sonata-project/SonataUserBundle/jobs/66365243

I see two "solutions" at this moment:

* Review `composer.json` file. See: https://github.com/composer/composer/issues/3993#issuecomment-111120628
* Find a way to increase (again) composer timeout option.

Will make a PR for testing.

**Comment by rande** [comment]
I think we need to disable the --prefer-lowest option for now, we have no time to fix composer regression.

**Comment by Soullivaneuh** [comment]
Let's wait for this job: https://travis-ci.org/sonata-project/SonataUserBundle/builds/66508971

If it fail again, I'll add it on allowed_failure then. :/

**Comment by mmoreram** [comment]
There is another way to fix this. Travis says that the timeout is 10 minutes without any output data. What you can do is enable the -v. Then you will not have any timeout anymore :)

**Comment by Soullivaneuh** [comment]
@mmoreram Already tried on local. But the `-v` option is not helpful because of no output during dependencies resolving. And it's especially this resolving that take more than 20 minutes.

**Comment by mmoreram** [comment]
`-vvv` ? XD

**Comment by Soullivaneuh** [comment]
@mmoreram good try, but no. :-)

**Comment by mmoreram** [comment]
Well, I'm having the same problem... and it is very annoying. Did you find another way of solving this issue?

**Comment by Soullivaneuh** [comment]
BTW, composer should not be long as this.

But this issue is not very actual since cache is set up.

Travis run quite good now: https://travis-ci.org/sonata-project/SonataUserBundle

**Comment by mmoreram** [comment]
Composer length is not something I can decide...

A project has `n` dependencies, and each dependency must be computed. You can avoid several dependencies by adding middle packages, but then you will need more time to compute these dependencies... so if my project (not package, project) has a long dependency file, should be OK.
