### ISSUE TITLE
How can there be so many issues??

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataUserBundle#583]
I just did composer require sonata-project/user-bundle 
and got all of this:

 Problem 1
    - sonata-project/user-bundle 2.2.2 requires sonata-project/admin-bundle ~2.2.7 -> no matching package found.
    - sonata-project/user-bundle 2.2.1 requires sonata-project/admin-bundle ~2.2.7 -> no matching package found.
    - sonata-project/user-bundle 2.2.0 requires sonata-project/admin-bundle ~2.2.7 -> no matching package found.
    - sonata-project/user-bundle 2.2.3 requires friendsofsymfony/user-bundle ~1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev].
    - sonata-project/user-bundle 2.2.4 requires friendsofsymfony/user-bundle ~1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev].
    - Conclusion: don't install friendsofsymfony/user-bundle 1.3.x-dev
    - Installation request for sonata-project/user-bundle ^2.2 -> satisfiable by sonata-project/user-bundle[2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

I know I can use --no-update and that will work... but still.. sonata admin bundle is on version 2.3.3 why does user bundle require 2.2.7?? 
And fos user bundle is on 2.0 why is this still stuck on 1.3????

**Comment by Soullivaneuh** [comment]
That kind and title and many `?` won't help you neither other users. Please make a clean title like "Composer dependencies break" for example.

> why does user bundle require 2.2.7??

It doesn't, see: https://github.com/sonata-project/SonataUserBundle/blob/9716d46303706f0f00ad1931a436bdd085cc978b/composer.json#L25

Can you please paste your full composer.json and the result of `composer info -i | grep sonata`?

**Comment by AntonioCS** [comment]
Ok that is great so how about you move from FOSUserBundle 1.3 to 2.0?
It might not require 2.2.7 but that is what it says there.

**Comment by AntonioCS** [comment]
> sonata-project/admin-bundle          2.3.3   Symfony SonataAdminBundle
> sonata-project/block-bundle          2.2.13  Symfony SonataBlockBundle
> sonata-project/cache                 1.0.6   Cache library
> sonata-project/core-bundle           2.3.4   Symfony SonataCoreBundle
> sonata-project/doctrine-extensions   1.0.2   Doctrine2 behavioral extensions
> sonata-project/easy-extends-bundle   2.1.9   Symfony SonataEasyExtendsBundle
> sonata-project/exporter              1.3.4   Lightweight Exporter library
> sonata-project/google-authenticator  1.0.2   Library to integrate Google Authenticator into a PHP project
> sonata-project/user-bundle           2.2.4   Symfony SonataUserBundle

**Comment by Soullivaneuh** [comment]
> Ok that is great so how about you move from FOSUserBundle 1.3 to 2.0?

https://github.com/sonata-project/SonataUserBundle/pull/555

> It might not require 2.2.7 but that is what it says there.

I repeat: sonata-user 2.x **does not** require sonata-admin 2.2.7. It require `>=2.2.9` and btw 2.2.9 exists: https://github.com/sonata-project/SonataAdminBundle/tree/2.2.10

Maybe a simple global `composer update` should do the trick.

`composer.json` copy paste still missing.

**Comment by AntonioCS** [comment]
As you can see I am using 2.3.3. So I hope all the bundles will play nicely with one another.
Ok, great, there will be support for 2.0. Any idea when this will be merged?

Composer.json
```
{
    "name": "site",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/",
            "SymfonyStandard\\": "app/SymfonyStandard/"
        }
    },
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~1.3",        
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/user-bundle": "^2.2"

    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3"
    },
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ],
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
```




Thanks for the quick reply.

**Comment by Soullivaneuh** [comment]
> As you can see I am using 2.3.3. So I hope all the bundles will play nicely with one another.

`"sonata-project/admin-bundle": "~2.2,>=2.2.9"` mean all 2.x versions of this bundle are supported.

Have you try required it manually and run `composer update` again?

**Comment by AntonioCS** [comment]
Yes! and it all seems to be ok... Magic! Might have been other modules that conflicted with something.

Regarding the update to fos user bundle 2.0, any ETA on that?

**Comment by Soullivaneuh** [comment]
> Regarding the update to fos user bundle 2.0, any ETA on that?

No AFAIK. This will be available when the concerned PR will be ready and merged.

I close this issue as far it's resolved.
