### ISSUE TITLE
Duplicate validation error messages are shown when YML server-side validation files are split into  each file

### ISSUE THREAD

**Issue by cithukyaw** [sonata-project/SonataUserBundle#584]
I disabled HTML5 validation for Sonata Admin Forms. I enabled server-side validation by adding all validation rules for all entities in  `MyBundle\Resources\config\validation.yml`. I added `app\Resources\SonataAdminBundle\views\CRUD\edit.html.twig` with the following content to disable the pretty popover errors:

	{% extends 'SonataAdminBundle:CRUD:base_edit.html.twig' %}
	
	{% block javascripts %}
	    {{ parent() }}
	    <script type="text/javascript">
	        if (Admin) {
	            // disable popover error messages
	            Admin.add_pretty_errors = function() {}
	        }
		</script>
	{% endblock %}

Everything was fine and the error messages are shown underneath of field. Then, I split the validation rules for each entity in each file according to [the SO answer](http://stackoverflow.com/a/24210501/1179841) such as 

```
MyBundle\Resources\config\validation\
|__	property.yml
|__	user.yml
```

The problem comes here. The duplicate error messages are shown:

when popover messages are enabled

![635703491059624013](https://cloud.githubusercontent.com/assets/4285555/8257510/1e2f622e-16d4-11e5-939a-3046322ca40b.png)

when popover messages are disabled

![635703491143998839](https://cloud.githubusercontent.com/assets/4285555/8257514/2559fb90-16d4-11e5-9043-17d03aa8c232.png)

**Comment by core23** [comment]
This issue should be fixed in the latest stable version. 

If this is still present, feel free to reopen this issue
