### ISSUE TITLE
Extended user class validation

### ISSUE THREAD

**Issue by gnorby88** [sonata-project/SonataUserBundle#585]
Hello.

I use sf 2.7 and sonata user bundle 2.3dev. I extended my user class from the sonata baseuser.

```
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Symfony\Component\Validator\Constraints as Assert;
```

In my user class i added an image field:

```
class User extends BaseUser
{
...
    /**
     * @ORM\ManyToOne(targetEntity="Media", cascade={"persist", "remove"})
     * @Assert\Valid
     */
```

But the validation dont work. In the other entity (product, brand..) its working..
I tryed xml,yml validation, validation groups and nothing.. I have installed SonataUserBundle according to the docs and i checked twice the config..
So... What have I missed?

**Comment by OskarStark** [comment]
you get an error?

can you please format this as a code block?

**Comment by gnorby88** [comment]
No error. Just ignore the validation.

**Comment by jordisala1991** [comment]
This is because User class use validation groups. You need to define the validation group for your field.

Closing, if you still having this issue, please provide more information, and we will reopen
