### ISSUE TITLE
German translations are incomplete

### ISSUE THREAD

**Issue by gnutix** [sonata-project/SonataUserBundle#588]
But I'm no German speaker, so I cannot translate them myself. Anyone willing to help ?
I've found the following missing keys : 

* sonata_profile_title
* link_show_profile
* link_edit_profile
* title_user_edit_authentication
* link_edit_authentication
* label_profile_gender
* label_profile_firstname
* label_profile_lastname
* label_profile_website
* label_profile_dob
* label_profile_biography
* label_profile_locale
* label_profile_timezone
* label_profile_phone
* profile.flash.updated
* sonata_change_password_link
* link_register
* link_login
* link_logout
* registration.flash.user_created
* forgotten_password
* sonata_user_profile_breadcrumb_index
* sonata_user_profile_breadcrumb_edit

**Comment by OskarStark** [comment]
For example this one:
```xml
            <trans-unit id="link_register">
                <source>link_register</source>
                <target>Registrieren</target>
            </trans-unit>
```
is already translated, are you sure that all of these are missing?

Have a look here:
https://github.com/sonata-project/SonataUserBundle/edit/master/Resources/translations/SonataUserBundle.de.xliff

**Comment by gnutix** [comment]
I'm using "sonata-project/user-bundle": "2.2.4", which is the latest tag, and it's not translated there.

**Comment by OskarStark** [comment]
just copy the latest file and overwrite it in your project

create a directory under ```app```
-> ```Resources\SonataUserBundle\translations\````

and copy all translation files there!

keep me updated if its working

**Comment by OskarStark** [comment]
Yes

Which one?

Am Mittwoch, 24. Juni 2015 schrieb Dorian Villet :

**Comment by gnutix** [comment]
Didn't get your comment. What do you mean "which one?" ?

**Comment by OskarStark** [comment]
sorry the message was from yesterday via mail and didnt get out... sorry
