### ISSUE TITLE
jms/serializer-bundle 1.0.0 version support

### ISSUE THREAD

**Issue by nandorstanko** [sonata-project/SonataUserBundle#590]
I can't update my project because jms/serializer-bundle requires jms/serializer ^1.0.0. Please just add the support for this version as well to composer (~0.11|~1.0) or remove the conflict part if possible. Nothing has changed in the serializer, just the version number.

**Comment by Soullivaneuh** [comment]
> Nothing has changed in the serializer, just the version number.

Seems not:

> [BC Break] Passes DeserializationContext to ObjectConstructor instances as additional argument

https://github.com/schmittjoh/serializer/blob/master/CHANGELOG.md

I'll give a try on a PR.

@rande are the tests covering serialization on sonata-user?
