### ISSUE TITLE
No fields available for groups, roles and status

### ISSUE THREAD

**Issue by ferriss** [sonata-project/SonataUserBundle#593]
I'm using the dev-master user-bundle.
No options for groups in the security user tab, while I've added a few groups...
This is also showing on the demo sandbox environment of sonata admin.

The strange thing is the options are there while creating a user.
Will take a look at the form builder but for future updates this should be fixed.

Glad if anyone can help!

**Comment by ferriss** [comment]
I commented out UserAdmin.php line 188
        if ($this->getSubject() && !$this->getSubject()->hasRole('ROLE_SUPER_ADMIN')) {

This should probably check for the logged user instead of the user subject...
Strange as i did see the security tab and field but no contents.
Anyway, i can progress

**Comment by sharky98** [comment]
I have the same issue. I can't even modify my own groups.
Modifying the line to
if ($this->getSubject()) {
allow to see the field. However, I don't know the implication of doing that (what was the idea behind preventing modifying a user that has super admin role?). Maybe a better way would be to check if logged user have super admin role?

**Comment by jordisala1991** [comment]
Fixed in https://github.com/sonata-project/SonataUserBundle/pull/717

Closing
