### ISSUE TITLE
No label for checkbox locked enabled and expired

### ISSUE THREAD

**Issue by titom59280** [sonata-project/SonataUserBundle#595]
Hello, 

I had implement sonataUserBundle but I have a issue with the edition or creation of a user :

With this line in the configureFormFields function
```php
    ->add('locked', null, array('label'=>'someLabel','required' => false))
```

I have the checkbox but the label is not displaying.

it's the same for enabled or expired

How can I do to display them.

Thnaks for your time

**Comment by OskarStark** [comment]
Can you post a screenshot please?

**Comment by titom59280** [comment]
![sonata](https://cloud.githubusercontent.com/assets/7037603/8407277/64552ef8-1e65-11e5-8c35-55b27ddab38e.png)

**Comment by webdevilopers** [comment]
Have you tried current `dev-master` @titom59280 ? I think the issue was fixed with https://github.com/sonata-project/SonataAdminBundle/issues/2630 .

**Comment by titom59280** [comment]
Sorry about that I was on something else so far and I totally forget about it but I think it fixed because I don't had a bad return from my boss.

**Comment by OskarStark** [comment]
thanks for the feedback
