### ISSUE TITLE
This form should not contain extra fields (api call)

### ISSUE THREAD

**Issue by edouardkombo** [sonata-project/SonataUserBundle#600]
Hi everyone,

I'm really stucked with Sonata UserBundle api, using symfony 2.7 and sonataUserBundle 2.3.x-dev.
I try to create a user with POST method, and this is the result I get.
    
    {
        "code": 400,
        "message": "Validation Failed",
        "errors": {
            "errors": [
                "This form should not contain extra fields."
            ],
            "children": {
                "username": {},
                "email": {},
                "enabled": {},
                "plainPassword": {},
                "passwordRequestedAt": {},
                "locked": {},
                "expired": {},
                "expiresAt": {},
                "roles": {},
                "credentialsExpired": {},
                "credentialsExpireAt": {},
                "facebookData": {},
                "twitterData": {},
                "gplusData": {},
                "twoStepVerificationCode": {},
                "dateOfBirth": {},
                "firstname": {},
                "lastname": {},
                "website": {},
                "biography": {},
                "gender": {},
                "locale": {},
                "timezone": {},
                "phone": {},
                "facebookUid": {},
                "facebookName": {},
                "twitterUid": {},
                "twitterName": {},
                "gplusUid": {},
                "gplusName": {},
                "token": {}
            }
        }
    }

This is my javascript call request:

        var url     = myform.action;
        var http    = new XMLHttpRequest();
        var roles = ['ROLE_USER'];

        var data = new FormData();
        data.append('username', 'xxxxxx');
        data.append('email', 'xxxxxxx@xxx.com');
        data.append('plainPassword', 'xxxxxx');
        data.append('enabled', true);
        data.append('locked', false);
        data.append('expired', false);
        data.append('expiresAt', '2019-08-26 12:05:05');
        data.append('roles[]', roles);
        data.append('credentialsExpired', false);

        console.log(data);

        http.open("POST", url, true);
        //http.withCredentials = true;
        http.onreadystatechange = function() {//Call a function when the state changes.
            if(http.readyState == 4 && http.status == 200) {
                console.log(http.responseText);
                http = null;
            } else {
                console.log(http.responseText);
            }
        };
        http.send(data);

Can anyone help me please?

**Comment by OskarStark** [comment]
can you please put the json in a code block?

**Comment by edouardkombo** [comment]
@OskarStark DONE

**Comment by edouardkombo** [comment]
Up please, any idea?

**Comment by OskarStark** [comment]
can please post your FormType?

**Comment by edouardkombo** [comment]
I see the problem.

First of all, I have to update my Sonata CoreBundle dependency:
    composer require sonata-project/core-bundle 2.3.4

Then, I have to extend the user api controller and add this line to remove extra fields on form submit (https://sonata-project.org/bundles/core/master/doc/reference/api.html):
    FormHelper::removeFields($request->request->all(), $form);

The problem is that, the original service is in xml format: Sonata\UserBundle\Resources\Config\api_controllers.xml.
This is the content:

    <?xml version="1.0" encoding="UTF-8" ?>

    <container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

        <services>
            <service id="sonata.user.controller.api.user" class="Sonata\UserBundle\Controller\Api\UserController">
                <argument type="service" id="sonata.user.user_manager" />
                <argument type="service" id="sonata.user.group_manager" />
                <argument type="service" id="form.factory" />
            </service>

            <service id="sonata.user.controller.api.group" class="Sonata\UserBundle\Controller\Api\GroupController">
                <argument type="service" id="sonata.user.group_manager" />
                <argument type="service" id="form.factory" />
            </service>
        </services>
    </container>


How to transform this configuration in YML format properly?

Thanks.

**Comment by OskarStark** [comment]
1) why do you want to transform this configuration?

2) you can use this one: http://converter.rosstuck.com/

3) i did this for you:
```yml
services:
    sonata.user.controller.api.user:
        class: Sonata\UserBundle\Controller\Api\UserController
        arguments: ['@sonata.user.user_manager', '@sonata.user.group_manager', '@form.factory']
    sonata.user.controller.api.group:
        class: Sonata\UserBundle\Controller\Api\GroupController
        arguments: ['@sonata.user.group_manager', '@form.factory']
```

**Comment by edouardkombo** [comment]
1) why do you want to transform this configuration?

Because, my error "This form should not contain extra fields." means that that I have submitted extra fields and that Sonata is unable to bypass them if they are not mapped.

So I need to override the api UserController to delete additionnal extra fields, by adding:

    FormHelper::removeFields($request->request->all(), $form);

Before the form bind, inside the handleWriteUser method.


I did this, but still having the issue :(.

**Comment by edouardkombo** [comment]
Ok, I see clearly now.

I am submitting boolean values as string values, this is my mistake :)

**Comment by OskarStark** [comment]
hmm, but then the error message is wrong i think

**Comment by edouardkombo** [comment]
Yes the error message is wrong, and otherwise, I was wrong too.

I don't know why this error happened.

**Comment by edouardkombo** [comment]
SOLVED !!!!!

It was the "ROLES" array that wasn't in the good format.
When I don't send the ROLES array, everything works fine !

**Comment by phansys** [comment]
Nice to know @edouardkombo. Could you close this issue then?

**Comment by edouardkombo** [comment]
Closed :)
