### ISSUE TITLE
Add translation to field type array e.g. custom roles block

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataUserBundle#602]
In my custom `UserAdmin` I add `roles` and `groups` to my `showMapper`:

``` php
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->with('Contact', array('class' => 'col-md-4'))
                ->add('firstName')
                ->add('lastName')
                ->add('mobile')
                ->add('email')
            ->end()
            ->with('User', array('class' => 'col-md-4'))
                ->add('enabled')
                ->add('username')
                ->add('roles', 'array', array(
                    'translation_domain' => 'roles'
                ))
                ->add('groups')
            ->end()
            ->with('Qualifications', array('class' => 'col-md-4'))
                ->add('qualifications') // how to suppress show links without removing show route?
            ->end()
        ;
    }
```

Both are displayed like this:
![bildschirmfoto vom 2015-07-10 12 00 53](https://cloud.githubusercontent.com/assets/3479626/8616370/07e96a00-26fb-11e5-819e-84103e574c32.png)

The `roles` are displayed as `array`:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/list_array.html.twig#L16

The `groups` are displayed as a list.

I guess the `roles` would have been displayed as a list too if I assigned them to a `Admin class`?

Since there is no custom `roles` block in `SonataUserBundle` I guess I have to add a custom template instead of using the `array` type?

Should the `array` type feature translation?

**Comment by webdevilopers** [comment]
My current solution looks like this:
```twig
{% extends 'SonataAdminBundle:CRUD:base_show_field.html.twig' %}

{% block field %}
    <ul>
    {% for role in value %}
        <li>{{ role|trans({}, 'roles') }}</li>
    {% endfor %}
    </ul>
{% endblock %}
```

Is there a way to get the `translation_domain` from the `showMapper`?
```php
                ->add('roles', 'array', array(
                    'translation_domain' => 'roles'
                ))
```

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
