### ISSUE TITLE
User add crash in the Admin page

### ISSUE THREAD

**Issue by smekens** [sonata-project/SonataUserBundle#604]
I have built a system based on the example of the SonateUserBundle. All work fine but when I wand to create or modify a user entry, it crashes with this error:

Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Form\DataTransformer\ModelsToArrayTransformer::__construct() must be an instance of Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList, instance of Symfony\Component\Form\ChoiceList\LegacyChoiceListAdapter given, called in /var/www/dev.hypnos-solutions.com/app/cache/dev/classes.php on line 13683 and defined 

I can not find any informations about this problem.

Here is my configuration:
```
{
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.7@beta",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "~1.3",
        "friendsofsymfony/jsrouting-bundle": "~1.1",
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/doctrine-extensions": "^1.0",
        "sonata-project/user-bundle": "^2.2",
        "sonata-project/easy-extends-bundle": "^2.1",
        "knplabs/knp-menu-bundle": "~1.1",
        "mopa/bootstrap-bundle": "v3.0.0-beta3"
    },
}
```

and

    public function registerBundles()
    {
        $bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Symfony\Bundle\AsseticBundle\AsseticBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),

            new FOS\JsRoutingBundle\FOSJsRoutingBundle(),

            new Sonata\CoreBundle\SonataCoreBundle(),
            new Sonata\BlockBundle\SonataBlockBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
            new Sonata\AdminBundle\SonataAdminBundle(),

            new FOS\UserBundle\FOSUserBundle(),
            new Sonata\UserBundle\SonataUserBundle('FOSUserBundle'),
            new Application\Sonata\UserBundle\ApplicationSonataUserBundle(),

            new HypnosSolutions\MainBundle\HypnosSolutionsMainBundle(),
            new HypnosSolutions\DocBundle\HypnosSolutionsDocBundle(),
            new HypnosSolutions\NewsBundle\HypnosSolutionsNewsBundle(),

            new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),

            new Mopa\Bundle\BootstrapBundle\MopaBootstrapBundle(),
        );

        if (in_array($this->getEnvironment(), array('dev', 'test'))) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
        }

        return $bundles;
    }

Sincerely
Christophe Smekens

**Comment by tunne** [comment]
Christophe,
 
It should be fixed with this https://github.com/symfony/symfony/pull/14551 merged pull request.

In my opinion, you could try to use the Symfony 2.7 branch or you could try to fix the Sonata DataTransformers to work with the LegacyChoiceListAdapter.

Kindest regards

**Comment by smekens** [comment]
Fixed!!!

It works with symfony "2.6.*", "2.7.0" and "2.7.1"
It doesn't work with "2.7.2" and later.

Thanks,
Christophe

**Comment by tunne** [comment]
Nice,

There's already a PR for the issue, but maybe it should  be an interface.
https://github.com/sonata-project/SonataAdminBundle/pull/3111

Maybe we should close this one.

 Regards
Gilles

**Comment by Soullivaneuh** [comment]
@smekens This is already fixed on https://github.com/sonata-project/SonataAdminBundle/pull/3111

Please update your dependencies, this should fix the issue.
