### ISSUE TITLE
How to add new field to api

### ISSUE THREAD

**Issue by edouardkombo** [sonata-project/SonataUserBundle#607]
Hi everyone,

I've added new fields inside sonataUserBundle, now I want them to be available inside the api, but it is not setted automatically.

Could someone help me please?

**Comment by Soullivaneuh** [comment]
Which API you mean?

**Comment by edouardkombo** [comment]
I'm using FOSRestBundle with NelmioAPIDocBundle, default bundles provided by Sonata.

I've extended sonata User entity with new properties, now I am unable to get them accessible through an api call.

**Comment by edouardkombo** [comment]
This is an example of my user entity

	<?php

	/**
	 * This file is part of the <name> project.
	 *
	 * (c) <yourname> <youremail>
	 *
	 * For the full copyright and license information, please view the LICENSE
	 * file that was distributed with this source code.
	 */

	namespace Application\Sonata\UserBundle\Entity;

	use Doctrine\ORM\Mapping as ORM;
	use Doctrine\ORM\EntityManager;
	use Doctrine\Common\Collections\ArrayCollection;
	use Sonata\UserBundle\Entity\BaseUser as BaseUser;
	use Application\Sonata\ClassificationBundle\Entity\Tag as Tag;

	use JMS\Serializer\Annotation\ExclusionPolicy;
	use JMS\Serializer\Annotation\Expose;
	use JMS\Serializer\Annotation\Groups;
	use JMS\Serializer\Annotation\VirtualProperty;

	/**
	 * @ORM\Entity
	 * @ORM\Table(name="fos_user_user")
	 *
	 * @ExclusionPolicy("all")
	 */
	class User extends BaseUser
	{
		/**
		 * @var integer
		 * @ORM\Column(type="integer")
		 * @ORM\Id
		 * @ORM\GeneratedValue(strategy="AUTO")
		 */
		protected $id;

		/**
		 * @var ArrayCollection Tag $tags
		 * Owning Side
		 *
		 * @ORM\ManyToMany(targetEntity="\Application\Sonata\ClassificationBundle\Entity\Tag", inversedBy="users", cascade={"persist", "merge", "remove"})
		 * @ORM\JoinTable(name="fos_user_users_tags",
		 *   joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
		 *   inverseJoinColumns={@ORM\JoinColumn(name="tag_id", referencedColumnName="id")}
		 * )
		 */
		protected $tags;

		/**
		 * @var string
		 *
		 * @ORM\Column(name="creation_ip", type="string", nullable=true)
		 * @Expose
		 */
		protected $creationIp;

		/**
		 * @var string
		 *
		 * @ORM\Column(name="last_access_ip", type="string", nullable=true)
		 * @Expose
		 */
		protected $lastAccessIp;


		public function __construct()
		{
			parent::__construct();
			$this->tags = new ArrayCollection();
		}

		/**
		 * Get id
		 *
		 * @return integer $id
		 */
		public function getId()
		{
			return $this->id;
		}

		/**
		 * Add Tag
		 *
		 * @param \Application\Sonata\ClassificationBundle\Entity\Tag $tag
		 */
		public function addTag(Tag $tag)
		{
			// Si l'objet fait déjà partie de la collection on ne l'ajoute pas
			if (!$this->tags->contains($tag)) {
				$this->tags->add($tag);
			}
		}

		public function setTags($tags)
		{
			if ($tags instanceof ArrayCollection || is_array($tags)) {
				foreach ($tags as $tag) {
					$this->addTag($tag);
				}
			} elseif ($tags instanceof Tag) {
				$this->addTag($tags);
			} else {
				throw new Exception("$tags  must be an instance of Tag or ArrayCollection");
			}
		}

		/**
		 * Get ArrayCollection
		 *
		 * @return ArrayCollection $tags
		 */
		public function getTags()
		{
			return $this->tags;
		}

		/**
		 * Get lastAccess
		 *
		 * @return string $creationIp
		 * @VirtualProperty
		 */
		public function getCreationIp()
		{
			return $this->creationIp;
		}

		/**
		 * Set creationIp
		 *
		 * @return User
		 * @VirtualProperty
		 */
		public function setCreationIp($creationIp)
		{
			$this->creationIp = $creationIp;

			return $this;
		}

		/**
		 * Get lastAccessIp
		 *
		 * @return string $lastAccessIp
		 * @VirtualProperty
		 */
		public function getLastAccessIp()
		{
			return $this->lastAccessIp;
		}

		/**
		 * Set lastAccessIp
		 *
		 * @param string $lastAccessIp
		 *
		 * @return User
		 * @VirtualProperty
		 */
		public function setLastAccessIp($lastAccessIp)
		{
			$this->lastAccessIp = $lastAccessIp;

			return $this;
		}
	}

**Comment by Soullivaneuh** [comment]
To add new fields on API, you must read FOSRestBundle documentation. This is not directly related to this bundle.

Thanks.

**Comment by edouardkombo** [comment]
For those who will search before, you just have to extend the FOSUserBundle serializer options setted here:

Resources/config/serializer/FOSUserBundle/Model.User.xml

Thanks
