### ISSUE TITLE
AdminLTE theme user list

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataUserBundle#609]
Would be nice to have a custom list for user using AdminLTE theme:

![adminlte_last_users](https://cloud.githubusercontent.com/assets/1698357/9108126/57b44f8c-3c2c-11e5-944b-c0ba9fb4f089.png)

**Comment by rande** [comment]
This can be done by customizing the mozaic mode

**Comment by Soullivaneuh** [comment]
Yeah but why not propose this one as default?

**Comment by Soullivaneuh** [comment]
BTW, do we have some docs about mosaic customization?

**Comment by eko** [comment]
Gravatar API (https://fr.gravatar.com/site/implement/images/php/) could also be implemented really easily in a first time to retrieve a user / e-commerce customer picture using its email address and then add the possibility to store a user picture.

**Comment by benrcole** [comment]
@Soullivaneuh  there is some:
https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_customizing_a_mosaic_list.html

**Comment by Soullivaneuh** [comment]
> Gravatar API (https://fr.gravatar.com/site/implement/images/php/) could also be implemented really easily in a first time to retrieve a user / e-commerce customer picture using its email address and then add the possibility to store a user picture.

@eko you can open another issue for this. :+1:
