### ISSUE TITLE
Error on /login page

### ISSUE THREAD

**Issue by pim** [sonata-project/SonataUserBundle#612]
Hey,

I'm trying to set up the bundle. I checked a few times and I think I've done everything according to [the instructions](https://sonata-project.org/bundles/user/master/doc/reference/installation.html).

However, when I visit my /login page I get this error:

```
Error: Call to a member function getUser() on null

in vendor/sonata-project/user-bundle/Controller/AdminSecurityController.php at line 26
```

The line that is mentioned is this:

```
$user = $this->container->get('security.context')->getToken()->getUser();
```

So it seems that `getToken()` is null which is right, because there's no user logged in yet. Is there anything I can do about it? Any help is appreciated.

My Symfony version is 2.7.3.

**Comment by fidelio314** [comment]
Hi any news on this "issue"?

**Comment by greg0ire** [comment]
I guess access should be denied before even accessing this line, right? What version of the bundle do you use? Can you link to the offending line on github?

**Comment by fidelio314** [comment]
yep it was just a secirity.yml issue.

**Comment by greg0ire** [comment]
Closing then.
