### ISSUE TITLE
Bundle crashes with Symfony 2.7

### ISSUE THREAD

**Issue by eduardoconceicao** [sonata-project/SonataUserBundle#615]
Hey guys,

I have a project built with symfony 2 framework that uses several sonata bundles. One of them is the SonataUserBundle. Apart from that we use FOSUserBundle in the project too.

After i update the symfony version to the newest 2.7, i've got crashes edit users from sonata admin bundle. After an investigation i realised that the FOSUserBundle version (1.3) is not compatible with new symfony version.

The problem is that i cannot update FOSUserBundle because SonataUserBundle has a dependency of 1.3 version of FOSUserBundle.

At the moment i think that are only 2 options for me:
- Downgrade symfony back to 2.6.\* version. (But i don't want to have symfony in 2.6 version forever...)
- Develop a new version of SonataUserBundle to be compatible with 2.0 version.

Are you guys already thinking in updating SonataUserBundle in order to depend on FOS 2.0 version? I will be happy if i can contribute you that

**Comment by rande** [comment]
There is a work in progress to add support with the FOS 2.0 branch, hower FOS 2.0 is not stable yet.

Also the sonata demo is running with Symfony 2.7 with FOS 1.3 with out any issues.

**Comment by eduardoconceicao** [comment]
Is that work in progress available to use? FOSUserBundle is referencing things that no longer exist in symfony 2.7.

Thanks

**Comment by eduardoconceicao** [comment]
@rande Can i use that WIP branch?

**Comment by eduardoconceicao** [comment]
@rande After digging into the code and researching about it i've found that FOSUserBundle 1.3.6 version fixed this.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/v1.3.6/Changelog.md

Thanks

**Comment by jordisala1991** [comment]
Issue is solved, this can be closed
