### ISSUE TITLE
remove group does not remove assigned roles

### ISSUE THREAD

**Issue by remoteclient** [sonata-project/SonataUserBundle#617]
I use Sonata admin and user bundle in combination with fos user bundle.

For convenience I group different roles to groups and assign them to users. I think sonata just take the roles from the groups and assign them to the users.

When I remove one group from a user the group gets removed but the containing roles are assigned to the user furthermore.

The expected behavior should be that all roles which are in this removed group and are not present in other groups which are assigned to the user are removed from the user.

**Comment by core23** [comment]
Can you please check this against the latest stable / master version? 

Feel free to provide a PR to fix this.

**Comment by jordisala1991** [comment]
Just tried this. It works as expected.

You define a group with some roles. Assign it to a user. Try if the user has those permissions. -> User has the persmissions.

Remove the groups. Check user permissions -> User does not have the permissions on the group removed.

Closing for now. If you still having this issue, please ping me  and provide more information, and we will reopen.
