### ISSUE TITLE
Separate admin password resetting

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataUserBundle#618]
Currently I am working on a project, where there is no frontend login, only admin. It would be great if resetting the password would be available for admin only as well. I am happy to provide a PR if you like the idea.

**Comment by OskarStark** [comment]
absolutely!

we would appreciate this PR :+1: 

let me know if you need help and don't forget, that SonataUser currently only works with FOS 1.3

**Comment by sagikazarmark** [comment]
One thing that is in my mind: currently the resetting routes are duplicated in `sonata_resetting_1.xml`: there is one with a fos_ prefixed version and one with a sonata_user_ prefixed version. Are there any reasons for that? Those can't be duplicated in the admin resetting routes as there would be an id collision. So I would just prefix routes with sonata_admin_ eg: sonata_admin_resetting_request

**Comment by sagikazarmark** [comment]
And one more thing: looking at the front-end reset container: it extends the core FOSUser resetting controller and overrides the templates by inheritance. In this case the controller itself must be overrided as well, as the template names are hardcoded.

One possible solution is to create one base resetting controller with option to override the templates and extend that in the Front-end and the admin resetting controller. This means three controllers instead of two, but I think it is more elegant.

**Comment by OskarStark** [comment]
IMO you should just prefix the routes like login and logout for example

@rande @Soullivaneuh can someone please provide some help with the controller stuff?

**Comment by sagikazarmark** [comment]
I implemented the feautre, see the relevant PR.
