### ISSUE TITLE
Admin login bad redirection for already logged in user

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataUserBundle#619]
When a user is already logged in and goes to `/admin/login` it should redirect to the dashboard. Instead it redirects to the profile page which is not just illogical (since you want to go to the dashboard), but also bad: in case frontend login is not allowed, it ends up with an error saying route `sonata_user_profile_show` cannot be found (in case frontend routes are not set).

**Comment by sagikazarmark** [comment]
The problem is in the AdminSecurity controller, it redirects to / instead of the dashboard. Also, wouldn't it be better to check already logged in user by using `$this->get('security.context')->isGranted('IS_AUTHENTICATED_FULLY')` instead of the current solution (checking the token for an available user object)?

**Comment by OskarStark** [comment]
i think i have the same problem when logging out from the admin area, can you reproduce it?

it goes to ```/``` and i would recommend to link to ```/admin/login```

**Comment by sagikazarmark** [comment]
Actually the logout is handled by the SecurityBundle. Try adding `target: /admin/dashboard` to the `logout` section of `admin` firewall, it should resolve the problem. I think you can also use `sonata_admin_dashboard`. I would rather redirect to the dashboard, not the login page.

**Comment by OskarStark** [comment]
Thank you i will try this!
