### ISSUE TITLE
Already logged in checks

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataUserBundle#627]
Currently login checks are done the following way: The token is fetched from the SecurityContext and if it is an instance of UserInterface (from FOSUserBundle).

The most common way is to check the security context for the role `IS_FULLY_AUTHENTICATED`.

In some cases it might worth to check if the Token holds an instance of UserInterface, but in most cases I don't think it is necessary, checking the special login role is enough.

/cc @rande

**Comment by core23** [comment]
Can you provide a PR @sagikazarmark ?

**Comment by OskarStark** [comment]
Closed via #869
