### ISSUE TITLE
Error: Maximum function nesting level of '250' reached, aborting!

### ISSUE THREAD

**Issue by pabarrientos** [sonata-project/SonataUserBundle#632]
on route /profile

Stack Trace
in vendor\sonata-project\user-bundle\Block\ProfileMenuBlockService.php at line 61   + 
at AbstractBlockService ->setDefaultSettings () 
in vendor\sonata-project\user-bundle\Block\ProfileMenuBlockService.php at line 63   + 
at ProfileMenuBlockService ->configureSettings () 
in app\cache\dev\classes.php at line 4616   + 
at AbstractBlockService ->setDefaultSettings () 
in vendor\sonata-project\user-bundle\Block\ProfileMenuBlockService.php at line 63   + 
at ProfileMenuBlockService ->configureSettings () 
in app\cache\dev\classes.php at line 4616   + 
at AbstractBlockService ->setDefaultSettings () 
in vendor\sonata-project\user-bundle\Block\ProfileMenuBlockService.php at line 63   + 
at ProfileMenuBlockService ->configureSettings () 
in app\cache\dev\classes.php at line 4616   + 

...

**Comment by OskarStark** [comment]
ping @sagikazarmark 

Can you please have a look?

**Comment by OskarStark** [comment]
Refs #628

**Comment by Soullivaneuh** [comment]
Fixed in #630.

**Comment by pabarrientos** [comment]
thanks for fix!!!
