### ISSUE TITLE
Apply #626 to the 2.2 branch and tag 2.2.5

### ISSUE THREAD

**Issue by aderuwe** [sonata-project/SonataUserBundle#635]
As requested by @OskarStark.

I figure that the same as in #626 should be applied to the 2.2 branch, as it is essentially a bug fix. (See also 331d1d0)

Ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
As 2.2 is the last stable branch, I see no problem for doing that.

Feel free to submit a PR.

**Comment by aderuwe** [comment]
#636 was merged.
