### ISSUE TITLE
Can't update roles with group roles!!

### ISSUE THREAD

**Issue by hieuit7** [sonata-project/SonataUserBundle#646]
I have configured with security.yml file 
security:
  role_hierarchy:
    ROLE_USER_NIV_1:  
            - ROLE_SONATA_ADMIN
            - ROLE_VOYAGE_ADMIN_VOYAGESTEP_EDITOR
            - ROLE_VOYAGE_ADMIN_VOYAGE_EDITOR
            - ROLE_VOYAGE_ADMIN_VOYAGE_LIST
            - ROLE_VOYAGE_ADMIN_VOYAGE_EDIT
            - ROLE_VOYAGE_ADMIN_VOYAGE_CREATE
When i check in admin to set  ROLE_USER_NIV_1 for a user. 
After update it, i remove this role, but it can't remove!!
Please help

**Comment by brossdu** [comment]
Got the same issues here ! 
Someone find the issue or a workaround ?

**Comment by hieuit7** [comment]
I have a solution for this. 

I created a group with role_user_niv_1include some roles, and create another group with role_user_niv_2 include some roles. And now, i added some users to group one, and some user to group two. and some user to both groups. It's working with me.

**Comment by jordisala1991** [comment]
User found a solution. And I use my own defined roles without any problem. Without more info of the issue, I close it.
