### ISSUE TITLE
SonataUserBundle no longer compatible with Symfony less then 2.7

### ISSUE THREAD

**Issue by xaben** [sonata-project/SonataUserBundle#648]
The latest commits use a Symfony 2.7 only perk - the shorthand of getParameter() in [here](https://github.com/sonata-project/SonataUserBundle/blob/master/Controller/AdminSecurityController.php#L79). Not sure about other places, but this was an unpleasant surprise and should be fixed asap.

The perk was introduced in symfony 2.7 only and should not be used in projects that support lower versions. Here is the description: http://symfony.com/blog/new-in-symfony-2-7-productivity-improvements

**Comment by xaben** [comment]
@Soullivaneuh

**Comment by OskarStark** [comment]
ping @core23

**Comment by DevMaster112** [comment]
Can confirm this issue. Since the latest commit the login form is not working anymore with symfony 2.6.x! please fix this asap.

**Comment by core23** [comment]
Thank you @xaben 

Should be fixed with #649
