### ISSUE TITLE
Unable to override templates / form types with latest change

### ISSUE THREAD

**Issue by weberdominik** [sonata-project/SonataUserBundle#655]
Since the latest commit for 3.0 compatibility it is not possible to override registration/profile form types anymore, because they seem to be hard coded & my configuration is ignored (see my comment here https://github.com/sonata-project/SonataUserBundle/commit/c6aeda90aa3fcd23ab9abd10e11ac2b6c5caa296).

If i remove the registerFormTypeMapping part everything works as expected again. I am using Symfony 2.8.

**Comment by weberdominik** [comment]
You need to update the core bundle.

**Comment by OskarStark** [comment]
thank you for the answer and closing this PR @weberdominik
