### ISSUE TITLE
Argument 1 passed to Symfony\Component\Form\Extension\Core\Type\ChoiceType::normalizeLegacyChoices() must be of the type array, null given

### ISSUE THREAD

**Issue by muhammadtaqi** [sonata-project/SonataUserBundle#660]
I have added some new field to group class. After that on Sonata admin side, When i want to add new user , it prompts me below error.

```
Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\Extension\Core\Type\ChoiceType::normalizeLegacyChoices() must be of the type array, null given, called in /var/www/html/pnc-mis/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php on line 266 and defined
```

and if figure out in useradmin class.

``` php
->add('groups', 'sonata_type_model', array(
                'required' => false,
                'expanded' => true,
                'multiple' => true
            ))
```

when i remove the above code, it works but groups options are not displayed.  What's wrong with above?  is there anything i should do after adding some custom fields in group class. the fields are `description`, `is_locked` etc.

**Comment by 3mg** [comment]
I have the same error. It appeared after migrating to symfony 2.8.

Problem is in SonataAdminBundle
https://github.com/sonata-project/SonataAdminBundle/commit/2cefe04cd787838a414f947490965dfeeb689e40

**Comment by 3mg** [comment]
If you using a custom UserAdmin class, you can hotfix it by adding 'choices' => array(), option

->add('groups', 'sonata_type_model', array(
                    'required' => false,
                    'expanded' => true,
                    'multiple' => true,
                    'choices' => array(),
                ))

**Comment by seltzlab** [comment]
Same error is happening with SF 2.7.8 too (Sonata Admin Bundle 2.3.7, Sonata User Bundle 2.2.4)
You can also make it works changing 'sonata_type_model' to null, groups will appear

**Comment by jordisala1991** [comment]
This issue is too old and without more information it is hard to track. Probably not related to userbundle. Closing
