### ISSUE TITLE
Parameter "id" for route "admin_sonata_user_user_edit" must match "[^/]++" ("" given) to generate a corresponding URL.

### ISSUE THREAD

**Issue by xmon** [sonata-project/SonataUserBundle#663]
Hi,

I'm trying some actions after create a user.

this in Admin class, src\Application\Sonata\UserBundle\Admin\UserAdmin.php

``` php
/**
 * {@inheritdoc}
 */
public function create($object)
{
    parent::create($object);

    // do something
}
```

when click on Create, the user is succesfully created, but:
**Parameter "id" for route "admin_sonata_user_user_edit" must match "[^/]++" ("" given) to generate a corresponding URL.**

Any idea to solve it?

**Comment by czarra** [comment]
Problem is in Symfony\Component\Routing\Generator\UrlGenerator.php

I commented out lines 174 -186

if (null !== $this->strictRequirements && !preg_match('#^'.$token[2].'$#', $mergedParams[$token[3]])) {
                        $message = sprintf('Parameter "%s" for route "%s" must match "%s" ("%s" given) to generate a corresponding URL.', $token[3], $name, $token[2], $mergedParams[$token[3]]);
                        if ($this->strictRequirements) {
                            throw new InvalidParameterException($message);
                        }

                        if ($this->logger) {
                            $this->logger->error($message);
                        }

                        return;

**Comment by czarra** [comment]
You can in config_dev.yml.
You have to change strict_requirements: true on
strict_requirements: null

**Comment by xmon** [comment]
Thanks a lot, I will try it.

**Comment by OskarStark** [comment]
@xmon does it work?

**Comment by cassianotartari** [comment]
> I'm trying some actions after create a user.

Why don't you simply extends ``postPersist``?
