### ISSUE TITLE
admin_resetting.xml missed

### ISSUE THREAD

**Issue by crazy-genius** [sonata-project/SonataUserBundle#669]
Set config for Sonata to:  
"sonata-project/admin-bundle": "2.3.7",
 "sonata-project/doctrine-orm-admin-bundle": "2.3.3",
 "sonata-project/user-bundle": "2.2.4",
And after composer update . I've got error con't load admin_resetting.xml file.

I'm fix only by manualy set git version of sonata-project/user-bundle to origin/master

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
