### ISSUE TITLE
Save last logout time of user

### ISSUE THREAD

**Issue by taqiofficial** [sonata-project/SonataUserBundle#675]
I have to Save User login and logout history, I get the last login or in loginsuccess handler. but how do i get the user logout datetime. it's only logout success handler, in which i have no access of whom is logout?

**Comment by muspelheim** [comment]
you can add to your security.yml
```yml
    logout:
        success_handler: my.logout_success_handler
```

**Comment by jordisala1991** [comment]
Is this still an issue?

**Comment by taqiofficial** [comment]
@jordisala1991 What do you mean by still an issue? does sonata added this field to user's entity now or ?

**Comment by jordisala1991** [comment]
I mean, does that proposed solution works for you?

**Comment by taqiofficial** [comment]
@jordisala1991 , Yes it works.

**Comment by jordisala1991** [comment]
Then I close this one.
