### ISSUE TITLE
Redirect issue on edit profile page

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataUserBundle#679]
There is a strange bug when submitting forms on the edit profile page (http://demo.sonata-project.org/profile/edit-profile). The page has three forms which behave completly different because each template includes other pages.

When submitting the **User Profile** form - everything is fine
When submitting the **Authentication** form - the first form is gone
When submitting the **Change your password** - all other forms are gone

**Comment by stphnpt** [comment]
"edit_profile.html.twig":
**extends "SonataUserBundle:Profile:action.html.twig"**
renders "edit_authentication.html.twig"

"edit_authentication.html.twig":
renders "changePassword.html.twig"

"changePassword.html.twig":
**extends "SonataUserBundle:Profile:action.html.twig"**

**Comment by core23** [comment]
Can you say something more to this @stphnpt

**Comment by stphnpt** [comment]
when using {% render url("sonata_user_change_password") %} in edit_profile template, the template to be used shall be "SonataUserBundle:ChangePassword:changePassword**_content**.html.twig" (not "SonataUserBundle:ChangePassword:changePassword.html.twig" to avoid extension of "SonataUserBundle:Profile:action.html.twig" twice)
