### ISSUE TITLE
How to install with sf3 ?

### ISSUE THREAD

**Issue by epci** [sonata-project/SonataUserBundle#681]
i have a problem with composer dependencies when i try to install with sf3

this is my composer require : 

  "require": {
    "php": ">=5.5.9",
    "symfony/symfony": "3.0.*",
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-cache-bundle": "^1.2",
    "symfony/swiftmailer-bundle": "^2.3",
    "symfony/monolog-bundle": "^2.8",
    "sensio/distribution-bundle": "^5.0",
    "sensio/framework-extra-bundle": "^3.0.2",
    "incenteev/composer-parameter-handler": "^2.0",
    "sonata-project/admin-bundle": "dev-master",
    "sonata-project/user-bundle": "dev-master",
    "sonata-project/datagrid-bundle": "dev-master",
    "sonata-project/doctrine-orm-admin-bundle": "dev-master",
    "symfony/security-bundle": "dev-master",
    "friendsofsymfony/user-bundle": "dev-master",
    "symfony/security-acl": "dev-master"
  },

and this is the result : 

  Problem 1
    - Installation request for sonata-project/user-bundle dev-master -> satisfiable by sonata-project/user-bundle[dev-master].
    - Can only install one of: friendsofsymfony/user-bundle[dev-master, 1.3.x-dev].
    - sonata-project/user-bundle dev-master requires friendsofsymfony/user-bundle ~1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev].
    - Installation request for friendsofsymfony/user-bundle dev-master -> satisfiable by friendsofsymfony/user-bundle[dev-master].

how i can fix this prob ?

**Comment by rande** [comment]
the current master does not support sf3.0, You can try this branch: https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2 however the support is not over. Feel free to send PRs or feedbacks

Thanks
