### ISSUE TITLE
Error with mopa

### ISSUE THREAD

**Issue by adrian410** [sonata-project/SonataUserBundle#685]
Hi,

I'm starting a new project with symfony 2.8. I installed sonata user bundle.
It's works great except i get an error on the route "profile/edit-authentication" :
"Variable "render_fieldset" does not exist in MopaBootstrapBundle:Form:fields.html.twig at line 113"
After i log on.

Before this error i got another one saying that it couldn't find the template of Mopa. 
It was because i didn't installed MOPA. So i got it with composer and i added it to the AppKernel.

Did i miss something ?

Thanks.

**Comment by fussl** [comment]
Same issue here. :-(

**Comment by Apoill19** [comment]
Hi,

I had the same issue and I've just find the soluce. In **config.yml**, you have to set _mopa_bootstrap_ like that : 

**_mopa_bootstrap:
    form: ~_**

It's ok for me with that.

I hope it could help you.

**Comment by Soullivaneuh** [comment]
This issue is related to MopaBootstrapBundle.
