### ISSUE TITLE
Getting errors because of API code bundle needs

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataUserBundle#686]
Hey,

I have `"sonata-project/user-bundle": "^2.2"` in my composer.json. 
I do not plan to use any type of API component. When I do `composer update`  I get this:

```
[Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\UserBundle\Controller\Api\GroupController::getGroupsAction() does not exist, or could not be auto-loaded.


Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception



  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Doctrine\Common\Annotations\AnnotationException]
    [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\UserBundle\Controller\Api\GroupController::getGroupsAction() does not exist, or could not be auto-loaded.

  .
```

Do I need to install & configure FOSRestBundle and NelmioApiDocBundle? Is this something that you are forcing users to do???

**Comment by core23** [comment]
Hi,

for the 2.2 version of the this bundle, the dependency is requires. In the current master, the ApiBundle is removed (https://github.com/sonata-project/SonataUserBundle/pull/650).

**Comment by AntonioCS** [comment]
Thanks. I will change to dev-master in the composer.json.

**Comment by core23** [comment]
Be aware of using the master version, because you are using a bleeding edge version. This should not be used for a production environment.

**Comment by AntonioCS** [comment]
Right. Any version that I can use that does not have this bundle issue?

**Comment by core23** [comment]
I see, there was a new release. You could use version 2.2.4.

**Comment by AntonioCS** [comment]
Changed to 2.2.4, did composer update and got this:

`PHP Fatal error:  Declaration of Sonata\UserBundle\Block\AccountBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /var/www/mylocalpitch/rc_mlp_20140609/vendor/sonata-project/user-bundle/Block/AccountBlockService.php on line 110`

**Comment by core23** [comment]
Can you show your composer config? @AntonioCS

**Comment by kaiwa** [comment]
I am experiencing the same problem, but I don't think it's SonataUserBundle's fault in my case. I am using the master branch, the api controllers do not get loaded by SonataUserBundle, which is correct, but for some reason JMSDiExtraBundle loads the controllers anyway (or at least they are not loaded if I disable JMSDiExtraBundle) and therefore it comes to the same exception as OP's initial one.

Something is fucked up since i explicitly configured

```
jms_di_extra:
    locations:
        all_bundles: false
```

I guess this is the point when magic starts kicking your butt :-/

**Comment by gremo** [comment]
I have the same problem: using JMSDiExtraBundle without NelmioApiDocBundle.

Maybe the problem relies  in the  [cache warmer](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/HttpKernel/ControllerInjectorsWarmer.php#L49) scanning all bundles folders and looking for controllers (note that `all_bundles: false` is ignored).

It works if you disable the warmer:

```yml
jms_di_extra:
    cache_warmer:
        enabled: false
```

There is a [blacklist option](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/DependencyInjection/Configuration.php#L41) but it relies on the controller realpath.

What about prepending the blacklist option if JMSDiExtraBundle is found but NelmioApiDocBundle not?

**Comment by greg0ire** [comment]
> I can work on a PR.

Amazing work. Please do!

**Comment by kaiwa** [comment]
@gremo Nice workaround. But I guess it would be preferrable if this would be fixed in JmsDiExtraBundle itself, so that `all_bundles: false` is working correctly. Maybe better put your effort into an PR over at https://github.com/schmittjoh/JMSDiExtraBundle ? Anyway, looking forward to a solution :)

**Comment by gremo** [comment]
@kaiwa I agree, but a PR (shouldn't hard to write) on JMSDiExtraBundle could take months to be accepted. In addition we have BC to older version of JMSDiExtraBundle.

**Comment by greg0ire** [comment]
Did someone report the bug to `JMSDiExtraBundle` ?

> In addition we have BC to older version of JMSDiExtraBundle.

I think we can drop older versions if it's not a major version we're dropping.

**Comment by kaiwa** [comment]
> Did someone report the bug to JMSDiExtraBundle ?

Yes I did, here you go:

https://github.com/schmittjoh/JMSDiExtraBundle/issues/248

**Comment by gremo** [comment]
I just opened a new one https://github.com/schmittjoh/JMSDiExtraBundle/issues/269 and I'm sending a PR.

**Comment by jordisala1991** [comment]
This seems to be solved, or atleast belongs to JMSDiExtraBundle. If I am wrong ping me and I will reopen
