### ISSUE TITLE
Cant Generate Easy-Extends of SonataUserBundle

### ISSUE THREAD

**Issue by rekursed** [sonata-project/SonataUserBundle#687]
Hi,

i am at the ending stage of installing SonataUserBundle,
When i run,
`app/console sonata:easy-extends:generate SonataUserBundle -d src --dest=src`
i get 

> [Doctrine\Common\Persistence\Mapping\MappingException]  
>   Class 'Application\Sonata\UserBundle\Entity\User' does not exist 

I followed everything according to [This Doc](https://sonata-project.org/bundles/user/2-2/doc/reference/installation.html)

Any idea how to get through it?

**Comment by nlzet** [comment]
I tried this. I think you forgot to load the EasyExtends bundle in your AppKernel. If you did this you should be able to run the easy-extends, following this documentation: https://sonata-project.org/bundles/user/2-2/doc/reference/installation.html

**Comment by jordisala1991** [comment]
Is this still an issue? Looks like you configured to use Application classes **before** generating them with easy-extends
