### ISSUE TITLE
[v2.2.4] Unable to find file admin_resetting.xml

### ISSUE THREAD

**Issue by ivangabriele** [sonata-project/SonataUserBundle#696]
Hi,

I just installed SonataUserBundle and got this exception :

```
Unable to find file "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
in @SonataUserBundle/Resources/config/routing/admin_resetting.xml (which is being imported
from "C:\Users\ivang\Workspace\monetys\app/config\routing.yml"). Make sure the
"SonataUserBundle/Resources/config/routing/admin_resetting.xml" bundle is correctly registered
and loaded in the application kernel class. If the bundle is registered, make sure the bundle
path "@SonataUserBundle/Resources/config/routing/admin_resetting.xml" is not empty.
```

I confirm the file is missing under last version `2.2.4` as seen here : https://github.com/sonata-project/SonataUserBundle/tree/2.2.4/Resources/config/routing

This bug was reported on SO too: http://stackoverflow.com/questions/35541894/unable-to-find-file-sonatauserbundle-resources-config-routing-admin-resetting

Either the [documentation](https://sonata-project.org/bundles/user/master/doc/reference/installation.html#integrating-the-bundle-into-the-sonata-admin-bundle) has not been updated (which I don't think so since this file is present on the master branch), or it's just a major issue for this specific version.

**Comment by aivus** [comment]
Version 2.2.4 was released in 14.02.2014.
File `admin_resetting.xml` was added in September 2015.

Your documentation link for master version.
Please, visit [documentation for 2.2.4 version](https://sonata-project.org/bundles/user/2-2/doc/reference/installation.html#integrating-the-bundle-into-the-sonata-admin-bundle).

**Comment by OskarStark** [comment]
Thank you for the feedback @aivus :+1:

**Comment by ivangabriele** [comment]
Thank you @aivus :)
