### ISSUE TITLE
to convert user entity to string

### ISSUE THREAD

**Issue by pajooh** [sonata-project/SonataUserBundle#70]
trying to see admin dashboard, i get the following:

An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Symfony\Component\Security\Core\User\User could not be converted to string in /home/pajooh/web/app/cache/dev/twig/67/b2/dee9cd5a99bf1b282fb737c319bd.php line 24") in SonataUserBundle:Admin/Core:user_block.html.twig at line 1. 

the problem is that in the user_block.html.twig, the {{ app.user}} can not be converted to string.

**Comment by hal9087** [comment]
+1 ... so it's not possible to use in_memory user provider to login into the admin area?
