### ISSUE TITLE
Notice: Undefined index: choice_list [SF3, FOSUSER2]

### ISSUE THREAD

**Issue by Mangetsu** [sonata-project/SonataUserBundle#704]
It seems my SonataUserBundler UserAdmin breaks when trying to render the group field list.
![capture](https://cloud.githubusercontent.com/assets/8430081/13666461/8d2d89f8-e6a9-11e5-8af6-0cfadd841f16.PNG)

When i remove Groups Field from the FormBuilder of UserAdmin, the edit form shows up (obviously without Groups)

here is my composer.json : 

"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/security-acl": "^3.0",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "dev-master",
        "sonata-project/user-bundle": "dev-add_support_for_fos_user2@dev",
        "sensio/generator-bundle": "^3.0"
    },

**Comment by greg0ire** [comment]
Looks like there should be a `choice_loader` option but there is none.

**Comment by Mangetsu** [comment]
@greg0ire : i didn't customize anything in User nor Group entities, i just used easy-extend to get the Application bundle from SonataUserBundle, no extra fields or nothing, and this show's up, another weird thing is that the doctrine keeps creating 2 differents tables for the Group Entity, one called groups (from Application/Sonata....) and another one fos_user_user_group (always empty).

here's my fos config : 
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager


btw to avoid some incompatibility issues i added 2 alias for FOS deprecated services:
# Fix FOSUserBundle issue
    fos_user.doctrine_registry:
        alias: doctrine

    fos_user.entity_manager:
        alias: fos_user.object_manager

**Comment by greg0ire** [comment]
This branch is a work in progress, you know? If you want to contribute a fix, you should read and apply [this](https://symfony.com/doc/current/cookbook/debugging.html#cookbook-debugging-disable-bootstrap)

**Comment by Mangetsu** [comment]
I found the issue source it's the fact that the ModelType and the ModelsToArrayTransformer from SonataAdminBundle wasn't up to date with the new choice_loader issue please look at this pull request for details:
https://github.com/sonata-project/SonataAdminBundle/pull/3645

**Comment by greg0ire** [comment]
Please use good commit messages : http://rakeroutes.com/blog/deliberate-git/ "update file.txt" is paraphrasing.

**Comment by Mangetsu** [comment]
@greg0ire : i've edited the files using github browser editor, since I'm at work and i don't even have the right to be here.
i just wanted to help since maybe someone else is stuck with the same issue.

**Comment by greg0ire** [comment]
Ok, could you rework this at home when you have the time?

**Comment by Mangetsu** [comment]
@greg0ire : I've updated the pull request as requested :)
