### ISSUE TITLE
Security Tab fields in UserAdmin not showing

### ISSUE THREAD

**Issue by ejkun** [sonata-project/SonataUserBundle#706]
I was having a problem with my user security, the Security Tab wasn't showing all the fields. Looking in the files I found this line in the [UserAdmin](https://github.com/sonata-project/SonataUserBundle/blob/master/Admin/Model/UserAdmin.php)

`if ($this->getSubject() && !$this->getSubject()->hasRole('ROLE_SUPER_ADMIN')) {`

Which means that any user, that it's not a SUPER_ADMIN, have full access to the Security Tab.
IMO the right would be:

`if ($this->getSubject() && $this->getSubject()->hasRole('ROLE_SUPER_ADMIN')) {`
without the `!`

I'm right on this? Or I'm missing something?

**Comment by greg0ire** [comment]
First, you can link to a line directly [like this](https://github.com/sonata-project/SonataUserBundle/blob/master/Admin/Model/UserAdmin.php#L191). Second, that's really, really strange. Looks like this condition was first introduced by @rande in 3f8e91e1aa0561747242dea7048367f88a79ab73 four years ago. @rande @OskarStark @core23 , do you know why this is like this? If yes, a little comment in the code wouldn't hurt I think.

**Comment by core23** [comment]
IMO this is a security feature, so that super admin can't lock their account or remove admin permissions.

**Comment by greg0ire** [comment]
Oh right!

@ejkun : `getSubject()` is not the current user, it's the user that is being edited. Makes sense. Would you please make a PR adding a comment that clarifies that?

**Comment by ejkun** [comment]
@greg0ire I realized that today at work. I see now that it really works. But that is one case that is at least weird. What if I am a `ROLE_SUPER_ADMIN` and I'm creating a new user that is also a `ROLE_SUPER_ADMIN`? If I do wrong when creating the user, I can't change it. And also, what if I need to take out some roles of a user that was previously a Super Admin? Btw, sorry for the delay, internet problems during the weekend.

**Comment by greg0ire** [comment]
Well if you're a super admin, groups and roles are quite pointless (are they even checked?) but the rest (locked, expired, and so on), not so. Maybe we should remove this check. What do you think @core23 @OskarStark ?

**Comment by ejkun** [comment]
Thank you @core23
