### ISSUE TITLE
Issue with loggin in

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataUserBundle#710]
I have installed the dev-master version of the bundle paired up with FOSUser Bundle 2.0

However, I am unable to login because I get the error below.

`Unexpected "render" tag (expecting closing tag for the "block" tag defined near line 77) in SonataUserBundle:Security:base_login.html.twig at line 77.`

Anyone know how to correct this?

**Comment by muspelheim** [comment]
@marvoh I think, FOSUser 2.0 not capability with SonataUser in develop branch, coz composer have this: friendsofsymfony/user-bundle: "~1.3",

**Comment by Soullivaneuh** [comment]
The stable part of this bundle is not yet compatible with FOSUser v2.

It will be changed when FOSUser v2 will be stable.
