### ISSUE TITLE
composer.json wrong require?

### ISSUE THREAD

**Issue by bschmithuysen** [sonata-project/SonataUserBundle#721]
Could you please add SonataAdminBundle 3.x-dev?
I think 2.4 is no longer available?

`sonata-project/admin-bundle": "~2.3|~2.4@dev`

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataUserBundle/pull/722

**Comment by Soullivaneuh** [comment]
See https://github.com/sonata-project/SonataUserBundle/issues/730
