### ISSUE TITLE
Impossible to use the SonataUserBundle dev-master with SonataAdminBundle 2.3.10?

### ISSUE THREAD

**Issue by ejkun** [sonata-project/SonataUserBundle#729]
I'm using SonataUserBundle dev-master with SonataAdminBundle 2.3.10 and the login page won't render. I'm getting this error.

`Variable "sonata_admin" does not exist in SonataUserBundle:Admin:Security/login.html.twig at line 19`

First I looked into the latest commits. There was a commit that changed the adminpool variable inside the template. I changed it back, now it works. But the design is wrong. And the html code is a different from the normal. Here is a print:
![sonata_login_page](https://cloud.githubusercontent.com/assets/7905944/15193109/a68accd4-1792-11e6-91f2-654b4c129661.png)

I'm thinking that in some point beetween SonataAdmin 2.3.10 and dev-master the `sonata_admin` global variable was removed and the base_template changed.

Can anyone help me solve this?

**Comment by ejkun** [comment]
I really don't know what happened. Probably a cache problem or something like that. It worked now. With the layout bugged I logged in, then logged out, and everything was normal.

But I still have to change the `sonata_admin.adminPool` to `admin_pool` and I still think that the right would be using `admin_pool`.

**Comment by greg0ire** [comment]
> in some point

Maybe you could find the commit with `git bisect` ?

**Comment by ejkun** [comment]
Sure, but I don't think that's the problem. Check these [lines](https://github.com/sonata-project/SonataUserBundle/blob/619f64ae6eda66458dbbddea952760a79bb79140/Resources/views/Admin/Security/login.html.twig#L19-L26). I the `admin_pool` variable (which is given by the controller) was changed to `sonata_admin.adminPool` (that is a global variable). The changes on these lines were made on a [commit](https://github.com/sonata-project/SonataUserBundle/commit/619f64ae6eda66458dbbddea952760a79bb79140#diff-2e5875f4978e2b95e6a2174de395950e) which only objective was to show the company logo.

And I just realized that the AdminLTE Theme changed. Maybe the change broke the layout? I will make some tests here to see if that is the problem.

**Comment by greg0ire** [comment]
> which only objective was to show the company logo.

There should have been two commits indeed, that's really fishy.

**Comment by ejkun** [comment]
So, about the AdminLTE Theme. There was indeed a change. The CSS rules that were being used no longer exists.

**Comment by greg0ire** [comment]
I remember having problems with this bundle too, and ended up using a fixed commit as a version constraint for the user bundle. Very ugly, but I had no real choice…

**Comment by ejkun** [comment]
Apparently, SonataAdmin is using AdminLTE 1.2. The only branch with the 2.x version is the SonataAdmin 3.x. Which I can't use because SonataUserBundle dev-master only accept SonataAdmin ~2.3 ou ~2.4@dev (this one don't exist anymore). So now I'm going to SonataAdmin repository to see what I can do.

**Comment by greg0ire** [comment]
You can alias 3.0 to 2.4@dev, can't you ?

**Comment by ejkun** [comment]
Yes, but I need to check some more, there are other dependencies that I would need to change. I will try this tomorrow. Going to live this issue open until we figure out the `admin_pool` problem.

**Comment by Soullivaneuh** [comment]
You can now directly use user-bundle 3.x-dev that is composer comptabile with admin-bundle 3.0.
