### ISSUE TITLE
Version upgrade plan

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataUserBundle#730]
I discussed with @rande about the user-bundle problematic.

### Actual state

The last stable version of user-bundle is `2.2.4`.
Several un-tagged commits are present on 2.2 branch: https://github.com/sonata-project/SonataUserBundle/compare/2.2.4...2.2

We have two branch without any stable tag:

* `2.3`
* master that is also aliased to `2.3.x`. Don't ask me why, I don't know.

For the moment, user-bundle is compatible with FOSUserBundle `1.x` stable.

### The plan

We won't get the risk to release a `2.3` stable version without being sure this one is BC with `2.2`.
Why? Simply because we will drop `2.x` support just after that (like core-bundle and admin-bundle)

Here is the steps of the elaborated plan:

- [x] Push a last version of `2.2`, `2.2.5`, to keep un-tagged work. If you was on `2.2.4` and `2.2.5` does not work, simply stay at `2.2.4`.
- [x] Push a `2.x` branch from `2.2`, for keeping the history. Set it to `2.x-dev`
- [x] Remove `2.0`, `2.1` and `2.2` branch. Push tags before, if trailing commits are present.
- [x] Merge `2.3` onto master, and remove it.
- [x] Rework composer and set it to `3.x-dev`
- [x] Prepare and release a `3.0` stable version
- [x] Prepare master for the next major (`4.x`)

### FOSUserBundle 2.0 special case

Lot of people are asking to have a support for FOSUserBundle 2.0.

@rande Tried to get it working here: https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2

But it's apparently too hard to keep both support of 1.x and 2.x.

As FOSUserBundle 2.0 is not stable yet, we **will not** add support of this one, neither for 2.x or 3.x version of our bundle.

For the future, two possible cases:

* If we can keep support for both 1.x and 2.x version of FOSUser, it will be done on next minor (probably 3.1)
* If not, the work for FOSUser 2.x support will be merged and release on a new major **only when** FOSUser 2.0 will be stable

Thanks for your support and your patience.

**Comment by redactuk** [comment]
Thank your for this very positive update. Appreciate all the hard work you guys do. With regarda your final 'two possible cases' for FOSUserbBundle support, I will ask again, has team considered a fork of FOSUserBundle and merge with SonataUserBundle? FOSUserBundle looks pretty dead to me and I fea that continuing to support the now very oudated v1.0 will just cause further problems.

**Comment by greg0ire** [comment]
> FOSUserBundle looks pretty dead to me

Are there any alternatives to this bundle ?

**Comment by Soullivaneuh** [comment]
> FOSUserBundle looks pretty dead to me

Don't be so hard with them, the last commit was done 6 hours ago: https://github.com/FriendsOfSymfony/FOSUserBundle/commit/abb35b94ed8ec78a504c9e1a2cd803d85d3ffad9 ;-)

If you indeed have another bundle that we can support, you can open another issue about that.

But please not that FOSUserBundle is the most used bundle for user management with SF full stack project, and we will not drop the support of this one.

**Comment by OskarStark** [comment]
> Don't be so hard with them, the last commit was done 6 hours ago: FriendsOfSymfony/FOSUserBundle@abb35b9 ;-)

😄

**Comment by redactuk** [comment]
I've no wish to be hard on the individual developers involved - their massive contribution in the past is appreciated by thousands, but progress on a stable 2.0 release has been glacial - nearly 2 years! compare this with awesome release schedule of Symfony core and it just feels like there is no appetite from original developers to continue supporting the bundle. As for alternatives, sadly there are none. Again I find it very strange that such an established framework as Symfony has just one User management bundle out there and one that has received so little attention. Anyway, I guess like thousands of others we'll just have to contimue to force v2.0 compatibility manually as we're no longer prepared to continue to use v1. That or evaluate other admin bundles.

**Comment by Soullivaneuh** [comment]
> compare this with awesome release schedule of Symfony

Two points about this:

* This release schedule was not always awesome as you said. ;-)
* Symfony is managed by SensioLabs that is a company with lot of developers. They must have dedicated time to have a good release process. This is not the case of community only project, as FOSUserBundle or sonata projects. We just can't do the same thing.

> progress on a stable 2.0 release has been glacial - nearly 2 years!

I understand but if no stable version is pushed for now is certainly for a good reason. Stof won't push a release until he is sure of him.

BTW, I opened a ticket for, at least, a new alpha tag: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2128

Wait and see.

> I find it very strange that such an established framework as Symfony has just one User management bundle out there and one that has received so little attention.

It's historical. FOSUserBundle was the first bundle out for Symfony2. Again, this is the community magic.

If one day you found another bundle like this one and want to provide a support of it on sonata user-bundle, feel free!

If you want to create your own FOSUserBundle, fell also free for it! ;-)

**Comment by sagikazarmark** [comment]
The following comment brings up an interesting question:
https://github.com/sonata-project/SonataUserBundle/issues/728#issuecomment-219392177

Sonata projects with the user bundle installed will not support Symfony 3.0?

**Comment by Soullivaneuh** [comment]
Sadly yes, for the moment.

**Comment by sagikazarmark** [comment]
> Sadly yes, for the moment.

Maybe it should be emphasized somewhere? Although it's not really "good marketing", I would expect much more questions/confusions like this.

**Comment by Soullivaneuh** [comment]
Maybe on the installation / introduction doc?

**Comment by peter-gribanov** [comment]
Thank you all. I waiting for this update.
Now we wait for the full support of Symfony 3

**Comment by sagikazarmark** [comment]
> Maybe on the installation / introduction doc?

Yes, somewhere at the beginning.

> Now we wait for the full support of Symfony 3

Sonata works perfectly fine without the User Bundle. You are free to develop your own protection using symfony methods.

**Comment by rande** [comment]
@stof do you have any input for us ?
