### ISSUE TITLE
Unable to install version 2.2.5

### ISSUE THREAD

**Issue by MAXakaWIZARD** [sonata-project/SonataUserBundle#746]
```javascript
"symfony/symfony": "2.8.*",
"sonata-project/core-bundle": "2.3.*",
"sonata-project/admin-bundle": "2.3.*",
"sonata-project/doctrine-orm-admin-bundle": "2.3.*",
"sonata-project/block-bundle": "2.2.*",
"sonata-project/intl-bundle": "2.2.*",
"sonata-project/user-bundle": "2.2.5",
"sonata-project/media-bundle": "2.3.*",
"sonata-project/datagrid-bundle": "dev-master#6e7940a",
"sonata-project/formatter-bundle": "2.3.*",
```

# Error message

```
[Composer\DependencyResolver\SolverProblemsException]                                                                                                                
    Problem 1                                                                                                                                                          
      - The requested package sonata-project/user-bundle 2.2.5 exists as sonata-project/user-bundle[2.3.x-dev, dev-master] but these are rejected by your constraint.  
```
# Expected results
Version `2.2.5` is installed
# Actual results
See error above

**Comment by Soullivaneuh** [comment]
Why command did you use? `2.3.x-dev` does not exist anymore, it should be `2.x-dev`.

Please also note this: https://github.com/sonata-project/SonataUserBundle/issues/730

> Push a last version of 2.2, 2.2.5, to keep un-tagged work. If you was on 2.2.4 and 2.2.5 does not work, simply stay at 2.2.4.

**Comment by MAXakaWIZARD** [comment]
@Soullivaneuh `composer update`

**Comment by MAXakaWIZARD** [comment]
@Soullivaneuh `2.2.4` also does not work `The requested package sonata-project/user-bundle 2.2.4 exists as sonata-project/user-bundle[2.3.x-dev, dev-master] but these are rejected by your constraint.` I've already tried `composer clear-cache`

**Comment by Soullivaneuh** [comment]
Which version of user-bundle is working? Or which composer.json works?

Could you try `composer why-not sonata-project/user-bundle:2.2.5` after installed it successfully?

**Comment by MAXakaWIZARD** [comment]
@Soullivaneuh Seems like issue was in `jms/serializer-bundle` dependency constraint. Now I am able to install `2.2.5` and `2.x-dev#ebf6839`. I will stay on `2.x-dev#ebf6839`, because `2.2.5` has UI broken. Thanks!
