### ISSUE TITLE
FOSUserBundle Events not dispatched by Sonata ?

### ISSUE THREAD

**Issue by Notmarrco** [sonata-project/SonataUserBundle#762]
Hi,

I tried to listen to some FOSUserBundle events, like *REGISTRATION_CONFIRM*, thinking that the SonataUserBundle would fire the same events.

I see in _*FOSUser1Controller_ that it's not the case. Am I doing something wrong and the events are fired nonetheless (and I missed them) or did sonata voluntarily avoid to dispatch these events ? If so why ? Should I override the controller in my AppBundle to do so ?

thx

**Comment by greg0ire** [comment]
Do these events exist in version 1?

**Comment by Notmarrco** [comment]
you're right , that's it, they're only in master for now ..

sorry, I thought I looked everywhere :)

i'm closing the issue.
