### ISSUE TITLE
CustomUserEntity - has a dependency of fos?

### ISSUE THREAD

**Issue by iBasit** [sonata-project/SonataUserBundle#765]
I want to use SonataUserBundle with Custom User entity, but I keep getting following error

> The service "sonata.user.orm.user_manager" has a dependency on a non-existent parameter "fos_user.model.user.class".

Is there any doc on how to implement this with custom entity?

**Comment by ebuildy** [comment]
I think you can create your own services ``fos_user.*``:

https://github.com/sonata-project/SonataUserBundle/search?utf8=%E2%9C%93&q=fos_user&type=Code

And implement the used methods.

**Comment by Soullivaneuh** [comment]
@iBasit Please follow the issue template format.

**Comment by Soullivaneuh** [comment]
Closing for not respected bug report format and no answer from the author.

**Comment by iBasit** [comment]
@ebuildy  Sorry, I just saw this message.

I had problem getting this running on custom entity without using `fos_user`. 

I'm not sure which `fos_user` services needs to be created to cover the initial running stage and also I'm not sure what method will be required for them to run properly. 

We are not using `username` or `canonicalizer` fields. Any help on without the `fos_user` bundle?


@Soullivaneuh  Sorry, I wouldn't be able to replicate  to get all the answers for formatted question, but I will definitely will do on new questions.
