### ISSUE TITLE
friendsofsymfony/rest-bundle 2.0.0 is released, but we have a strict dependency here: "friendsofsymfony/rest-bundle": "^1.1"

### ISSUE THREAD

**Issue by dmitryhiccup** [sonata-project/SonataUserBundle#775]
I need to install friendsofsymfony/rest-bundle v2.0.0, but current composer.json configuration is set to be "friendsofsymfony/rest-bundle": "^1.1" which blocks from installing v2.0.0

**Comment by core23** [comment]
Maybe there are reasons for that? Feel free to create a PR which supports both versions.

**Comment by dmitryhiccup** [comment]
@core23 I'm using friendsofsymfony/rest-bundle separately from sonata-project. I see that it's now optional in https://github.com/sonata-project/SonataUserBundle/blob/3.x/composer.json, but there is a check for it in "conflict", which prevents me to install both SonataUserBundle & the FOSRestBundle

**Comment by Soullivaneuh** [comment]
If there is a conflict, it's because the 2.0 version is not compatible/tested yet.

As @core23 said, we will happy to see a PR making this bundle compatible with both versions.

**Comment by Soullivaneuh** [comment]
BTW:

> friendsofsymfony/rest-bundle 2.0.0 is released

Alpha tags are released, here is the last one: https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-alpha3

But not stable release. We need to support at least one stable release.

I close this issue as this is not "directly" concerning our project.

When FOSUser 2.0 will be stable, we will be able to start the migration.

**Comment by ethernal** [comment]
I think you misread REST bundle for User bundle (since it's a major PITA lately), unless SonataUserBundle depends on FOSUserBundle and that depends on FOSRestBunlde less than 2.0  don't remember atm.

**Comment by Soullivaneuh** [comment]
Indeed, sorry for the mistake! :+1: 

In this case, we will happy to review a PR to support both v1 and v2 of FOSRestBundle (if possible). :wink:

**Comment by AlexandreKilian** [comment]
any news on that? currently using a fork where I just disable the maximum requirement in order for that to work since there are too many other dependencies on fos/rest-bundle 2 to go down to 1.x... for example sensio/framework-extrabundle requires 2.0 for a while now

**Comment by dubfire** [comment]
No news? :(

**Comment by lemorragia** [comment]
+1 on this one. SonataClassificationBundle is also affected by this "^1.1" dependancy.

**Comment by greg0ire** [comment]
There is [an upgrade guide](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/UPGRADING-2.0.md) if anyone wants to give the migration to 2.0 a try. [The two files to migrate are here](https://github.com/sonata-project/SonataUserBundle/tree/3.x/Controller/Api)

**Comment by greg0ire** [comment]
@AlexandreKilian @lemorragia @dmitryhiccup can one of you make a PR that removes the conflict and allows version 2 ? That way we will see if there are unit tests to solve.

**Comment by xabbuh** [comment]
see #802 which makes SonataUserBundle compatible with FOSRestBundle 2.x
