### ISSUE TITLE
Class Sonata\UserBundle\Entity\BaseUser contains 35 abstract methods

### ISSUE THREAD

**Issue by utilisezlinux** [sonata-project/SonataUserBundle#776]
Hi

Sorry if it is not the right place to post but I don't know how to have help otherwise.

I try and install sonata-project/user-bundle with friendsofsymfony/user-bundle. Versions are `"sonata-project/user-bundle": "^2.2"` and `"friendsofsymfony/user-bundle": "^1.3"`. 
I keep having this error 

```
Fatal error: Class Sonata\UserBundle\Entity\BaseUser contains 35 abstract methods and must therefore be declared abstract or implement the remaining methods (FOS\UserBundle\Model\UserInterface::setUsername, FOS\UserBundle\Model\UserInterface::getUsernameCanonical, FOS\UserBundle\Model\UserInterface::setUsernameCanonical, ...) in C:\xampp\htdocs\poterie-symf\poterie\vendor\sonata-project\user-bundle\Entity\BaseUser.php on line 21
```

the issue is already posted here with no answer http://stackoverflow.com/questions/37078278/symfony-sonatauser-error-with-abstract-method-of-baseuser.
Any help or advice regarding version compatibility will be welcome…

**Comment by Soullivaneuh** [comment]
As already said on https://github.com/sonata-project/SonataAdminBundle/issues/3991, please stop posting issue for just question.

Plus, this error is quite clear and say you have to implement needed methods.

If you find a bug, open another one and please again, **follow the bug format template**.

**Comment by utilisezlinux** [comment]
Ok, I understand perfectly, but…
Why do i have to manually implement methods in Sonata\UserBundle\Entity\BaseUser?
Because when I implements them in Application\Sonata\UserBundle\Entity\User, I still have the error…
Why do these methods miss in the class from source?
If I add it in the sonata bundle, won't it be overwritten with the next update?
Please tell me.
