### ISSUE TITLE
symfony 3 compatibility

### ISSUE THREAD

**Issue by RomainSanchez** [sonata-project/SonataUserBundle#777]
Hi , we are developing a project using a series of bundles we made [https://github.com/libre-informatique](url) extending mainly sonata admin, sonata doctrine orm and sonata user.We were hoping to adapt the project and the bundles it uses to use symfony 3 and all latest stable releases of sonata bundles.The bottom line is that we are still stuck because of the user bundle.So is there a definitive answer possible to this question : 

Do we adapt everything to work with all sonata 2.3 legacy(projects were using on 2.4 when started), or is there a point waiting for the user bundle to be compatible with symfony 3 (and if yes, will it be ready soon).

thanks for the help

**Comment by Soullivaneuh** [comment]
This question was asked many times on the issue tracker and the response is the same: The Symfony 3 support depends of the FOSUser 2.x support. In a nutshell: We are waiting for a 2.0 stable release.

Plus, you already ask for it in #728.

Please next time do some search before and avoid issue duplication.
