### ISSUE TITLE
Support for Symfony3.1.*

### ISSUE THREAD

**Issue by arman-mukatov** [sonata-project/SonataUserBundle#778]
Any plan to update for symfony3.1.2 ? I keep getting warning about the "Your requirements could not be resolved to an installable set of packages".

**Comment by greg0ire** [comment]
Hey, what if someone already asked this very question?

**Comment by arman-mukatov** [comment]
@greg0ire, perhaps ;-), as the support will be soon? or look for something else?

**Comment by Soullivaneuh** [comment]
Question many many many times and already answered many many times.

Stop create duplicate and do some search please!

**Comment by greg0ire** [comment]
What part of #777 don't you understand?

**Comment by arman-mukatov** [comment]
@greg0ire, why so nervous? feel relaxed all right!

@Soullivaneuh, ok, sorry!

**Comment by greg0ire** [comment]
> @greg0ire, why so nervous? feel relaxed all right!

Dunno. Might have to do with the fact that you're the second person to ask this just today, and this is the 4567865th about this. *breathes deeply*
