### ISSUE TITLE
SonataUserBundle with Symfony 3.1

### ISSUE THREAD

**Issue by boubouhkarim** [sonata-project/SonataUserBundle#783]
Hi everybody

I am using the sonata project 3.x branch as a back end for my project with symfony 3.1.

When i finished configuring and creating things i wander to add user management with SonataUserBundle but i couldn't install the bundle because of dependencies especially with FOSUserBundle. So

Is there any solution for now to make it work ?
If not should i roll back to symfony 2 ?

**Comment by Soullivaneuh** [comment]
Not compatible yet. Issue opened multiple time, please do search before asking.

**Comment by boubouhkarim** [comment]
yes i did search in old issues, firslty they are too old, and i'm wondering if there is any tweeks or i have to just roll back to symfony 2 please answer i have to make a decision now

**Comment by core23** [comment]
If you had used the search, you would know that the problem is the FOSUserBundle

**Comment by OskarStark** [comment]
Or you can try to work with this branch: https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2

but this is NOT STABLE yet

**Comment by Soullivaneuh** [comment]
> firslty they are too old

Last closed issue: 18 days ago. This is not old at all. Tricks and/or solutions was already discussed on other issues/PR.

Opening new issue just to have the same answer will be not efficient at all, people will get confused under a lot of  same kind issues.

You can be sure if we had right now the possibility to solve it with stable released, it will be already done.

You can also follow/help #745, this one is still opened.

I'm locking this issue, all information you need are already posted.

Regards.
