### ISSUE TITLE
Bare exception messages displayed on login page

### ISSUE THREAD

**Issue by Nepoh** [sonata-project/SonataUserBundle#788]
When an error occures during login, the exception message gets simply displayed above the login form. In my case a database error occures and something like

> An exception occurred while executing 'SELECT ...

is visible.

This behaviour has two mayor drawbacks:
* Sensitive and/or confusing error messages are leaked to the user
* Symfony's nice error pages in dev env are not displayed, so the error is harder to track down (EDIT: Just noticed that the error does not get logged, too)

**Comment by core23** [comment]
Sounds like a setup problem. Does the database exist?

**Comment by Nepoh** [comment]
It looks like I'm dealing with the error noticed here: FriendsOfSymfony/FOSUserBundle#1274 (maybe I messed up something in the entity mapping config).

But the exact error and it's cause is not the point here. What I wanted to say is: I think it's a bad idea to simply return the exception message to the user - an error like the one I encountered should be handled "the symfony way" (i.e. a HTTP 500 response, propper logging and error pages in dev and prod environment).

**Comment by core23** [comment]
Feel free to fix this with a PR

**Comment by ejkun** [comment]
Not sure about it, but I think is the same problem of the 'Bad credentials' message. Which is fixed on FoSUserBundle 2.0.
I'm working on a quickfix of it now, just rebuilding a old PR mine.

**Comment by greg0ire** [comment]
Witnessed the smart as @ejkun today

**Comment by ejkun** [comment]
I made the test, it is the same problem. Pulling a PR now.

**Comment by OskarStark** [comment]
@Nepoh can you please check if #791 fixes you rproblem?

**Comment by Nepoh** [comment]
Looks good! Thanks @ejkun for the fix.
