### ISSUE TITLE
How to send email when user is created in fos_user?

### ISSUE THREAD

**Issue by Sivanime** [sonata-project/SonataUserBundle#793]
I was just following the official symfony tutorial on how to send email : http://symfony.com/doc/current/bundles/FOSUserBundle/emails.html

But, it seems that your Bundle "prevents" from sending email using FOSUserBundle.

Please how to do that, thanks.

Regards,
Sivanime

**Comment by greg0ire** [comment]
> But, it seems that your Bundle "prevents" from sending email using FOSUserBundle.

Crazy idea: what if you elaborated on that part?

**Comment by Sivanime** [comment]
En français 👍 

Lors de la création d'un compte utilisateur, nous souhaiterions mettre en place un mail de validation (standard avec FOSUserBundle), mais il semblerait que le module Sonata le bloque.

**Comment by greg0ire** [comment]
I asked you to elaborate, not to translate, I understood quite well the first time, thanks. Please tell us more on how the Sonata module is blocking the email? What makes you say that the problem lies with the Sonata bundle?

**Comment by Soullivaneuh** [comment]
The issue tracker if for issue only (bug and feature request).

How to help questions must be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/sonata)

Plus, you question is concerning FOSUserBundle, not SonataUserBundle.

I close this one. If you really think a bug exists for SonataUserBundle, feel free to open a **new one** with all the details, following the issue template which is mandatory.

Regards.
