### ISSUE TITLE
The template "SonataUserBundle:Profile:edit_profile.html.twig" contains an error: Unexpected "render" tag

### ISSUE THREAD

**Issue by jsbuilder** [sonata-project/SonataUserBundle#862]
assetic.ERROR: The template "SonataUserBundle:Profile:edit_profile.html.twig" contains an error: Unexpected "render" tag (expecting closing tag for the "block" tag defined near line 19) in "SonataUserBundle:Profile:edit_profile.html.twig" at line 34.  

assetic.ERROR: The template "SonataUserBundle:Security:base_login.html.twig" contains an error: Unexpected "render" tag (expecting closing tag for the "block" tag defined near line 79) in "SonataUserBundle:Security:base_login.html.twig" at line 79. 

https://github.com/sonata-project/SonataUserBundle/blob/master/Resources/views/Profile/edit_profile.html.twig

{% render url("sonata_user_profile_edit_authentication") %}

#### Sonata packages

sonata-project/admin-bundle              3.14.0                                The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2                                 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7                                 Cache library
sonata-project/classification-bundle     3.3.0                                 Symfony SonataClassificationBundle
sonata-project/core-bundle               3.3.0                                 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1                                 Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                                 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.x-dev b97591c                       Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10                                Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1                                 Lightweight Exporter library
sonata-project/google-authenticator      1.0.2                                 Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0                                 Symfony SonataIntlBundle
sonata-project/media-bundle              3.5.0                                 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0                                 Symfony SonataNotificationBundle
sonata-project/user-bundle               dev-add_support_for_fos_user2 c029525 Symfony SonataUserBundle

#### Symfony packages

symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.6  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v3.1.10 The Symfony PHP framework

#### PHP version

PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

**Comment by greg0ire** [comment]
It should indeed be the render function, not the render tag. Can you make a PR to fix this?

**Comment by jsbuilder** [comment]
I'm just moved these templates and commented out the lines that have errors: 
app/Resources/SonataUserBundle/views/Profile/edit_profile.html.twig
comment line: 34

app/Resources/SonataUserBundle/views/Security/base_login.html.twig
comment line: 79

And fix wrong route in profile button
app/Resources/SonataUserBundle/views/Admin/Core/user_block.html.twig
fix line:9
`{% set _profile_uri       = sonata_user.userAdmin.isGranted('EDIT', app.user) ? sonata_user.userAdmin.generateUrl('edit', {id: app.user.username}) : sonata_user.userAdmin.generateUrl('show', {id: app.user.username}) %}`
to
`{% set _profile_uri       = sonata_user.userAdmin.isGranted('EDIT', app.user) ? sonata_user.userAdmin.generateUrl('edit', {id: app.user.id}) : sonata_user.userAdmin.generateUrl('show', {id: app.user.id}) %}`

**Comment by jordisala1991** [comment]
Can you take a look at this PR? https://github.com/sonata-project/SonataUserBundle/pull/861

We are working on that branch to make it more stable.
