### ISSUE TITLE
Is SonataUserBundle compatible with Symfony 3.2.*? 

### ISSUE THREAD

**Issue by luislaborda** [sonata-project/SonataUserBundle#877]
I saw already an issue around compatibility with Symfony 3.2, but I don't recall seeing a clear response. Is there any updates?

My composer output:
 - Installation request for sonata-project/user-bundle dev-master -> satisfiable by sonata-project/user-bundle[dev-master].
- Conclusion: don't install symfony/symfony v3.2.2
- sonata-project/user-bundle dev-master requires symfony/form ^2.3  -> satisfiable by symfony/form[v2.3.0, ...., v2.8.9]
- don't install symfony/form v2.8.9|don't install symfony/symfony v3.2.0

Thanks and my apologies if this has been already reported.

**Comment by marioafonso** [comment]
greetings,

I'm using Symfony 3.2.8.

I'm also using FOSUserBundle version 2.0 as the 1.3 version is targeted to older Symfony versions.

Running `composer require sonata-project/user-bundle` outputs this:

Using version ^3.2 for sonata-project/user-bundle
(...)

  Problem 1
    - sonata-project/user-bundle 3.2.3 requires friendsofsymfony/user-bundle ^1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7] but these conflict with your requirements or minimum-stability.
    - sonata-project/user-bundle 3.2.2 requires friendsofsymfony/user-bundle ^1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7] but these conflict with your requirements or minimum-stability.
    - sonata-project/user-bundle 3.2.1 requires friendsofsymfony/user-bundle ^1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7] but these conflict with your requirements or minimum-stability.
    - sonata-project/user-bundle 3.2.0 requires friendsofsymfony/user-bundle ^1.3 -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7] but these conflict with your requirements or minimum-stability.
    - Installation request for sonata-project/user-bundle ^3.2 -> satisfiable by sonata-project/user-bundle[3.2.0, 3.2.1, 3.2.2, 3.2.3].

So, sonata-project/user-bundle 3.2.0 requires friendsofsymfony/user-bundle ^1.3, but I have version 2.0 installed.

Shall I downgrade FOSUserBundle or wait for an update to sonata-project/user-bundle?

thanks

**Comment by marioafonso** [comment]
I just saw a pull request is on its way :)

https://github.com/sonata-project/SonataUserBundle/pull/869

I'll wait for this to be merged. Thanks.

**Comment by jordisala1991** [comment]
It is merged now. Closing
