### ISSUE TITLE
Issues with twig 2.x

### ISSUE THREAD

**Issue by Tofandel** [sonata-project/SonataUserBundle#883]
The profiles templates are not compatible with twig 2.x

They are usually throwing errors when rendering like : 

> "Using "null" for the value of node "translationBundle" of "Sonata\CoreBundle\Twig\Node\TemplateBoxNode" is not supported. You must pass a Twig_Node instance."

Or for the AdminBundle templates

> "Accessing Twig_Template attributes is forbidden."

But when you downgrade to twig 1.x the issue is gone.

Would be nice to have these templates compatible with twig 2

**Comment by greg0ire** [comment]
Would you like to provide PRs to fix that?

**Comment by Tofandel** [comment]
If I have time maybe, but I tried fixing it and didn't succeed. So switched back to twig 1.34.

**Comment by Soullivaneuh** [comment]
Is this issue still relevant?

**Comment by FireLizard** [comment]
Same issue here.

What does it mean ["You need to import the required macro(s) in every single .twig file."](https://stackoverflow.com/a/41590052)?
