### ISSUE TITLE
Sonata UserBundle install Issue Symfony[3.3.2]

### ISSUE THREAD

**Issue by jez1313** [sonata-project/SonataUserBundle#887]
#### Sonata packages : Sonata UserBundle

Hello, I have a problem installing Sonta UserBundle when I do 
php composer.phar require sonata-project / user-bundle --no-update
 then
 php composer.phar update
 I have the following error :
Problem 1 
-Conclusion: don't install sonata-project/user-bundle 3.2.4
-Conclusion: don't install sonata-project/user-bundle 3.2.3
-Conclusion: don't install sonata-project/user-bundle 3.2.2
-Conclusion: don't install sonata-project/user-bundle 3.2.1
-Conclusion: remove symfony/symfony v3.3.2 
........
Sorry if the problem has already been raised

**Comment by OskarStark** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

Currently the version 3 of user-bundle is not compatible with Sf3, you could try the dev-master, but we don't reccommend this...
