### ISSUE TITLE
Routing sonata_security_1.xml

### ISSUE THREAD

**Issue by ArmandArthur** [sonata-project/SonataUserBundle#895]
Hello,

I'm under symfony 3.3.6 and try do https://sonata-project.org/bundles/user/3-x/doc/reference/installation.html.

I finished the tutorial and i have en error:

```
(1/3) InvalidArgumentException
Unable to find file "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml".
```
Sure, the file doesn't existe in the repository vendor, why?

**Comment by jordisala1991** [comment]
If you are using Symfony 3.x, you must be using SonataUser dev-master, don't you?

follow those other installation instructions: https://sonata-project.org/bundles/user/master/doc/reference/installation.html

**Comment by ArmandArthur** [comment]
I don't know if i use dev-master. But i found the files on https://childrensrefuge.com/vendor/sonata-project/user-bundle/Resources/config/routing/.

**Comment by jordisala1991** [comment]
What do you have on composer.json?

**Comment by LeTo34** [comment]
I've the same problem. The xml files required not exist in the "@SonataUserBundle/Resources/config/routing" path.
The directory just content 3 files : 
admin_resetting.xml
admin_security.xml
api.xml

In my composer.json, I've this : "sonata-project/user-bundle": "dev-master"

**Comment by core23** [comment]
Please use the issue template. This will help us to analyse the issue

**Comment by Odpf** [comment]
Hello, 
I've the same problem. 
My composer.json : 
` "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "~3.0",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-fixtures-bundle": "~2.2",
        "stof/doctrine-extensions-bundle": "^1.2.2",
        "friendsofsymfony/user-bundle": "2.0.x-dev",
        "sonata-project/admin-bundle":"3.x-dev",
        "sonata-project/doctrine-orm-admin-bundle":"dev-master",
        "sonata-project/easy-extends-bundle":"2.x-dev",
        "sonata-project/user-bundle":"dev-master"`
Composer changes my requirements : 
` Problem 1
    - Can only install one of: sonata-project/easy-extends-bundle[2.x-dev, dev-master].
    - Can only install one of: sonata-project/easy-extends-bundle[dev-master, 2.x-dev].
    - sonata-project/user-bundle dev-master requires sonata-project/easy-extends-bundle ^2.2 -> satisfiable by sonata-project/easy-extends-bundle[2.x-dev].
    - Installation request for sonata-project/user-bundle dev-master -> satisfiable by sonata-project/user-bundle[dev-master].
    - Installation request for sonata-project/easy-extends-bundle dev-master -> satisfiable by sonata-project/easy-extends-bundle[dev-master].`
and :`Problem 1
    - Can only install one of: friendsofsymfony/user-bundle[2.0.x-dev, dev-master].
    - Can only install one of: friendsofsymfony/user-bundle[dev-master, 2.0.x-dev].
    - sonata-project/user-bundle dev-master requires friendsofsymfony/user-bundle ^2.0 -> satisfiable by friendsofsymfony/user-bundle[2.0.x-dev].
    - Installation request for sonata-project/user-bundle dev-master -> satisfiable by sonata-project/user-bundle[dev-master].
    - Installation request for friendsofsymfony/user-bundle dev-master -> satisfiable by friendsofsymfony/user-bundle[dev-master].`
I'm following the Documentations at 

> https://sonata-project.org/bundles/user/3-x/doc/reference/installation.html
with routing :`sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile`
But, I never had to add routes like sonata_security_1.xml. 
So, I don't know where Symfony can find them !

> Unable to find file "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
And an other error occured : 

> User provider "Sonata\UserBundle\Entity\UserManager" must implement "Symfony\Component\Security\Core\User\UserProviderInterface".

**Comment by jordisala1991** [comment]
You should follow install instructions for the version you are using.

In this case: https://sonata-project.org/bundles/user/4-x/doc/reference/installation.html

Closing for now. If you have this issue after following the correct install instructions, please provide more information and we will reopen.
