### ISSUE TITLE
PHP versions in Composer and Travis CI configs vary

### ISSUE THREAD

**Issue by jaikdean** [sonata-project/SonataUserBundle#897]
On the `master` (4.x-dev) branch, the `composer.json` specifies a requirement for PHP `^7.0`, however `.travis.yml` only tests with 7.1 and nightly versions.

I'm not sure what requirement has been decided on, but it looks like one of them needs correcting.

**Comment by greg0ire** [comment]
IIRC we decided to use 7.1 I'm on my phone and can hardly provide a source to back this up though

**Comment by jordisala1991** [comment]
Fixed: https://github.com/sonata-project/SonataUserBundle/pull/921
