### ISSUE TITLE
User Entity error on dev-master

### ISSUE THREAD

**Issue by borjadinamic** [sonata-project/SonataUserBundle#901]
Symfony 3.3 and installing SonataUserBundle dev-master to work with Symfony 3.3

#### Sonata packages

```
sonata-project/admin-bundle              3.22.0             3.22.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              1.0.7              Cache library
sonata-project/core-bundle               3.4.0              3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.6              3.1.6              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              1.7.1              Lightweight Exporter library
sonata-project/user-bundle               dev-master fca7672 dev-master fca7672 Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/assetic-bundle     v2.8.2  v2.8.2 Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.27 v3.3.8 Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.5.0  v1.5.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0  v1.5.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0  v1.5.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0  v1.5.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0  v1.5.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  v3.0.3 Symfony SwiftmailerBundle
symfony/symfony            v3.3.8  v3.3.8 The Symfony PHP framework
```

#### PHP version

```
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject

> User provider "Sonata\UserBundle\Entity\UserManager" must implement "Symfony\Component\Security\Core\User\UserProviderInterface".

## Steps to reproduce
Just install, configure and run

**Comment by borjadinamic** [comment]
I found a fix for it:

`use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * @author Hugo Briand <briand@ekino.com>
 */
class UserManager extends BaseUserManager implements UserManagerInterface, ManagerInterface, UserProviderInterface
{
    /**
     * {@inheritdoc}
     */
    public function findUsersBy(array $criteria = null, array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->getRepository()->findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * {@inheritdoc}
     */
    public function find($id)
    {
        return $this->getRepository()->find($id);
    }

    public function loadUserByUsername($username)
    {
        // TODO: Implement loadUserByUsername() method.
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user)
    {
        // TODO: Implement refreshUser() method.
    }

    public function supportsClass($class)
    {
        // TODO: Implement supportsClass() method.
    }`

**Comment by Matan** [comment]
@fdyckhoff fix works for me!

**Comment by borjadinamic** [comment]
Thanks for fix, closing.

**Comment by Matan** [comment]
@fdyckhoff will you create a PR? I don't want to run my project off a fork forever :D

**Comment by OskarStark** [comment]
Yes, please provide a PR against `master`

**Comment by OskarStark** [comment]
@jordisala1991 can you verify this?

**Comment by jordisala1991** [comment]
I didn't try it on SF3.3, on 3.2 it was not necessary. Maybe that was a change on Symfony?

**Comment by Matan** [comment]
Seems like @fdyckhoff is AKF. Mind if I create the PR?

**Comment by greg0ire** [comment]
We don't mind, please do.

**Comment by gomcodoctor** [comment]
simply use this

providers:
        fos_userbundle:
            id: fos_user.user_provider.username

Do not use fos_user.usermanager as documented in installation

**Comment by 0l1v3r5** [comment]
thanks! @gomcodoctor, it's working for me!

**Comment by 0l1v3r5** [comment]
thanks @gomcodoctor, it's working for me!

**Comment by jordisala1991** [comment]
Closing, discused on the PR also: https://github.com/sonata-project/SonataUserBundle/pull/905
