### ISSUE TITLE
After update version 2.0 got error "Unknown column type json requested"

### ISSUE THREAD

**Issue by jclopez** [sonata-project/SonataUserBundle#91]
"Unknown column type json requested".
SonataUserBundle 2.0

File: Resources/config/doctrine/BaseUser.orm.xml
Line: 25
<field name="facebookData"    type="json"       column="facebook_data"  nullable="true" />

**Comment by Corncakes** [comment]
Hi, I have the same problem '[Doctrine\DBAL\DBALException] Unknown column type "json" requested.'
Sonata Admin Bundle 2.3, User Bundle 2.2

app/autoload.php
`<?php

use Doctrine\Common\Annotations\AnnotationRegistry;
use Composer\Autoload\ClassLoader;

/**
 * @var ClassLoader $loader
 */
$loader = require __DIR__.'/../vendor/autoload.php';

AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

return $loader;
`

**Comment by Corncakes** [comment]
I find answer in other forum.....

For Doctrine Exception you must add a new Type Json

        types:
            json: Sonata\Doctrine\Types\JsonType
mentionned in https://sonata-project.org/bundles/notification/master/doc/reference/installation.html

from config.yml

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

**Comment by belguith** [comment]
Hello i have the same issue with JsonType

Fatal error: Class 'Sonata\Doctrine\Type\JsonType' not found in C:\wamp\www\WebApp\vendor\doctrine\dbal\lib\Doctrine\DBAL\Types\Type.php on line 172

Kernel and config are safe as i guess 
here is my app/config.yml
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

here is my Kernel

 #....other calls
new FOS\UserBundle\FOSUserBundle(),
            new Sonata\UserBundle\SonataUserBundle('FOSUserBundle'),
            new Sonata\CoreBundle\SonataCoreBundle(),
            new Sonata\BlockBundle\SonataBlockBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
            new Sonata\AdminBundle\SonataAdminBundle(),
            new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),
#.... othercalls

**Comment by ebuildy** [comment]
@belguith did you run ``composer require sonata-project/doctrine-extensions`` and double check the file is here.
