### ISSUE TITLE
Symfony Roles with hierachy are not translateable in SecurityRolesType

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataUserBundle#911]
#### Sonata packages

```
sonata-project/admin-bundle              3.23.0             = 3.23.0
sonata-project/block-bundle              3.4.0              = 3.4.0
sonata-project/cache                     1.0.7              = 1.0.7
sonata-project/core-bundle               3.5.1              = 3.5.1
sonata-project/datagrid-bundle           2.2.1              = 2.2.1
sonata-project/doctrine-extensions       1.0.2              = 1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.7              = 3.1.7
sonata-project/easy-extends-bundle       2.2.0              = 2.2.0
sonata-project/exporter                  1.7.1              = 1.7.1
sonata-project/user-bundle               dev-master a962eaa = dev-master a962eaa
```

#### Symfony packages

```
symfony/assetic-bundle     v2.8.2 = v2.8.2
symfony/monolog-bundle     v3.1.0 = v3.1.0
symfony/phpunit-bridge     v3.3.9 = v3.3.9
symfony/polyfill-apcu      v1.5.0 = v1.5.0
symfony/polyfill-intl-icu  v1.5.0 = v1.5.0
symfony/polyfill-mbstring  v1.5.0 = v1.5.0
symfony/polyfill-php56     v1.5.0 = v1.5.0
symfony/polyfill-php70     v1.5.0 = v1.5.0
symfony/polyfill-util      v1.5.0 = v1.5.0
symfony/security-acl       v3.0.0 = v3.0.0
symfony/swiftmailer-bundle v2.6.3 ~ v3.0.4
symfony/symfony            v3.3.9 = v3.3.9
```

#### PHP version

```
PHP 7.1.2 (cli) (built: Feb 14 2017 21:38:43) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

Symfony Roles are not translateable when using Roles for User Admin secruity when they have hierachy.

## Steps to reproduce
use `sonata.admin.security.handler.role` as `sonata_admin.security.handler`
have `security.role_hierarchy` with a role with hierachy like `ROLE_ADMIN:             [ROLE_USER, ROLE_SONATA_ADMIN]`
show the Secruity on a User in Backend.
## Expected results
`Translation not found. {"id":"ROLE_ADMIN","domain":"messages","locale":"de"}`
## Actual results
`Translation not found. {"id":"ROLE_ADMIN: ROLE_USER, ROLE_SONATA_ADMIN","domain":"messages","locale":"de"}`

## The Problem

Is how SecurityRolesType and EditableRolesBuilder does handle the Roles for the Form input is done,
That EditableRolesBuilder does already concat the Role and the subroles together, then SecurityRolesType just pass that list to it's parent ChoiceType.

## Possible Solution
The Role names should be translated before being concat, then SecurityRolesType should use false translation domain to show that the names are already translated

## PS
also the parent rules should problably not be added when SecurityRolesType expanded isn't set to true

## EDIT

- now that PR sonata-project/SonataAdminBundle#4670 got merged, the translation of the Roles can be disabled with `'choice_translation_domain' => false`

**Comment by Hanmac** [comment]
**Status Update:**

on **EditableRolesBuilder**:
i added Translator as dependency into EditableRolesBuilder, and have it translate the Roles if needed

with that, `ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]` would result in three translations, `ROLE_ADMIN`, `ROLE_USER` and `ROLE_SONATA_ADMIN`
I added `$domain` parameter to `getRoles` so it can be configured in the Type.

on **SecurityRolesType**:
i did configure the options like that
```php
public function configureOptions(OptionsResolver $resolver)
    {
        $rolesBuilder = $this->rolesBuilder;

        $resolver->setDefaults([
            'choices' => function (Options $options, $parentChoices) use ($rolesBuilder) {
                // primary translation domain
                $domain = $options['choice_translation_domain'];
                
                if ($domain === null) {
                    $domain = $options['sonata_field_description']->getAdmin()->getTranslationDomain();
                }
                list($roles, $rolesReadOnly) = $rolesBuilder->getRoles($domain);
                return empty($parentChoices) ? array_flip($roles) : [];
            },

            'read_only_choices' => function (Options $options) use ($rolesBuilder) {
                // primary translation domain
                $domain = $options['choice_translation_domain'];
                
                if ($domain === null) {
                    $domain = $options['sonata_field_description']->getAdmin()->getTranslationDomain();
                }
                list($roles, $rolesReadOnly) = $rolesBuilder->getRoles($domain);
                return empty($options['choices']) ? $rolesReadOnly : [];
            },
            'data_class' => null,
        ]);
    }
```
the setted option of the `choice_translation_domain` has higher priority, so the user can configure if he want to translate them or not, or what his own translation domain for the roles.

I am not happy yet that i need the getDomain stuff in both functions, i think i will put that into extra clossure.

later in `buildView`, i did disable `choice_translation_domain` with `false` again, because the choices are already translated

----

has someone else more Options, Request or Comments about this or should i try to make a pull request soon?

**Comment by Hanmac** [comment]
@greg0ire some of you guys more ideas what i should do with that, or can it be turned into a PR?

i currently did a bigger rewrite of the RoleBuilder to prevent it from making unnessesary (or failed) translations.

i think it isn't much of a BC break because it is an internal service that shouldn't be much used elsewhere

**Comment by greg0ire** [comment]
Please make a PR, we like to see code.

**Comment by Hanmac** [comment]
@greg0ire my current state is seen there:
https://github.com/Hanmac/SonataUserBundle/tree/security_roles_translation
i can make a branch of it soon

i just need to wait until i can run style checks (couldn't get the style run on windows)
