### ISSUE TITLE
Migrate to Symfony3

### ISSUE THREAD

**Issue by JonathanBaudoin** [sonata-project/SonataUserBundle#913]
Hi all,

This is not an issue, this is a proposal (I didn't know where to post).

My company works with Symfony and Sonata (Core, Admin, Media, Classification, User...). For now, we're on Symfony 2.8, but we would like to migrate to SF3 (3.3). It seems that only SonataUserBundle prevents us to do it. That's why we (my company) propose to help with the SF3 migration. We have already proposed some pull request to Sonata, but we are not very used to this process. Is there a way to have a roadmap (or there is just [this](https://github.com/sonata-project/SonataUserBundle/projects/1)), a todo list, and/or a bug list for SF3 ?

Thanks, and have a wonderful day.

**Comment by greg0ire** [comment]
@jordisala1991 can you help? IIRC master already has sf3 support, right?

**Comment by jordisala1991** [comment]
Master works with SF 3, but not with 3.3, there are some issues that are being worked AFAIK.

**Comment by baurelien** [comment]
@greg0ire Master may be compatible, but what prevents a stable 4.x version to be published ?

**Comment by greg0ire** [comment]
There are a number of depended on sonata libs that we wish to release first. See https://github.com/sonata-project/dev-kit/issues/216
cache and exporter are ready, for instance.

**Comment by JonathanBaudoin** [comment]
So if I understand, the 4.x depends on the list you mentioned ? Or maybe SF3 compatibility is for 3.x, and 4.x will be for SF4 ? Have you made a decision for that?

**Comment by Soullivaneuh** [comment]
Thanks for your interests.

As usual, you can help by proposing PR that fix compatibility issues on master.

For the releasing, this is just on WIP. But you can always use the master branch and lock at a specific commit waiting that. Use branch aliases if you have conflict issues.

You can also discuss about Sonata projects here: https://github.com/sonata-project/dev-kit/issues

I close this issue as there is nothing directly related to a bug or a feature request.

Best regards.

**Comment by greg0ire** [comment]
1. SF3 compat will be for SonataUser v4
2. SonataUser depends on
    - sonata-project/admin-bundle: need help
    - sonata-project/core-bundle: need help
    - sonata-project/datagrid-bundle: need help
    - sonata-project/doctrine-extensions: need help
    - sonata-project/easy-extends-bundle: almost ready
    - sonata-project/google-authenticator : done

Not sure if we will wait for the admin release, but the other should be released before, it's a realistic goal.
