### ISSUE TITLE
Sonata\UserBundle\Block\ classes used by Sonata ecommerce 

### ISSUE THREAD

**Issue by jeroendk** [sonata-project/SonataUserBundle#916]
In the dev-master / 4.x-dev branche the classes under Sonata\UserBundle\Block\  are deprecated. 
How should this be handled by the other bundles like the Sonata ecommerce bundle that uses "Sonata\UserBundle\Block\Breadcrumb\BaseUserProfileBreadcrumbBlockService"  ?

**Comment by core23** [comment]
Sorry, I don't get it. Which classes are you talking about? We don't have any deprecated classes under the package `Sonata\UserBundle\Block`.

**Comment by jeroendk** [comment]
Hi ! 

When i look at the master branche the block folder is not there right ? 
Perhaps I do not understand the versions yet but in this commit the classes seem to be removed: 
https://github.com/sonata-project/SonataUserBundle/commit/96ae5b93112aab464858992b79342c76be5bee4e

**Comment by jordisala1991** [comment]
We might need to restore them, but anyway you won't be able to configure ecommerce with SonataUser 4.x-dev because ecommerce is not compatible with Symfony 3.x ATM

**Comment by jeroendk** [comment]
In am working on that compatibility so that is why i saw this error



met vriendelijke groet,
Jeroen de Kok
lead developer

<http://www.aveq.nl> [cid:imagea83a70.PNG@d4f3000b.43996272] <http://www.aveq.nl/>

Koppelstokstraat 81<http://maps.google.com/?q=AveqGroep>
2583 CB  Den Haag<http://maps.google.com/?q=AveqGroep>
+31 (0)70 306 25 46<tel:+31703062546>

www.aveq.nl<http://www.aveq.nl>

<https://nl-nl.facebook.com/AVEQgroep> [cid:imagea78f8b.PNG@9c8d8975.4b9d0cb8] <https://nl-nl.facebook.com/AVEQgroep> [cid:imageb2b9d4.PNG@6d58cc52.43a37620] <https://twitter.com/aveqgroep> [cid:imagee11e3a.PNG@cb1acb3b.4cb0cc77] <https://nl.linkedin.com/company/aveq-groep> [cid:image3c529f.PNG@0ffac126.4684f6d5] <https://www.youtube.com/channel/UC5tDOz8R1ycOaLFeJ9X-Vig>


Op 4 okt. 2017 om 17:36 heeft Jordi Sala Morales <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


We might need to restore them, but anyway you won't be able to configure ecommerce with SonataUser 4.x-dev because ecommerce is not compatible with Symfony 3.x ATM

**Comment by quisse** [comment]
Any update on this?

**Comment by quisse** [comment]
Nevermind, spoke to @kunicmarko20 & they won't be restored. Guess this one can be closed then?

**Comment by kunicmarko20** [comment]
Well, not really like that. They _might_ be restored but no one really has time to try this.

**Comment by quisse** [comment]
Ok

**Comment by wbloszyk** [comment]
I will do it. It is part of TODO in [sandbox#616](https://github.com/sonata-project/sandbox/pull/616)

I will add it in suggest:
        "sonata-project/block-bundle": "For use blocks install ^3.13.2 || ^4.0 version",

Block Bundle 3.x is require in ecommerce:3.x Also support for BlockBundle 3.x will be drop in SonataUserBundle 5.x

**Comment by jordisala1991** [comment]
This was added to ecommerce, closing
