### ISSUE TITLE
Attempted to load class "ApplicationSonataUserBundle" from namespace "Application\Sonata\UserBundle".

### ISSUE THREAD

**Issue by itemvirtual** [sonata-project/SonataUserBundle#919]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
```
sonata-project/admin-bundle              3.23.0                                3.23.0                                The missing Symfony Admin Generator
sonata-project/block-bundle              3.4.0                                 3.4.0                                 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7                                 1.0.7                                 Cache library
sonata-project/core-bundle               3.5.1                                 3.5.1                                 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1                                 2.2.1                                 Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                                 1.0.2                                 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7                                 3.1.7                                 Symfony Sonata / Integrate Doctrine O...
sonata-project/easy-extends-bundle       2.2.0                                 2.2.0                                 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1                                 1.7.1                                 Lightweight Exporter library
sonata-project/google-authenticator      1.1.0                                 2.0.0                                 Library to integrate Google Authentic...
sonata-project/user-bundle               dev-add_support_for_fos_user2 99be909 dev-add_support_for_fos_user2 99be909 Symfony SonataUserBundle

#### Symfony packages

```
$ composer show --latest 'symfony/*'
```
symfony/monolog-bundle     v3.1.1  v3.1.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.10 v3.3.10 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0  v1.5.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0  v1.5.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0  v1.5.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0  v1.5.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0  v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0  v1.5.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  v3.1.0  Symfony SwiftmailerBundle
symfony/symfony            v3.3.10 v3.3.10 The Symfony PHP framework

#### PHP version

```
$ php -v
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

```

After follow the documentation of Sonata Admin:
https://sonata-project.org/bundles/user/3-x/doc/reference/installation.html

I add the class in AppKernel.php but always get this error:
```
(1/1) ClassNotFoundExceptionAttempted to load class "ApplicationSonataUserBundle" from namespace "Application\Sonata\UserBundle".Did you forget a "use" statement for another namespace?
```
--

**Comment by jlamur** [comment]
Did you follow the step `2.5. EXTENDING THE BUNDLE`:

```
php app/console sonata:easy-extends:generate SonataUserBundle -d src
```

**Comment by itemvirtual** [comment]
Hi Jlamur,
yes I have a folder called AppBunble and another called Application with Sonata/UserBundle and the file ApplicationSonataUserBundle.php

I don't understand the reason why my app don't load the other namespace.

Thanks
Fidel

**Comment by itemvirtual** [comment]
Hi, 
i solve it adding in composer:

"autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle",
            "Application\\": "src/Application"
        },

**Comment by jlamur** [comment]
Thank you for your feedback, hopefully it will help someone.

**Comment by greg0ire** [comment]
@itemvirtual could you please make a PR to update the docs?

**Comment by itemvirtual** [comment]
Hi Greg,
Sorry  I don't have experience in PR. 
You only have to add the composer comment in the 2.5. EXTENDING THE BUNDLE of sonara-project doc.
Thanks
Fidel

**Comment by greg0ire** [comment]
@itemvirtual can you please learn how to make a PR and then do it?

**Comment by itemvirtual** [comment]
@greg0ire 
do you have any documentation about good practices of PR?

Thanks
Fidel

**Comment by greg0ire** [comment]
We absolutely do, so after reading [this quick tutorial](https://yangsu.github.io/pull-request-tutorial/), you may read about 
[docs PR on Sonata](https://github.com/sonata-project/SonataUserBundle/blob/3.x/CONTRIBUTING.md#the-documentation)

**Comment by HassanGouzoul** [comment]
You should also excute a:  cmd $ composer dump-autoload after editing your composer.json  "autoload": {
        "psr-4": {
            "": "src/"
        },
