### ISSUE TITLE
Missing command in documentation in SonataUserBundle

### ISSUE THREAD

**Issue by itemvirtual** [sonata-project/SonataUserBundle#922]
**2.5. EXTENDING THE BUNDLE**

At this point, the bundle is functional, but not quite ready yet. You need to generate the correct entities for the media:
`php app/console sonata:easy-extends:generate SonataUserBundle -d src`
If you specify no parameter, the files are generated in app/Application/SonataUserBundle but you can specify the path with --dest=src
**Remind to register the new bundle in your composer.json in autoload psr-4 section, for exemple:**
<code>
        "psr-4": {
            "AppBundle\\": "src/AppBundle",
            "Application\\": "src/Application"
        },
</code>

**Comment by core23** [comment]
Can you create a PR with a doc update @itemvirtual ?

**Comment by jlamur** [comment]
Please do not open multiple issues for the same problem @itemvirtual.

Ref: #919
