### ISSUE TITLE
Move configuration defaults to the Configuration class

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataUserBundle#927]
### Subject

`Sonata\UserBundle\DependencyInjection\SonataUserExtension` class contains the following method, which is called from `Sonata\UserBundle\DependencyInjection\SonataUserExtension::load` method.

https://github.com/sonata-project/SonataUserBundle/blob/258192330405d49b5fc42be090572f6b3c5ac14a/DependencyInjection/SonataUserExtension.php#L208-L230

Please pay special attention to the following lines

https://github.com/sonata-project/SonataUserBundle/blob/258192330405d49b5fc42be090572f6b3c5ac14a/DependencyInjection/SonataUserExtension.php#L223-L224

Here I see several problems at once:
1. We have hardcoded class names, and we have **absolutely no guarantees** that these classes exist.
2. We use these class names as default values, without forcing the user to enter the actual values, while these default hardcoded values themselves may be incorrect.
3. We do all this in class `Sonata\UserBundle\DependencyInjection\SonataUserExtension`, so the user (and the `Sonata\UserBundle\DependencyInjection\Configuration` class) has no idea that these properties have default values.

### An example of a problem that I encountered

I'm not using `Application\Sonata\UserBundle...` class path for overridden user bundle in my application. Instead, I use `Overridden\Sonata\UserBundle...`, so the `Application` keyword does not concern me at all (**and is incorrect!**), but the code shown above makes it default. The `Configuration` does not force me to fill this values in config.

### What I suggest

1. Put the default configuration setting into the class `Configuration`.
2. Make default values to be **valid**, for example, using the standard, not overridden Entities (`Sonata\UserBundle\Entity\BaseUser` etc).
3. Make `SonataUserExtension::addDefaults` empty and remove in next major.
4. Modify the `SonataUserExtension::load` to check whether the `manager_type` config value corresponds to the `user` and `group` values.

**Comment by vyshkant** [comment]
Any ideas? I'll gladly write PR.

**Comment by greg0ire** [comment]
1. 👍 not sure how you are going to manage that though, since this default value depends on another config value (the model type)
2. not sure why `BaseUser` isn't abstract, but with such a name, I don't think it should be considered valid.
3. 👍 
4. consistency checks are good

**Comment by vyshkant** [comment]
> :+1: not sure how you are going to manage that though, since this default value depends on another config value (the model type)

Strictly speaking, at this point, according to my proposal, we don't check the correspondence between the `manager_type` value and the `user` and `group` classes values. But we will check it when the `SonataUserExtension::load` method is executed.

> 2. not sure why BaseUser isn't abstract, but with such a name, I don't think it should be considered valid.

Judging by the installation manual (https://sonata-project.org/bundles/user/master/doc/reference/installation.html#doctrine-configuration 2.3.1) the `BaseUser` class may be user as the `user_class` of `fos_user`.

**Comment by greg0ire** [comment]
Indeed! Go for it then.

**Comment by vyshkant** [comment]
But I think when we change the `Application\Sonata\UserBundle\Entity\User`, etc to `Sonata\UserBundle\Entity\BaseUser`, etc — this will break BC (for those users who use `Application` namespace for overridden bundle).

It means, that I should target `master` branch for this PR. In this case, should I mark the `SonataUserExtension::addDefaults` method as `deprecated`, or I can delete it (the BC will be already broken by changing default values)?

**Comment by greg0ire** [comment]
Deprecations make no sense if the PR is not BC, so just remove it. Think hard if you can make parts of this PR BC though.

**Comment by vyshkant** [comment]
Since the https://github.com/sonata-project/SonataUserBundle/pull/930 PR is merged, this issue can be closed?
