### ISSUE TITLE
DoctrineORM exception after composer update

### ISSUE THREAD

**Issue by IliyaKarkamov** [sonata-project/SonataUserBundle#942]
#### Sonata packages
sonata-project/admin-bundle              3.24.0             3.24.0            
sonata-project/block-bundle              3.5.0              3.5.0             
sonata-project/cache                     2.0.0              2.0.0             
sonata-project/core-bundle               3.6.0              3.6.0             
sonata-project/datagrid-bundle           2.2.1              2.2.1             
sonata-project/doctrine-extensions       1.0.2              1.0.2             
sonata-project/doctrine-orm-admin-bundle 3.1.7              3.1.7             
sonata-project/easy-extends-bundle       2.2.0              2.2.0             
sonata-project/exporter                  1.7.1              1.7.1             
sonata-project/formatter-bundle          3.3.0              3.3.0             
sonata-project/user-bundle               dev-master bd98e7c dev-master bd98e7c

#### Symfony packages
symfony/monolog-bundle     v3.1.1  v3.1.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.10 v3.3.10 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0  v1.6.0  Symfony polyfill backporting apcu...
symfony/polyfill-intl-icu  v1.6.0  v1.6.0  Symfony polyfill for intl's ICU-r...
symfony/polyfill-mbstring  v1.6.0  v1.6.0  Symfony polyfill for the Mbstring...
symfony/polyfill-php56     v1.6.0  v1.6.0  Symfony polyfill backporting some...
symfony/polyfill-php70     v1.6.0  v1.6.0  Symfony polyfill backporting some...
symfony/polyfill-util      v1.6.0  v1.6.0  Symfony utilities for portability...
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL ...
symfony/swiftmailer-bundle v2.6.7  v3.1.6  Symfony SwiftmailerBundle
symfony/symfony            v3.3.10 v3.3.10 The Symfony PHP framework

#### PHP version
PHP 7.1.8-1ubuntu1 (cli) (built: Aug  8 2017 15:57:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-1ubuntu1, Copyright (c) 1999-2017, by Zend Technologies

## Subject
I did composer update and the following packages were updated:
  - Updating doctrine/orm (v2.5.11 => v2.5.12): Loading from cache
  - Updating cocur/slugify (v2.5 => v3.0.1): Loading from cache
  - Updating sonata-project/core-bundle (3.5.1 => 3.6.0): Loading from cache
  - Updating sonata-project/cache (1.1.0 => 2.0.0): Loading from cache
  - Updating sonata-project/block-bundle (3.4.0 => 3.5.0): Loading from cache
  - Updating sonata-project/admin-bundle (3.23.0 => 3.24.0): Loading from cache
  - Updating sonata-project/formatter-bundle (3.2.3 => 3.3.0): Loading from cache
  - Updating doctrine/doctrine-bundle (1.7.1 => 1.7.2): Loading from cache
  - Updating doctrine/doctrine-fixtures-bundle (v2.4.0 => v2.4.1): Loading from cache
  - Updating sensiolabs/security-checker (v4.1.5 => v4.1.6): Loading from cache
  - Removing sonata-project/user-bundle (dev-master c8aa3ca)
  - Installing sonata-project/user-bundle (dev-master bd98e7c): Cloning bd98e7c40f from cache

and then when i tried to do: 

> php bin/console doctrine:schema:update --force

, i got the following exception: 

```
[Doctrine\ORM\ORMException]                                                  
  Column name `id` referenced for relation from Application\Sonata\UserBundle  
  \Entity\User towards Sonata\UserBundle\Entity\BaseGroup does not exist. 
```
I didnt make any changes to the generated Application/Sonata/UserBundle entities or doctrine orm configuration.

The problem occurred right after the update, im not sure where the problem comes from. I previewed all the changes between c8aa3ca bd98e7c but im not sure there is something that breaks it.

Here is my configuration:
```yaml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    from_email:
            address: ilia.karkamov@gmail.com
            sender_name: Iliya Karkamov

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager
```

Any ideas?

**Comment by Hanmac** [comment]
@OskarStark: my `Application\Sonata\UserBundle\Entity\User` needed extra defination of the id column

```php
    /**
     *
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
```

don't know if your code is missing that

**Comment by IliyaKarkamov** [comment]
Im using the easy-extends bundle generated configuration:
`<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                  http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="Application\Sonata\UserBundle\Entity\User" table="fos_user_user">

        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>

    </entity>

</doctrine-mapping>
`

**Comment by maavia10** [comment]
i have the same issue 
tried @Hanmac  solution but nothing happen same error occur

**Comment by maavia10** [comment]
i have re install sonata user bundle but issue still exist 
when i run sonata easy extend command it generate user and group 
![group](https://user-images.githubusercontent.com/3215908/32437461-4553fbce-c309-11e7-9fe5-e50e494305f7.png)
![user](https://user-images.githubusercontent.com/3215908/32437464-4598fe40-c309-11e7-9434-85e8d9d23740.png)

**Comment by maavia10** [comment]
i need help to resolve this issue as soon as possible

**Comment by Soullivaneuh** [comment]
@maavia10 Please use text copy/paste instead of IDE screenshots.

> i need help to resolve this issue as soon as possible

Well, like any user AFAIK. Just rollback to the last working version waiting that.

If it was master or another dev branches, then don't use master. Master is unstable, it's the goal of master branches. You can also rollback to a specific commit with composer.

**Comment by Hanmac** [comment]
@IliyaKarkamov i noticed it wrong.
it isn't the User which needed the id column, but the Group class.
checkout if it got some defination too

**Comment by maavia10** [comment]
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package sonata-project/user-bundle dev exists as sonata-project/user-bundle[2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.x-dev, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.3.0, 3.4.0, 3.5.0, 3.x-dev, dev-add_support_for_fos_user2, dev-develop, dev-master, 4.x-dev] but these are rejected by your constraint.

get this error after using dev for user-bundle

**Comment by Soullivaneuh** [comment]
@maavia10 `dev` is not a proper constraint and this is not related to the issue. Please ask for help on StackOverflow or Symfony Slack channel.

**Comment by maavia10** [comment]
"require": {
        "php": ">=5.5.9",
        "a2lix/i18n-doctrine-bundle": "^0.1.0",
        "a2lix/translation-form-bundle": "^2.1",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-migrations-bundle": "1.2.1",
        "doctrine/orm": "^2.5",
        "gesdinet/jwt-refresh-token-bundle": "^0.2.1",
        "incenteev/composer-parameter-handler": "^2.0",
        "jms/i18n-routing-bundle": "dev-master",
        "jms/serializer-bundle": "^2.2",
        "jms/translation-bundle": "^1.3",
        "lexik/jwt-authentication-bundle": "^2.4",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "sonata-project/admin-bundle": "^3.23",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "sonata-project/user-bundle": "dev",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "platform": {
            "php": "7.1"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.3-dev"
        }
    }
can you please see my composer.json file

**Comment by IliyaKarkamov** [comment]
@Hanmac there is an id configured aswell for the group entity. May the problem come from the orm or something?

**Comment by Soullivaneuh** [comment]
@maavia10 Again, this is not a help channel. Please stop posting answer about your issue to keep this one clean. I'll remove the last one.

Just rollback to your previous composer state. If have difficulties to do that, please ask for help on StackOverflow or Symfony Slack channels.

Regards.

**Comment by jordisala1991** [comment]
This PR is causing the issue: https://github.com/sonata-project/SonataUserBundle/pull/930

still investigating!

@vyshkant can you help us too?

**Comment by jordisala1991** [comment]
Found a solution..

On sonata_user config:

```
sonata_user:
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group
```

Not sure if the intention of the PR was to always have to define this default config or not.

**Comment by maavia10** [comment]
@jordisala1991  solved my problem thanks alot

**Comment by vyshkant** [comment]
The values `Application\Sonata\UserBundle\Entity\User` and `Application\Sonata\UserBundle\Entity\Group` are no longer default.

After https://github.com/sonata-project/SonataUserBundle/pull/930, their base classes — `Sonata\UserBundle\Entity\BaseUser` and `Sonata\UserBundle\Entity\BaseGroup` become default ones.

To use the child classes (in the example above — `Application\Sonata\UserBundle\Entity\User` and `Application\Sonata\UserBundle\Entity\Group`), you need to specify them in the config.

Perhaps the solution of this problem is to output another error message.

**Comment by IliyaKarkamov** [comment]
@jordisala1991 that worked, thanks!
@vyshkant That helped me understand where the problem comes from, thank you!

**Comment by vyshkant** [comment]
> That helped me understand where the problem comes from, thank you!

@IliyaKarkamov Could you please help me understand this problem?

If you don't mind, could you `var_dump` the variables `$actualModelClasses` and `$expectedModelClasses` in the method `Sonata\UserBundle\DependencyInjection\SonataUserExtension::checkManagerTypeToModelTypeMapping` (file `/path/to/your/project/vendor/sonata-project/user-bundle/DependencyInjection/SonataUserExtension.php` on line 292).

In addition, if you are not hard, could you also `var_dump` expressions `$ actualModelClass !== $expectedModelClass` and `is_subclass_of($actualModelClass, $expectedModelClass)` inside `if` statement before exception is thrown?

**Comment by IliyaKarkamov** [comment]
@vyshkant i wasnt able to evaluate the expressions inside the if statement because the expressions always return true. 

$actualModelClasses:
```
 array(4) {
  [0]=>
  string(33) "Sonata\UserBundle\Entity\BaseUser"
  [1]=>
  string(34) "Sonata\UserBundle\Entity\BaseGroup"
  [2]=>
  string(40) "Sonata\UserBundle\Admin\Entity\UserAdmin"
  [3]=>
  string(41) "Sonata\UserBundle\Admin\Entity\GroupAdmin"
}
```
and 
$expectedModelClasses:
```
array(4) {
  [0]=>
  string(33) "Sonata\UserBundle\Entity\BaseUser"
  [1]=>
  string(34) "Sonata\UserBundle\Entity\BaseGroup"
  [2]=>
  string(40) "Sonata\UserBundle\Admin\Entity\UserAdmin"
  [3]=>
  string(41) "Sonata\UserBundle\Admin\Entity\GroupAdmin"
}
```
that is the output without setting the sonata_user configuration for the default user and group classes. 

When i set the configuration for sonata_user to point to my classes i get this:

$actualModelClasses
```
array(4) {
  [0]=>
  string(41) "Application\Sonata\UserBundle\Entity\User"
  [1]=>
  string(42) "Application\Sonata\UserBundle\Entity\Group"
  [2]=>
  string(40) "Sonata\UserBundle\Admin\Entity\UserAdmin"
  [3]=>
  string(41) "Sonata\UserBundle\Admin\Entity\GroupAdmin"
}
```
$expectedModelClasses
```
array(4) {
  [0]=>
  string(33) "Sonata\UserBundle\Entity\BaseUser"
  [1]=>
  string(34) "Sonata\UserBundle\Entity\BaseGroup"
  [2]=>
  string(40) "Sonata\UserBundle\Admin\Entity\UserAdmin"
  [3]=>
  string(41) "Sonata\UserBundle\Admin\Entity\GroupAdmin"
}
```

**Comment by vyshkant** [comment]
@IliyaKarkamov Thanks!

**Comment by lukepass** [comment]
Thank you, that saved my life!
