### ISSUE TITLE
Unknown column type json requested.

### ISSUE THREAD

**Issue by zazoomauro** [sonata-project/SonataUserBundle#96]
i have this error when i tray to run php  app/console doctrine:schema:update. If I change manually in /vendor/bundles/Sonata/UserBundle/Resources/config/doctrine/BaseUser.orm.xml all json strings for array works...

**Comment by chris1312** [comment]
Consider this solution: http://stackoverflow.com/questions/43474145/unknown-column-type-json-requested-running-doctrine-2-migrations/43474146
