### ISSUE TITLE
Sonata User Admin services need to be public?

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataUserBundle#965]
i currently copied my project and did try to update everythnig,
like Symfony 3.4, SonataUserBundle dev-master (thanks for merging)

i don't know if that is more a bug in UserBundle, or something that should be changed inside the AdminBundle (thats why no PR yet)

and got messages like this:

> User Deprecated: The "sonata.user.admin.user" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
> User Deprecated: The "sonata.user.admin.group" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

this happend when `AdminListBlockService` calls `$this->pool->getDashboardGroups()`
and then the pool try to ask the container with `$this->getInstance($item['admin'])`
then the container sees that the service is private and does this

a possible short fix (which i could make as PR) would be to make the two admin services public so that the pool can find them
I needed to do that for my admin services too.

An different, more complicated Fix would be to make the thing that checks for `sonata.admin` tags, inject the service somehow into the pool. But i don't know if that would work that easy or if that even is possible

**Comment by greg0ire** [comment]
Please go the short fix way at first, we'll try to rework this but since it will probably require some BC-breaks, it will come later and will be done on the unstable branch

**Comment by Hanmac** [comment]
@greg0ire okay i will do the short fix with adding `public="true"` into admin_orm.xml and admin_mongodb.xml files

because making this services public should change/break anything for sonata itself, 
should this changes be done into the 3.0 branch of the userbundle?

**Comment by greg0ire** [comment]
nah do it on the master branch, we are supposed to release it "soon" anyway

**Comment by Hanmac** [comment]
close because PR merged
