### ISSUE TITLE
[4.0] way to disable checkManagerType or allow FOSUser as parent?

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataUserBundle#967]
For one of my projects i used FOSUser as base class for my admin users because the Sonata users had too much Social Media stuff i didn't wanted as entries in the backend or the database.

I did wrote my own admin classes, extending the ones from Sonata, removed the Social Media stuff and it worked.

but now with checkManagerTypeToModelTypeMapping it doesn't work anymore and i need to extend from SonataUsers and do get the the facebook fields in the  database even if i don't want to.

could there be a way to disable the checkMangerType via a config flag, or allow FOSUser(Interface) / FOSGroup(Interface) to be a parent of that stuff?

**Comment by jeroendk** [comment]
I also ran into this problem.
@greg0ire @vyshkant So the check on the admin class was removed in #950, but the check on the correct admin class is still there. Is this on purpose ? Before the update we were able to use custom user classes.

**Comment by vyshkant** [comment]
I can only say that this problem appeared because of my patch. And, apparently, this is a violation of backward compatibility, which is permissible in the `master` branch.
The question remains: what to do next? Leave as is, or remove `checkManagerTypeToModelTypeMapping` method?
And we are stuck deciding what to do with this: https://github.com/sonata-project/SonataUserBundle/pull/930#issuecomment-342327896

I'll gladly write the patches to solve this problem and the problem with invalid default values, but I need to know your opinion, @greg0ire @jordisala1991 @OskarStark @Soullivaneuh @core23

**Comment by greg0ire** [comment]
1. I don't use the SonataUserBundle.
2. I voted nonetheless because I don't want things to get stuck.

If you both use this bundle, please decide together what to do next.

**Comment by jeroendk** [comment]
_compatibility, which is permissible in the master branch._ thats true but why did you added the check ? Everything seem to work fine with custom user & admin classes.

**Comment by vyshkant** [comment]
> compatibility,  which is permissible in the master branch. thats true but why did you added the check ? Everything seem to work fine with custom user & admin classes.

I did not take into account that such a situation can be. But it's not my decision whether we should allow this. I propose to wait for the others.

**Comment by jordisala1991** [comment]
My opinion is:

Admin classes should not extend always from baseuser class. The extension point here should be there to allow to modify completely the form, without restrictions.

**Comment by Hanmac** [comment]
@jordisala1991 the problem isnt the admin class but the user/group classes

Sometimes it's a good idea to use Fos User(interface) as base instead of Sonata User

**Comment by vyshkant** [comment]
I'll provide a PR solving this problem.

**Comment by vyshkant** [comment]
And what branch should I target? In `3.x` the problem is the same, does it mean that I should target `3.x`?

**Comment by greg0ire** [comment]
@vyshkant you should target 4.x, since we no longer merge 3.x in 4.x. People that badly need your fix on 3.x can backport it.

**Comment by peter-gribanov** [comment]
@OskarStark problem is not solved yet. We still must to extend `Sonata\UserBundle\Entity\BaseUser` if we want to expand only  `FOS\UserBundle\Model\FosUserInterface`.

As i [said before](https://github.com/sonata-project/SonataUserBundle/pull/980#issuecomment-369234265), will be better inverting the nonconformity check.
If manager type is `orm` then User class should not extends [**ODM** implementation](https://github.com/sonata-project/SonataUserBundle/blob/master/src/Document/BaseUser.php).
If manager type is `mongodb` then User class should not extends [**ORM** implementation](https://github.com/sonata-project/SonataUserBundle/blob/master/src/Entity/BaseUser.php).

As @jordisala1991 [said](https://github.com/sonata-project/SonataUserBundle/pull/980#issuecomment-381893326), will be better restriction on the lowest possible level.
For user: `FOS\UserBundle\Model\UserInterface`
For group: `FOS\UserBundle\Model\GroupInterface`

**Comment by OskarStark** [comment]
Hey Peter, thanks for the feedback.

> If manager type is orm then User class should not extends ODM implementation.

`orm` -> ODM ?

> If manager type is mongodb then User class should not extends ORM implementation.

`mongodb` -> ORM?

I am a bit confused by this 🤔

**Comment by peter-gribanov** [comment]
@OskarStark is said:
> should **not** extends

* It is important that the user class is implements `FOS\UserBundle\Model\UserInterface`.
* The problem suggests that it is important for us to create a custom class that does not implement `Sonata\UserBundle\Model\UserInterface`.
* I don’t know why you divide ORM (`Entity`) and ODM (`Document`), but it’s clear that the user class shouldn’t expand `Sonata\UserBundle\Document\BaseUser` if we use `orm` manager type.

**Comment by peter-gribanov** [comment]
If you allow not to use `Sonata\UserBundle\Model\UserInterface`, and do not invert the nonconformity 
check, then `checkManagersType` does not make sense at all and should be removed.

**Comment by peter-gribanov** [comment]
* Custom user class should implements `FOS\UserBundle\Model\UserInterface`;
* Custom user class can, but not required to implements `Sonata\UserBundle\Model\UserInterface`;
* Custom user class can, but not required to implements `Sonata\UserBundle\Entity\BaseUser` if we use `orm` manager type;
* Custom user class must not implements `Sonata\UserBundle\Document\BaseUser` if we use `orm` manager type.
