### ISSUE TITLE
[4.0] Why SonataUserBundle is not parent of FOSUserBundle?

### ISSUE THREAD

**Issue by bartosz-malec** [sonata-project/SonataUserBundle#976]
Hi,

I would like to ask why new version of SonataUserBundle is not a parent of FOSUserBundle? May it be optional configurable by constructor?

**Comment by greg0ire** [comment]
I think having a parent bundle is deprecated.

**Comment by bartosz-malec** [comment]
Yes, that's true, but what if someone uses bundle which extends SonataUserBundle? Now library is lighter, but... In this situation I need to do two new bundles. First one to extend FOSUserBundle and second one to extend SonataUserBundle. I am not sure, that the idea about removing support for extensions was fine.

**Comment by greg0ire** [comment]
Why would you need 2 new bundles?

**Comment by bartosz-malec** [comment]
First one is company bundle loaded by Satis, which extends e.g. login layout of SonataUserBundle. Second one is application bundle which should extends FOS/SonataUserBundle functionalities. After upgrade to 4.0, application bundle must extends FOSUserBundle, so in the same bundle I can not extend e.g. company bundle functionalities which extends SonataUserBundle.

I think it will be big change for most of us.

**Comment by Hanmac** [comment]
@bartosz-malec the problem is that Symfony itself doesn't support parent bundle anymore
so SonataUserBundle can't do many things about that
