### ISSUE TITLE
Be able to use Nelmio 3.0 Version

### ISSUE THREAD

**Issue by jchesne** [sonata-project/SonataUserBundle#988]
I saw Nelmio 3.0 version is in conflict since 30 June 2016 - [See the commit](https://github.com/sonata-project/SonataUserBundle/commit/fcef4a6f3ab4d8d3992fe17b7f091b1fd6d8a899#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780).
I really need to use the 3.0 version, when do you think we will be able to use it ?

Thanks,

Jérôme

**Comment by OskarStark** [comment]
did you try to make it work in your project? If yes, feel free to create a PR

**Comment by ibogdan94** [comment]
I am also need this

**Comment by ibogdan94** [comment]
@OskarStark Please, see https://github.com/sonata-project/SonataUserBundle/pull/989
