### ISSUE TITLE
SF4 drops ACL support.  mod UserBundle for use with 'symfony/acl-bundle' or switch to Voters?

### ISSUE THREAD

**Issue by pool0022** [sonata-project/SonataUserBundle#997]
trying to enable ACL use in UserBundle with SF4

i've got
```
packages/sonata.yaml
	sonata_user:
	    security_acl: true
	    manager_type: orm # can be orm or mongodb

	sonata_block:
	    default_contexts: [cms]
	    blocks:
	        sonata.admin.block.admin_list:
	            contexts: [admin]
	        sonata.user.block.menu:
	        sonata.user.block.account:
	        sonata.block.service.text:
```

and in

```
config/security.yml
	security:
	    encoders:
	        FOS\UserBundle\Model\UserInterface: argon2i

	    acl:
	        connection: default

	    role_hierarchy:
	        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
	        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
```

with that, I'm getting error:

```
 Unrecognized option "acl" under "security"
```

Although related config options appear in

 ["security.acl.voter.user_permissions" has a dependency on a non-existent service "security.acl.provider" #975](https://github.com/sonata-project/SonataUserBundle/issues/975)

and this doc

[SF4>Documentation>Bundles>SonataAdminBundle>5. Security](https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/security.html)

still refers to ACL usage.

But, According to

[SF4>Documentation>Security>How to Use Access Control Lists (ACLs)](https://symfony.com/doc/current/security/acl.html)
 
> ACL support was removed in Symfony 4.0. Install the Symfony ACL bundle and refer to its documentation if you want to keep using ACL.

And in the '**_new_**' ACL bundle docs
[How to Use Access Control Lists (ACLs)](https://github.com/symfony/acl-bundle/blob/master/src/Resources/doc/index.rst)

looks like at least additional config will be required for use with UserBundle.

Is that the direction UserBundle plans?  Or to follow the suggestion

> Using ACL's isn't trivial, and for simpler use cases, it may be overkill. If your permission logic could be described by just writing some code (e.g. to check if a Blog is owned by the current User), then consider using Symfony built-in security voters.

and remove it, replacing with Voters?

**Comment by greg0ire** [comment]
I think we probably should go the acl bundle route, and reconsider removing ACLs on next Sonata major

**Comment by divined** [comment]
And how it must work now?

**Comment by asassoye** [comment]
@divined, symfony/acl-bundle is a bundle now. 
To configure:
```yaml
security:
    …

acl:
    connection: default
```

and not:
```yaml
security:
    acl:
        connection: default
```

Here is the documentation: [https://github.com/symfony/acl-bundle/blob/master/src/Resources/doc/index.rst](url)

**Comment by asassoye** [comment]
@greg0ire please don't remove ACL from Sonata
